"""@brief Billing 应用命令与结果 / Billing application commands and results."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from fogmoe_bot.domain.billing._validation import normalize_instant, normalize_text
from fogmoe_bot.domain.billing.entitlements import EntitlementGrant, Subscription
from fogmoe_bot.domain.billing.orders import Order, PaymentEvent, PaymentEventKind
from fogmoe_bot.domain.billing.refunds import Refund


class BillingCode(StrEnum):
    """@brief Billing 用例结果代码 / Billing use-case result code."""

    SUCCESS = "success"
    """@brief 操作已成功提交 / Operation committed successfully."""

    NOT_REGISTERED = "not_registered"
    """@brief 用户尚无账户 / User does not have an account."""

    NOT_FOUND = "not_found"
    """@brief 产品、订单、退款或订阅不存在 / Product, order, refund, or subscription was not found."""

    FORBIDDEN = "forbidden"
    """@brief 操作者无权限 / Actor is not authorized."""

    OFFER_UNAVAILABLE = "offer_unavailable"
    """@brief 报价不再可售 / Offer is no longer available."""

    PAYMENT_UNVERIFIED = "payment_unverified"
    """@brief 渠道事件未通过外部验证 / Provider event did not pass external verification."""

    INVALID_PAYMENT_EVENT = "invalid_payment_event"
    """@brief 事件类型不适用于该用例 / Event kind does not apply to this use case."""

    INVALID_STATE = "invalid_state"
    """@brief 聚合不处于可变迁状态 / Aggregate is not in a transitionable state."""

    CONFLICT = "conflict"
    """@brief 幂等键或乐观并发发生冲突 / Idempotency or optimistic-concurrency conflict."""


class RefundReviewDecision(StrEnum):
    """@brief 后台对退款申请的审核决定 / Back-office review decision for a refund request."""

    APPROVE = "approve"
    """@brief 批准并等待支付渠道结算 / Approve and await provider settlement."""

    REJECT = "reject"
    """@brief 拒绝且恢复原订单履约状态 / Reject and restore original order fulfillment state."""


@dataclass(frozen=True, slots=True)
class PlaceOrder:
    """@brief 以当前可售报价创建订单 / Create an order from a currently sellable offer.

    @param buyer_id 下单用户 / Ordering user.
    @param offer_id 报价标识 / Offer identity.
    @param order_id 入口预先生成的订单标识 / Order identity generated by the entry point.
    @param created_at 创建时刻 / Creation instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @param renewal_subscription_id 可选待续费订阅标识 / Optional subscription identity to renew.
    @note 客户端不能传入价格；端口必须冻结已验证 Offer 的原生价格。/
        A client cannot provide a price; the port must freeze the verified Offer's native price.
    """

    buyer_id: int
    """@brief 下单用户 / Ordering user."""

    offer_id: UUID
    """@brief 报价标识 / Offer identity."""

    order_id: UUID
    """@brief 订单标识 / Order identity."""

    created_at: datetime
    """@brief 创建时刻 / Creation instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    renewal_subscription_id: UUID | None = None
    """@brief 可选待续费订阅标识 / Optional subscription identity to renew."""

    def __post_init__(self) -> None:
        """@brief 验证下单命令 / Validate order-placement command.

        @return None / None.
        @raise ValueError 用户、时刻或幂等键非法时抛出 /
            Raised when user, instant, or idempotency key is invalid.
        """

        _require_positive_user(self.buyer_id, field="Order buyer")
        object.__setattr__(
            self,
            "created_at",
            normalize_instant(self.created_at, field="Order creation time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class RecordPaymentEvent:
    """@brief 记录已验证的付款或争议事件 / Record a verified payment or chargeback event.

    @param event 已验真的支付渠道事件 / Verified payment-provider event.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @note Refund 事件必须使用 ``SettleRefund``，从而与 Refund 聚合一起结算。/
        Refund events must use ``SettleRefund`` so they settle with the Refund aggregate.
    """

    event: PaymentEvent
    """@brief 已验真的支付渠道事件 / Verified payment-provider event."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证普通支付事件命令 / Validate ordinary payment-event command.

        @return None / None.
        @raise TypeError 事件类型非法时抛出 / Raised when event has an invalid type.
        @raise ValueError 事件是退款事件或幂等键非法时抛出 /
            Raised when event is a refund event or key is invalid.
        """

        if not isinstance(self.event, PaymentEvent):
            raise TypeError("Billing payment event must be a PaymentEvent")
        if self.event.kind in {
            PaymentEventKind.REFUND_SUCCEEDED,
            PaymentEventKind.REFUND_FAILED,
        }:
            raise ValueError("Refund events must be recorded through SettleRefund")
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class FulfillOrder:
    """@brief 将已付款订单原子履约 / Atomically fulfill a paid order.

    @param order_id 待履约订单标识 / Order identity to fulfill.
    @param operator_id 执行履约的后台人员 / Back-office operator performing fulfillment.
    @param fulfilled_at 履约时刻 / Fulfillment instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    """

    order_id: UUID
    """@brief 待履约订单标识 / Order identity to fulfill."""

    operator_id: int
    """@brief 执行履约的后台人员 / Back-office operator performing fulfillment."""

    fulfilled_at: datetime
    """@brief 履约时刻 / Fulfillment instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证履约命令 / Validate fulfillment command.

        @return None / None.
        @raise ValueError 操作者、时刻或幂等键非法时抛出 /
            Raised when operator, instant, or idempotency key is invalid.
        """

        _require_positive_user(self.operator_id, field="Fulfillment operator")
        object.__setattr__(
            self,
            "fulfilled_at",
            normalize_instant(self.fulfilled_at, field="Order fulfillment time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class RequestRefund:
    """@brief 用户对已履约订单申请退款 / User requests a refund for a fulfilled order.

    @param requester_id 申请退款的用户 / User requesting refund.
    @param order_id 所属订单标识 / Owning order identity.
    @param refund_id 入口预先生成的退款标识 / Refund identity generated by the entry point.
    @param reason 用户说明的退款原因 / User-provided refund reason.
    @param requested_at 申请时刻 / Request instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @note 退款金额必须从订单冻结价格取得，不能由客户端指定。/
        Refund amount must come from the order's frozen price and cannot be client supplied.
    """

    requester_id: int
    """@brief 申请退款的用户 / User requesting refund."""

    order_id: UUID
    """@brief 所属订单标识 / Owning order identity."""

    refund_id: UUID
    """@brief 退款标识 / Refund identity."""

    reason: str
    """@brief 用户说明的退款原因 / User-provided refund reason."""

    requested_at: datetime
    """@brief 申请时刻 / Request instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证退款申请命令 / Validate refund-request command.

        @return None / None.
        @raise ValueError 用户、原因、时刻或幂等键非法时抛出 /
            Raised when user, reason, instant, or idempotency key is invalid.
        """

        _require_positive_user(self.requester_id, field="Refund requester")
        object.__setattr__(
            self,
            "reason",
            normalize_text(
                self.reason,
                field="Refund reason",
                minimum_length=1,
                maximum_length=1_000,
            ),
        )
        object.__setattr__(
            self,
            "requested_at",
            normalize_instant(self.requested_at, field="Refund request time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class ReviewRefund:
    """@brief 后台审核退款申请 / Back office reviews a refund request.

    @param refund_id 待审核退款标识 / Refund identity to review.
    @param reviewer_id 审核人员 / Reviewer identity.
    @param decision 批准或拒绝 / Approval or rejection decision.
    @param reviewed_at 审核时刻 / Review instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @param note 可选审核说明 / Optional review note.
    """

    refund_id: UUID
    """@brief 待审核退款标识 / Refund identity to review."""

    reviewer_id: int
    """@brief 审核人员 / Reviewer identity."""

    decision: RefundReviewDecision
    """@brief 批准或拒绝决定 / Approval or rejection decision."""

    reviewed_at: datetime
    """@brief 审核时刻 / Review instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    note: str | None = None
    """@brief 可选审核说明 / Optional review note."""

    def __post_init__(self) -> None:
        """@brief 验证退款审核命令 / Validate refund-review command.

        @return None / None.
        @raise TypeError 审核决定类型非法时抛出 / Raised when review decision has an invalid type.
        @raise ValueError 审核人员、时刻、说明或幂等键非法时抛出 /
            Raised when reviewer, instant, note, or idempotency key is invalid.
        """

        _require_positive_user(self.reviewer_id, field="Refund reviewer")
        if not isinstance(self.decision, RefundReviewDecision):
            raise TypeError("Refund decision must be a RefundReviewDecision")
        object.__setattr__(
            self,
            "reviewed_at",
            normalize_instant(self.reviewed_at, field="Refund review time"),
        )
        if self.note is not None:
            object.__setattr__(
                self,
                "note",
                normalize_text(
                    self.note,
                    field="Refund review note",
                    minimum_length=1,
                    maximum_length=1_000,
                ),
            )
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class SettleRefund:
    """@brief 以已验证渠道事件结算退款 / Settle a refund from a verified provider event.

    @param refund_id 待结算退款标识 / Refund identity to settle.
    @param event 已验证的退款渠道事件 / Verified provider refund event.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    """

    refund_id: UUID
    """@brief 待结算退款标识 / Refund identity to settle."""

    event: PaymentEvent
    """@brief 已验证的退款渠道事件 / Verified provider refund event."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证退款结算命令 / Validate refund-settlement command.

        @return None / None.
        @raise TypeError 事件类型非法时抛出 / Raised when event has an invalid type.
        @raise ValueError 事件不是退款事件或幂等键非法时抛出 /
            Raised when event is not a refund event or key is invalid.
        """

        if not isinstance(self.event, PaymentEvent):
            raise TypeError("Refund settlement event must be a PaymentEvent")
        if self.event.kind not in {
            PaymentEventKind.REFUND_SUCCEEDED,
            PaymentEventKind.REFUND_FAILED,
        }:
            raise ValueError("Refund settlement requires a refund payment event")
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class CancelSubscription:
    """@brief 请求在当前周期结束时取消订阅 / Request subscription cancellation at current-period end.

    @param owner_id 发起取消的订阅拥有者 / Subscription owner requesting cancellation.
    @param subscription_id 待取消订阅标识 / Subscription identity to cancel.
    @param requested_at 请求时刻 / Request instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    """

    owner_id: int
    """@brief 发起取消的订阅拥有者 / Subscription owner requesting cancellation."""

    subscription_id: UUID
    """@brief 待取消订阅标识 / Subscription identity to cancel."""

    requested_at: datetime
    """@brief 请求时刻 / Request instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证订阅取消命令 / Validate subscription-cancellation command.

        @return None / None.
        @raise ValueError 用户、时刻或幂等键非法时抛出 /
            Raised when user, instant, or idempotency key is invalid.
        """

        _require_positive_user(self.owner_id, field="Subscription owner")
        object.__setattr__(
            self,
            "requested_at",
            normalize_instant(
                self.requested_at,
                field="Subscription cancellation request time",
            ),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            _normalize_idempotency_key(self.idempotency_key),
        )


@dataclass(frozen=True, slots=True)
class BillingResult:
    """@brief Billing 写用例的可重放结果 / Replayable result of a Billing write use case.

    @param code 结果代码 / Result code.
    @param order 可选订单快照 / Optional order snapshot.
    @param refund 可选退款快照 / Optional refund snapshot.
    @param entitlements 本次履约或撤销涉及的权益 / Entitlements involved in fulfillment or revocation.
    @param subscription 可选订阅快照 / Optional subscription snapshot.
    @param replayed 结果是否来自幂等重放 / Whether result came from idempotent replay.
    """

    code: BillingCode
    """@brief 结果代码 / Result code."""

    order: Order | None = None
    """@brief 可选订单快照 / Optional order snapshot."""

    refund: Refund | None = None
    """@brief 可选退款快照 / Optional refund snapshot."""

    entitlements: tuple[EntitlementGrant, ...] = ()
    """@brief 涉及的权益快照 / Entitlement snapshots involved."""

    subscription: Subscription | None = None
    """@brief 可选订阅快照 / Optional subscription snapshot."""

    replayed: bool = False
    """@brief 结果是否来自幂等重放 / Whether result came from idempotent replay."""


def _require_positive_user(value: int, *, field: str) -> None:
    """@brief 校验应用命令中的正用户标识 / Validate a positive user identity in an application command.

    @param value 原始用户标识 / Raw user identity.
    @param field 出错信息中的字段名称 / Field name for error messages.
    @return None / None.
    @raise TypeError 用户标识不是严格整数时抛出 / Raised when user identity is not a strict integer.
    @raise ValueError 用户标识不为正时抛出 / Raised when user identity is not positive.
    """

    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{field} must be an integer")
    if value <= 0:
        raise ValueError(f"{field} must be positive")


def _normalize_idempotency_key(value: str) -> str:
    """@brief 规范化业务幂等键 / Normalize a business idempotency key.

    @param value 原始幂等键 / Raw idempotency key.
    @return 规范化幂等键 / Normalized idempotency key.
    @raise ValueError 幂等键为空或过长时抛出 / Raised when key is blank or oversized.
    """

    return normalize_text(
        value,
        field="Billing idempotency key",
        minimum_length=1,
        maximum_length=200,
    )
