"""@brief 银行应用命令和结果 / Banking application commands and results."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from fogmoe_bot.domain.banking.money import TokenAmount, TokenBucket, WalletBalance
from fogmoe_bot.domain.banking.requests import TokenRequest, TokenRequestStatus


class BankCode(StrEnum):
    """@brief 银行用例结果代码 / Bank use-case result code."""

    SUCCESS = "success"
    """@brief 操作成功 / Operation succeeded."""

    NOT_REGISTERED = "not_registered"
    """@brief 用户账户未注册 / User account is not registered."""

    NOT_FOUND = "not_found"
    """@brief 请求不存在 / Request does not exist."""

    NOT_PENDING = "not_pending"
    """@brief 请求不再等待审核 / Request is no longer awaiting review."""

    FORBIDDEN = "forbidden"
    """@brief 操作者无权限 / Actor is not authorized."""

    INSUFFICIENT_FUNDS = "insufficient_funds"
    """@brief 可用资金不足 / Available funds are insufficient."""


class TokenReviewDecision(StrEnum):
    """@brief 管理员对请求的审核决定 / Administrator review decision."""

    APPROVE = "approve"
    """@brief 批准并发行免费代币 / Approve and issue free tokens."""

    REJECT = "reject"
    """@brief 拒绝且不发行代币 / Reject without issuing tokens."""


@dataclass(frozen=True, slots=True)
class RequestTokens:
    """@brief 用户请求免费活动代币 / User request for free activity tokens.

    @param user_id 申请用户 / Requesting user.
    @param amount 请求金额 / Requested amount.
    @param purpose 用途说明 / Purpose statement.
    @param requested_at 请求时刻 / Request instant.
    @param idempotency_key 幂等键 / Idempotency key.
    @param request_id 由入口预先生成的请求 ID / Request ID generated by the entry point.
    """

    user_id: int
    """@brief 申请用户 / Requesting user."""

    amount: TokenAmount
    """@brief 请求金额 / Requested amount."""

    purpose: str
    """@brief 用途说明 / Purpose statement."""

    requested_at: datetime
    """@brief 请求时刻 / Request instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    request_id: UUID
    """@brief 请求稳定标识 / Stable request identity."""

    def __post_init__(self) -> None:
        """@brief 验证请求命令 / Validate the request command.

        @return None / None.
        @raise ValueError 标识、时间或幂等键非法时抛出 /
            Raised when identifiers, time, or idempotency key are invalid.
        """

        if self.user_id <= 0:
            raise ValueError("Token requester must be positive")
        if not 1 <= len(self.purpose.strip()) <= 500:
            raise ValueError("Token request purpose must contain 1-500 characters")
        if self.requested_at.tzinfo is None or self.requested_at.utcoffset() is None:
            raise ValueError("Token request time must be timezone-aware")
        if not self.idempotency_key.strip() or len(self.idempotency_key) > 200:
            raise ValueError(
                "Token request idempotency key must contain 1-200 characters"
            )

    def aggregate(self) -> TokenRequest:
        """@brief 转换为待处理领域聚合 / Convert to a pending domain aggregate.

        @return 待审核代币请求 / Pending token request.
        """

        return TokenRequest(
            request_id=self.request_id,
            requester_id=self.user_id,
            requested_amount=self.amount,
            requested_bucket=TokenBucket.FREE,
            purpose=self.purpose,
            status=TokenRequestStatus.PENDING,
            requested_at=self.requested_at,
        )


@dataclass(frozen=True, slots=True)
class ReviewTokenRequest:
    """@brief 管理员审核代币请求 / Administrator review of a token request.

    @param request_id 请求标识 / Request identity.
    @param reviewer_id 审核管理员 / Reviewing administrator.
    @param decision 审核决定 / Review decision.
    @param reviewed_at 审核时刻 / Review instant.
    @param idempotency_key 幂等键 / Idempotency key.
    @param note 可选审核说明 / Optional review note.
    """

    request_id: UUID
    """@brief 请求标识 / Request identity."""

    reviewer_id: int
    """@brief 审核管理员 / Reviewing administrator."""

    decision: TokenReviewDecision
    """@brief 审核决定 / Review decision."""

    reviewed_at: datetime
    """@brief 审核时刻 / Review instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    note: str | None = None
    """@brief 可选审核说明 / Optional review note."""

    def __post_init__(self) -> None:
        """@brief 验证审核命令 / Validate the review command.

        @return None / None.
        @raise ValueError 标识、时间或幂等键非法时抛出 /
            Raised when identifiers, time, or idempotency key are invalid.
        """

        if self.reviewer_id <= 0:
            raise ValueError("Token reviewer must be positive")
        if self.reviewed_at.tzinfo is None or self.reviewed_at.utcoffset() is None:
            raise ValueError("Token review time must be timezone-aware")
        if not self.idempotency_key.strip() or len(self.idempotency_key) > 200:
            raise ValueError(
                "Token review idempotency key must contain 1-200 characters"
            )
        if self.note is not None and len(self.note.strip()) > 500:
            raise ValueError("Token review note cannot exceed 500 characters")


@dataclass(frozen=True, slots=True)
class IssueTokens:
    """@brief 银行管理员直接发行代币 / Direct token issuance by a bank administrator.

    @param administrator_id 银行管理员 / Bank administrator.
    @param recipient_id 收款用户 / Recipient user.
    @param amount 正数发行量 / Positive issuance amount.
    @param bucket 收款钱包类别 / Recipient wallet bucket.
    @param purpose 可审计用途 / Auditable purpose.
    @param issued_at 发行时刻 / Issuance instant.
    @param idempotency_key 幂等键 / Idempotency key.
    """

    administrator_id: int
    """@brief 银行管理员 / Bank administrator."""

    recipient_id: int
    """@brief 收款用户 / Recipient user."""

    amount: TokenAmount
    """@brief 正数发行量 / Positive issuance amount."""

    bucket: TokenBucket
    """@brief 收款钱包类别 / Recipient wallet bucket."""

    purpose: str
    """@brief 可审计用途 / Auditable purpose."""

    issued_at: datetime
    """@brief 发行时刻 / Issuance instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证发行命令 / Validate the issuance command.

        @return None / None.
        @raise ValueError 标识、用途、时间或幂等键非法时抛出 /
            Raised when identities, purpose, time, or idempotency key are invalid.
        """

        if self.administrator_id <= 0 or self.recipient_id <= 0:
            raise ValueError("Issuance identities must be positive")
        if self.bucket is not TokenBucket.FREE:
            raise ValueError(
                "Regular bank issuance is limited to the free token bucket"
            )
        if not 1 <= len(self.purpose.strip()) <= 500:
            raise ValueError("Issuance purpose must contain 1-500 characters")
        if self.issued_at.tzinfo is None or self.issued_at.utcoffset() is None:
            raise ValueError("Issuance time must be timezone-aware")
        if not self.idempotency_key.strip() or len(self.idempotency_key) > 200:
            raise ValueError("Issuance idempotency key must contain 1-200 characters")


@dataclass(frozen=True, slots=True)
class FundActivityPot:
    """@brief 银行管理员为概率活动奖池显式注资 / Explicit activity-pot funding by the bank administrator.

    @param administrator_id 银行管理员身份 / Bank-administrator identity.
    @param amount 从发行账户转入活动奖池的严格正数量 /
        Strictly positive amount moving from issuance to the activity pot.
    @param purpose 人工注资的可审计用途 / Auditable purpose for the manual funding.
    @param funded_at 注资发生时刻 / Funding occurrence instant.
    @param idempotency_key 来源操作的稳定幂等键 / Stable idempotency key of the source operation.
    """

    administrator_id: int
    """@brief 银行管理员 / Bank administrator."""

    amount: TokenAmount
    """@brief 严格正注资数量 / Strictly positive funding amount."""

    purpose: str
    """@brief 可审计用途 / Auditable purpose."""

    funded_at: datetime
    """@brief 注资时刻 / Funding instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证活动奖池注资命令 / Validate an activity-pot funding command.

        @return None / None.
        @raise ValueError 标识、用途、时间或幂等键非法时抛出 /
            Raised when identity, purpose, time, or idempotency key is invalid.
        """

        if self.administrator_id <= 0:
            raise ValueError("Activity-pot funding administrator must be positive")
        if not 1 <= len(self.purpose.strip()) <= 500:
            raise ValueError(
                "Activity-pot funding purpose must contain 1-500 characters"
            )
        if self.funded_at.tzinfo is None or self.funded_at.utcoffset() is None:
            raise ValueError("Activity-pot funding time must be timezone-aware")
        if not self.idempotency_key.strip() or len(self.idempotency_key) > 200:
            raise ValueError(
                "Activity-pot funding idempotency key must contain 1-200 characters"
            )


@dataclass(frozen=True, slots=True)
class ListPendingTokenRequests:
    """@brief 管理员读取待审批代币申请 / Administrator reads pending token requests.

    @param administrator_id 请求列表的管理员身份 / Administrator identity requesting the list.
    @param limit 最多返回的申请数 / Maximum number of requests to return.
    """

    administrator_id: int
    """@brief 银行管理员身份 / Bank-administrator identity."""

    limit: int = 20
    """@brief 有界返回数量 / Bounded result count."""

    def __post_init__(self) -> None:
        """@brief 验证管理员身份与分页上限 / Validate administrator identity and page bound.

        @return None / None.
        @raise ValueError 身份或 limit 非法时抛出 / Raised when identity or limit is invalid.
        """

        if isinstance(self.administrator_id, bool) or self.administrator_id <= 0:
            raise ValueError("Pending-request administrator must be positive")
        if isinstance(self.limit, bool) or not 1 <= self.limit <= 20:
            raise ValueError("Pending-request limit must be between 1 and 20")


@dataclass(frozen=True, slots=True)
class BankOverview:
    """@brief 用户银行钱包概览 / User bank-wallet overview.

    @param user_id 用户标识 / User identity.
    @param free 免费钱包余额 / Free-wallet balance.
    @param paid 付费钱包余额 / Paid-wallet balance.
    """

    user_id: int
    """@brief 用户标识 / User identity."""

    free: WalletBalance
    """@brief 免费钱包余额 / Free-wallet balance."""

    paid: WalletBalance
    """@brief 付费钱包余额 / Paid-wallet balance."""

    def __post_init__(self) -> None:
        """@brief 验证双钱包概览 / Validate dual-wallet overview.

        @return None / None.
        @raise ValueError 用户或钱包类别不匹配时抛出 /
            Raised when user or wallet buckets do not match.
        """

        if self.user_id <= 0:
            raise ValueError("Bank overview user must be positive")
        if self.free.bucket is not TokenBucket.FREE:
            raise ValueError("Bank overview free balance must use free bucket")
        if self.paid.bucket is not TokenBucket.PAID:
            raise ValueError("Bank overview paid balance must use paid bucket")

    @property
    def total(self) -> int:
        """@brief 返回两个钱包的总余额 / Return total across both wallets.

        @return 非负总余额 / Non-negative total balance.
        """

        return self.free.value + self.paid.value


@dataclass(frozen=True, slots=True)
class TokenRequestResult:
    """@brief 代币请求操作结果 / Token-request operation result.

    @param code 结果代码 / Result code.
    @param request 可选请求快照 / Optional request snapshot.
    @param overview 批准发行后的可选钱包概览 / Optional post-issuance wallet overview.
    @param replayed 是否来自幂等回放 / Whether result comes from idempotent replay.
    """

    code: BankCode
    """@brief 结果代码 / Result code."""

    request: TokenRequest | None = None
    """@brief 可选请求快照 / Optional request snapshot."""

    overview: BankOverview | None = None
    """@brief 可选钱包概览 / Optional wallet overview."""

    replayed: bool = False
    """@brief 幂等回放标记 / Idempotent replay marker."""


@dataclass(frozen=True, slots=True)
class PendingTokenRequestsResult:
    """@brief 待审批代币申请列表结果 / Pending token-request list result.

    @param code 稳定银行结果码 / Stable bank result code.
    @param requests 按申请时间排序的待审批申请 / Pending requests ordered by request time.
    """

    code: BankCode
    """@brief 稳定银行结果码 / Stable bank result code."""

    requests: tuple[TokenRequest, ...] = ()
    """@brief 待审批申请快照 / Pending request snapshots."""

    def __post_init__(self) -> None:
        """@brief 验证失败结果不会泄漏申请 / Validate failures do not expose requests.

        @return None / None.
        @raise TypeError 或 ValueError 结果形状不合法时抛出 /
            Raised when the result shape is invalid.
        """

        if not isinstance(self.code, BankCode):
            raise TypeError("Pending-token-requests result code must be BankCode")
        if self.code is not BankCode.SUCCESS and self.requests:
            raise ValueError("Failed pending-request result cannot carry requests")
        if any(
            request.status is not TokenRequestStatus.PENDING
            for request in self.requests
        ):
            raise ValueError("Pending-request result can contain only pending requests")


@dataclass(frozen=True, slots=True)
class ActivityPotFundingResult:
    """@brief 活动奖池注资结果 / Result of an activity-pot funding operation.

    @param code 稳定银行结果码 / Stable bank result code.
    @param amount 成功时的本次注资数量 / Funding amount when successful.
    @param activity_pot_balance 成功后的活动奖池余额 / Activity-pot balance after success.
    @param ledger_entry_id 成功时不可变账本分录标识 / Immutable ledger-entry ID on success.
    @param replayed 是否由同义幂等重放返回 / Whether returned from a semantic idempotent replay.
    """

    code: BankCode
    """@brief 稳定银行结果码 / Stable bank result code."""

    amount: TokenAmount | None = None
    """@brief 可选本次注资量 / Optional funding amount."""

    activity_pot_balance: int | None = None
    """@brief 可选注资后奖池余额 / Optional post-funding pot balance."""

    ledger_entry_id: UUID | None = None
    """@brief 可选账本分录标识 / Optional ledger-entry identifier."""

    replayed: bool = False
    """@brief 幂等回放标记 / Idempotent replay marker."""

    def __post_init__(self) -> None:
        """@brief 验证成功结果包含完整可审计事实 / Validate successful result completeness.

        @return None / None.
        @raise TypeError 或 ValueError 成功/失败结果形状不一致时抛出 /
            Raised when the success/failure result shape is inconsistent.
        """

        if not isinstance(self.code, BankCode):
            raise TypeError("Activity-pot funding result code must be BankCode")
        if self.code is BankCode.SUCCESS:
            if (
                self.amount is None
                or self.activity_pot_balance is None
                or self.ledger_entry_id is None
            ):
                raise ValueError(
                    "Successful activity-pot funding requires amount, balance, and ledger entry"
                )
            if self.activity_pot_balance < self.amount.value:
                raise ValueError(
                    "Activity-pot balance cannot be below the just-funded amount"
                )
        elif (
            self.amount is not None
            or self.activity_pot_balance is not None
            or self.ledger_entry_id is not None
        ):
            raise ValueError("Failed activity-pot funding cannot carry funding facts")
