"""@brief 通用检索领域公共接口 / Public generic-retrieval domain API."""

from fogmoe_bot.domain.retrieval.models import (
    EmbeddingSpace,
    EmbeddingVector,
    RetrievalEvidence,
    RetrievalPassage,
    RetrievalScope,
    RetrievalScopeKind,
    passage_digest,
    passage_identity,
)
from fogmoe_bot.domain.retrieval.vector_job import (
    RECOVERED_PASSAGE_VECTOR_LEASE_ERROR,
    AwaitingPassageVector,
    CompletedPassageVector,
    FailedPassageVector,
    InvalidPassageVectorTransition,
    PassageVectorClaim,
    PassageVectorClaimed,
    PassageVectorCompleted,
    PassageVectorFailed,
    PassageVectorFailure,
    PassageVectorJob,
    PassageVectorJobKey,
    PassageVectorLeaseRecovered,
    PassageVectorRetryScheduled,
    PassageVectorState,
    PassageVectorStatus,
    ProcessingPassageVector,
    WaitingPassageVectorRetry,
)

__all__ = [
    "EmbeddingSpace",
    "EmbeddingVector",
    "AwaitingPassageVector",
    "CompletedPassageVector",
    "FailedPassageVector",
    "InvalidPassageVectorTransition",
    "PassageVectorClaim",
    "PassageVectorClaimed",
    "PassageVectorCompleted",
    "PassageVectorFailed",
    "PassageVectorFailure",
    "PassageVectorJob",
    "PassageVectorJobKey",
    "PassageVectorLeaseRecovered",
    "PassageVectorRetryScheduled",
    "PassageVectorState",
    "PassageVectorStatus",
    "ProcessingPassageVector",
    "RECOVERED_PASSAGE_VECTOR_LEASE_ERROR",
    "RetrievalEvidence",
    "RetrievalPassage",
    "RetrievalScope",
    "RetrievalScopeKind",
    "WaitingPassageVectorRetry",
    "passage_digest",
    "passage_identity",
]
