-- migrate:up

CREATE TABLE IF NOT EXISTS assistant.ai_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  run_at TIMESTAMP NOT NULL,
  trigger_reason VARCHAR(200) NOT NULL,
  context TEXT NULL,
  prompt TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','executing','executed','cancelled','failed')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  executed_at TIMESTAMP NULL DEFAULT NULL,
  error TEXT NULL
);

CREATE INDEX idx_ai_schedules_user_status
  ON assistant.ai_schedules (user_id, status);
CREATE INDEX idx_ai_schedules_run
  ON assistant.ai_schedules (status, run_at);

-- migrate:down

DROP TABLE IF EXISTS assistant.ai_schedules;
