-- migrate:up

ALTER TABLE moderation.group_spam_control
  ADD COLUMN exempt_administrators BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN rule_merge_mode TEXT NOT NULL DEFAULT 'override_global'
    CHECK (rule_merge_mode IN ('global_only', 'extend_global', 'override_global')),
  ADD COLUMN failure_mode TEXT NOT NULL DEFAULT 'fail_closed'
    CHECK (failure_mode IN ('fail_open', 'fail_closed')),
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0);

CREATE TABLE moderation.member_warning_windows (
  chat_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  window_started_at TIMESTAMPTZ NOT NULL,
  warning_count INTEGER NOT NULL CHECK (warning_count > 0),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE moderation.effects (
  effect_id UUID PRIMARY KEY,
  source_update_id BIGINT NOT NULL CHECK (source_update_id >= 0),
  kind TEXT NOT NULL
    CHECK (kind IN ('spam_enforcement', 'keyword_reply')),
  chat_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL CHECK (message_id >= 0),
  status TEXT NOT NULL
    CHECK (status IN ('pending', 'message_deleted', 'delivered', 'failed')),
  warning_count INTEGER NULL CHECK (warning_count IS NULL OR warning_count > 0),
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT moderation_effect_source_unique UNIQUE (source_update_id, kind),
  CONSTRAINT moderation_effect_warning_shape CHECK (
    (kind = 'spam_enforcement' AND (
      warning_count IS NOT NULL OR status = 'pending'
    ))
    OR (kind = 'keyword_reply' AND warning_count IS NULL)
  )
);

CREATE INDEX moderation_effect_group_updated_idx
  ON moderation.effects (chat_id, updated_at);

CREATE TABLE moderation.reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL CHECK (message_id >= 0),
  reporter_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT moderation_report_idempotency
    UNIQUE (chat_id, message_id, reporter_id)
);

CREATE INDEX moderation_reports_message_idx
  ON moderation.reports (chat_id, message_id, created_at);

-- migrate:down

DROP TABLE IF EXISTS moderation.reports;
DROP TABLE IF EXISTS moderation.effects;
DROP TABLE IF EXISTS moderation.member_warning_windows;

ALTER TABLE moderation.group_spam_control
  DROP COLUMN IF EXISTS version,
  DROP COLUMN IF EXISTS failure_mode,
  DROP COLUMN IF EXISTS rule_merge_mode,
  DROP COLUMN IF EXISTS exempt_administrators;
