-- migrate:up

ALTER TABLE economy.user_stakes
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0);

CREATE TABLE economy.stake_pool_postings (
  posting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pool_id SMALLINT NOT NULL,
  idempotency_key VARCHAR(200) NOT NULL UNIQUE
    CHECK (char_length(btrim(idempotency_key)) > 0),
  delta NUMERIC(20, 2) NOT NULL CHECK (delta <> 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX stake_pool_postings_pool_created_idx
  ON economy.stake_pool_postings (pool_id, created_at, posting_id);

-- Preserve every pre-ledger balance as one immutable opening entry.  The
-- stake_reward_pool row remains only as the low-frequency withdrawal gate;
-- ordinary assistant credits never update or lock it after this migration.
INSERT INTO economy.stake_pool_postings (pool_id, idempotency_key, delta)
SELECT id, 'migration:0022:opening:' || id::TEXT, balance
FROM economy.stake_reward_pool
WHERE balance <> 0;

CREATE TABLE economy.operation_receipts (
  idempotency_key VARCHAR(200) PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) > 0),
  operation_kind VARCHAR(80) NOT NULL
    CHECK (char_length(btrim(operation_kind)) > 0),
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  result JSONB NOT NULL CHECK (jsonb_typeof(result) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX operation_receipts_user_created_idx
  ON economy.operation_receipts (user_id, created_at);

CREATE TABLE economy.shop_pity (
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  game TEXT NOT NULL CHECK (game IN ('scratch', 'huanle')),
  business_date DATE NOT NULL,
  misses INTEGER NOT NULL DEFAULT 0 CHECK (misses >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, game)
);

-- migrate:down

UPDATE economy.stake_reward_pool AS pool
SET balance = COALESCE((
  SELECT SUM(posting.delta)
  FROM economy.stake_pool_postings AS posting
  WHERE posting.pool_id = pool.id
), 0),
updated_at = CURRENT_TIMESTAMP;

DROP TABLE IF EXISTS economy.shop_pity;
DROP TABLE IF EXISTS economy.operation_receipts;
DROP TABLE IF EXISTS economy.stake_pool_postings;

ALTER TABLE economy.user_stakes
  DROP COLUMN IF EXISTS version;
