-- migrate:up

CREATE SCHEMA IF NOT EXISTS observability;

ALTER TABLE conversation.inbound_updates
  ADD COLUMN traceparent VARCHAR(55),
  ADD CONSTRAINT inbound_updates_traceparent_ck CHECK (
    traceparent IS NULL OR traceparent ~ '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'
  );

ALTER TABLE conversation.inference_activities
  ADD COLUMN traceparent VARCHAR(55),
  ADD CONSTRAINT inference_activities_traceparent_ck CHECK (
    traceparent IS NULL OR traceparent ~ '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'
  );

ALTER TABLE conversation.outbound_messages
  ADD COLUMN traceparent VARCHAR(55),
  ADD CONSTRAINT outbound_messages_traceparent_ck CHECK (
    traceparent IS NULL OR traceparent ~ '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'
  );

UPDATE conversation.inbound_updates
SET traceparent = '00-' || md5('fogmoe-inbound:' || update_id::TEXT)
  || '-' || substr(md5('fogmoe-inbound-span:' || update_id::TEXT), 1, 16) || '-01'
WHERE traceparent IS NULL;

UPDATE conversation.inference_activities
SET traceparent = '00-' || md5('fogmoe-turn:' || turn_id::TEXT)
  || '-' || substr(md5('fogmoe-inference-span:' || activity_id::TEXT), 1, 16) || '-01'
WHERE traceparent IS NULL;

UPDATE conversation.outbound_messages
SET traceparent = '00-' || md5('fogmoe-outbound-trace:' || coalesce(turn_id::TEXT, message_id::TEXT))
  || '-' || substr(md5('fogmoe-outbound-span:' || message_id::TEXT), 1, 16) || '-01'
WHERE traceparent IS NULL;

ALTER TABLE conversation.inbound_updates ALTER COLUMN traceparent SET NOT NULL;
ALTER TABLE conversation.inference_activities ALTER COLUMN traceparent SET NOT NULL;
ALTER TABLE conversation.outbound_messages ALTER COLUMN traceparent SET NOT NULL;

CREATE TABLE observability.resources (
  resource_id UUID PRIMARY KEY,
  service_name VARCHAR(255) NOT NULL CHECK (char_length(btrim(service_name)) > 0),
  service_version VARCHAR(100) NOT NULL CHECK (char_length(btrim(service_version)) > 0),
  deployment_environment VARCHAR(100) NOT NULL
    CHECK (char_length(btrim(deployment_environment)) > 0),
  service_instance_id VARCHAR(255) NOT NULL
    CHECK (char_length(btrim(service_instance_id)) > 0),
  started_at TIMESTAMPTZ NOT NULL,
  stopped_at TIMESTAMPTZ,
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  CONSTRAINT observability_resources_time_ck CHECK (
    stopped_at IS NULL OR stopped_at >= started_at
  )
);

CREATE INDEX observability_resources_service_started_idx
  ON observability.resources (service_name, started_at DESC);

CREATE TABLE observability.log_records (
  occurred_at TIMESTAMPTZ NOT NULL,
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  observed_at TIMESTAMPTZ NOT NULL,
  resource_id UUID NOT NULL REFERENCES observability.resources(resource_id),
  trace_id BYTEA,
  span_id BYTEA,
  severity_number SMALLINT NOT NULL CHECK (severity_number BETWEEN 1 AND 24),
  severity_text VARCHAR(16) NOT NULL,
  logger_name VARCHAR(255) NOT NULL,
  event_name VARCHAR(255),
  body VARCHAR(16384) NOT NULL,
  exception_type VARCHAR(255),
  exception_message VARCHAR(4096),
  exception_stack VARCHAR(16384),
  turn_id UUID,
  update_id BIGINT,
  activity_id UUID,
  outbound_message_id UUID,
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  PRIMARY KEY (occurred_at, log_id),
  CONSTRAINT observability_log_trace_id_ck CHECK (
    trace_id IS NULL OR octet_length(trace_id) = 16
  ),
  CONSTRAINT observability_log_span_id_ck CHECK (
    span_id IS NULL OR octet_length(span_id) = 8
  ),
  CONSTRAINT observability_log_context_ck CHECK (
    span_id IS NULL OR trace_id IS NOT NULL
  )
) PARTITION BY RANGE (occurred_at);

CREATE INDEX observability_log_trace_idx
  ON observability.log_records (trace_id, occurred_at DESC)
  WHERE trace_id IS NOT NULL;
CREATE INDEX observability_log_event_idx
  ON observability.log_records (event_name, occurred_at DESC)
  WHERE event_name IS NOT NULL;
CREATE INDEX observability_log_error_idx
  ON observability.log_records (occurred_at DESC, severity_number)
  WHERE severity_number >= 13;
CREATE INDEX observability_log_turn_idx
  ON observability.log_records (turn_id, occurred_at DESC)
  WHERE turn_id IS NOT NULL;

CREATE TABLE observability.spans (
  started_at TIMESTAMPTZ NOT NULL,
  trace_id BYTEA NOT NULL CHECK (octet_length(trace_id) = 16),
  span_id BYTEA NOT NULL CHECK (octet_length(span_id) = 8),
  parent_span_id BYTEA CHECK (
    parent_span_id IS NULL OR octet_length(parent_span_id) = 8
  ),
  resource_id UUID NOT NULL REFERENCES observability.resources(resource_id),
  span_name VARCHAR(255) NOT NULL,
  span_kind VARCHAR(16) NOT NULL CHECK (
    span_kind IN ('internal', 'server', 'client', 'producer', 'consumer')
  ),
  ended_at TIMESTAMPTZ NOT NULL,
  duration_ns BIGINT NOT NULL CHECK (duration_ns >= 0),
  status_code VARCHAR(16) NOT NULL CHECK (
    status_code IN ('unset', 'ok', 'error')
  ),
  status_message VARCHAR(2000),
  turn_id UUID,
  update_id BIGINT,
  activity_id UUID,
  outbound_message_id UUID,
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  PRIMARY KEY (started_at, trace_id, span_id),
  CONSTRAINT observability_spans_time_ck CHECK (ended_at >= started_at)
) PARTITION BY RANGE (started_at);

CREATE INDEX observability_spans_trace_idx
  ON observability.spans (trace_id, started_at);
CREATE INDEX observability_spans_name_started_idx
  ON observability.spans (span_name, started_at DESC);
CREATE INDEX observability_spans_error_idx
  ON observability.spans (started_at DESC, span_name)
  WHERE status_code = 'error';
CREATE INDEX observability_spans_turn_idx
  ON observability.spans (turn_id, started_at)
  WHERE turn_id IS NOT NULL;

CREATE TABLE observability.metric_points (
  observed_at TIMESTAMPTZ NOT NULL,
  metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  resource_id UUID NOT NULL REFERENCES observability.resources(resource_id),
  metric_name VARCHAR(255) NOT NULL,
  metric_kind VARCHAR(16) NOT NULL CHECK (metric_kind IN ('counter', 'gauge')),
  value DOUBLE PRECISION NOT NULL CHECK (
    value NOT IN (
      'NaN'::DOUBLE PRECISION,
      'Infinity'::DOUBLE PRECISION,
      '-Infinity'::DOUBLE PRECISION
    )
  ),
  unit VARCHAR(63) NOT NULL,
  exemplar_trace_id BYTEA CHECK (
    exemplar_trace_id IS NULL OR octet_length(exemplar_trace_id) = 16
  ),
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  PRIMARY KEY (observed_at, metric_id),
  CONSTRAINT observability_metric_counter_ck CHECK (
    metric_kind <> 'counter' OR value >= 0
  )
) PARTITION BY RANGE (observed_at);

CREATE INDEX observability_metric_name_time_idx
  ON observability.metric_points (metric_name, observed_at DESC);
CREATE INDEX observability_metric_exemplar_idx
  ON observability.metric_points (exemplar_trace_id, observed_at DESC)
  WHERE exemplar_trace_id IS NOT NULL;

CREATE FUNCTION observability.ensure_daily_partitions(partition_day DATE)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  lower_bound TIMESTAMPTZ := partition_day::TIMESTAMP AT TIME ZONE 'UTC';
  upper_bound TIMESTAMPTZ := (partition_day + 1)::TIMESTAMP AT TIME ZONE 'UTC';
  suffix TEXT := to_char(partition_day, 'YYYYMMDD');
BEGIN
  IF partition_day < DATE '2020-01-01'
     OR partition_day > (CURRENT_DATE + 366) THEN
    RAISE EXCEPTION 'observability partition day out of allowed range: %', partition_day;
  END IF;

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS observability.%I PARTITION OF observability.log_records FOR VALUES FROM (%L) TO (%L)',
    'log_records_' || suffix, lower_bound, upper_bound
  );
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS observability.%I PARTITION OF observability.spans FOR VALUES FROM (%L) TO (%L)',
    'spans_' || suffix, lower_bound, upper_bound
  );
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS observability.%I PARTITION OF observability.metric_points FOR VALUES FROM (%L) TO (%L)',
    'metric_points_' || suffix, lower_bound, upper_bound
  );
END;
$$;

CREATE FUNCTION observability.drop_partitions_before(retain_from DATE)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  child RECORD;
  dropped INTEGER := 0;
  partition_day DATE;
BEGIN
  IF retain_from < DATE '2020-01-01' OR retain_from > CURRENT_DATE THEN
    RAISE EXCEPTION 'observability retention boundary out of allowed range: %', retain_from;
  END IF;

  FOR child IN
    SELECT child_namespace.nspname AS schema_name,
           child_class.relname AS table_name
    FROM pg_inherits
    JOIN pg_class AS parent_class ON parent_class.oid = inhparent
    JOIN pg_namespace AS parent_namespace
      ON parent_namespace.oid = parent_class.relnamespace
    JOIN pg_class AS child_class ON child_class.oid = inhrelid
    JOIN pg_namespace AS child_namespace
      ON child_namespace.oid = child_class.relnamespace
    WHERE parent_namespace.nspname = 'observability'
      AND parent_class.relname IN ('log_records', 'spans', 'metric_points')
  LOOP
    IF child.table_name ~ '^[a-z_]+_[0-9]{8}$' THEN
      partition_day := to_date(right(child.table_name, 8), 'YYYYMMDD');
      IF partition_day < retain_from THEN
        EXECUTE format('DROP TABLE %I.%I', child.schema_name, child.table_name);
        dropped := dropped + 1;
      END IF;
    END IF;
  END LOOP;
  RETURN dropped;
END;
$$;

CREATE VIEW observability.pipeline_health AS
SELECT 'inbox'::TEXT AS stage,
       count(*) FILTER (WHERE status = 'pending') AS pending_count,
       count(*) FILTER (WHERE status = 'processing') AS processing_count,
       count(*) FILTER (WHERE status = 'retry_wait') AS retry_count,
       count(*) FILTER (WHERE status = 'failed_final') AS failed_final_count,
       min(next_attempt_at) FILTER (
         WHERE status IN ('pending', 'retry_wait')
       ) AS oldest_ready_at,
       count(*) FILTER (
         WHERE status = 'processing' AND lease_expires_at < CURRENT_TIMESTAMP
       ) AS expired_lease_count
FROM conversation.inbound_updates
UNION ALL
SELECT 'inference',
       count(*) FILTER (WHERE status = 'pending'),
       count(*) FILTER (WHERE status = 'processing'),
       count(*) FILTER (WHERE status = 'retry'),
       count(*) FILTER (WHERE status = 'failed'),
       min(next_attempt_at) FILTER (WHERE status IN ('pending', 'retry')),
       count(*) FILTER (
         WHERE status = 'processing' AND lease_expires_at < CURRENT_TIMESTAMP
       )
FROM conversation.inference_activities
UNION ALL
SELECT 'outbox',
       count(*) FILTER (WHERE status = 'pending'),
       count(*) FILTER (WHERE status = 'processing'),
       count(*) FILTER (WHERE status = 'retry_wait'),
       count(*) FILTER (WHERE status = 'failed_final'),
       min(next_attempt_at) FILTER (
         WHERE status IN ('pending', 'retry_wait')
       ),
       count(*) FILTER (
         WHERE status = 'processing' AND lease_expires_at < CURRENT_TIMESTAMP
       )
FROM conversation.outbound_messages;

CREATE VIEW observability.turn_latency AS
SELECT turn.turn_id,
       turn.source_update_id AS update_id,
       turn.state,
       inbound.received_at,
       turn.created_at AS turn_created_at,
       activity.created_at AS inference_created_at,
       activity.completed_at AS inference_completed_at,
       delivery.first_created_at AS delivery_created_at,
       delivery.last_delivered_at AS delivered_at,
       EXTRACT(EPOCH FROM (turn.created_at - inbound.received_at)) * 1000
         AS ingress_to_turn_ms,
       EXTRACT(EPOCH FROM (activity.completed_at - activity.created_at)) * 1000
         AS inference_total_ms,
       EXTRACT(EPOCH FROM (delivery.last_delivered_at - delivery.first_created_at)) * 1000
         AS delivery_total_ms,
       EXTRACT(EPOCH FROM (turn.completed_at - inbound.received_at)) * 1000
         AS end_to_end_ms,
       turn.inference_attempts,
       turn.delivery_attempts
FROM conversation.conversation_turns AS turn
LEFT JOIN conversation.inbound_updates AS inbound
  ON inbound.update_id = turn.source_update_id
LEFT JOIN conversation.inference_activities AS activity
  ON activity.turn_id = turn.turn_id
LEFT JOIN LATERAL (
  SELECT min(outbound.created_at) AS first_created_at,
         max(outbound.delivered_at) AS last_delivered_at
  FROM conversation.outbound_messages AS outbound
  WHERE outbound.turn_id = turn.turn_id
) AS delivery ON TRUE;

-- migrate:down

DROP SCHEMA IF EXISTS observability CASCADE;

ALTER TABLE conversation.outbound_messages
  DROP CONSTRAINT IF EXISTS outbound_messages_traceparent_ck,
  DROP COLUMN IF EXISTS traceparent;

ALTER TABLE conversation.inference_activities
  DROP CONSTRAINT IF EXISTS inference_activities_traceparent_ck,
  DROP COLUMN IF EXISTS traceparent;

ALTER TABLE conversation.inbound_updates
  DROP CONSTRAINT IF EXISTS inbound_updates_traceparent_ck,
  DROP COLUMN IF EXISTS traceparent;
