-- migrate:up

DELETE FROM economy.operation_receipts
WHERE operation_kind IN ('redeem_code', 'approve_topup');

DELETE FROM crypto.operation_receipts
WHERE operation_kind = 'swap.submit';

DROP TABLE crypto.swap_request_conflicts;
DROP TABLE crypto.token_swap_requests;
DROP TABLE economy.redemption_codes;

ALTER TABLE identity.users
  DROP COLUMN recharge_blocked_until;

-- migrate:down

ALTER TABLE identity.users
  ADD COLUMN recharge_blocked_until TIMESTAMP NULL;

CREATE TABLE economy.redemption_codes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL UNIQUE,
  amount INT NOT NULL,
  is_used BOOLEAN NOT NULL DEFAULT FALSE,
  used_by BIGINT DEFAULT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (used_by) REFERENCES identity.users(id) ON DELETE SET NULL
);

CREATE TABLE crypto.token_swap_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username VARCHAR(255) NOT NULL,
  wallet_address VARCHAR(50) NOT NULL,
  amount INT NOT NULL,
  request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'pending',
  idempotency_key TEXT NOT NULL,
  CONSTRAINT token_swap_request_idempotency_key_ck
    CHECK (char_length(btrim(idempotency_key)) BETWEEN 1 AND 512),
  CONSTRAINT token_swap_request_idempotency_key_uk UNIQUE (idempotency_key)
);

CREATE UNIQUE INDEX uq_token_swap_requests_one_pending_per_user
  ON crypto.token_swap_requests (user_id)
  WHERE status = 'pending';

CREATE TABLE crypto.swap_request_conflicts (
  request_id INTEGER PRIMARY KEY
    REFERENCES crypto.token_swap_requests(id) ON DELETE RESTRICT,
  canonical_request_id INTEGER NOT NULL
    REFERENCES crypto.token_swap_requests(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (request_id <> canonical_request_id)
);
