-- migrate:up

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- @brief 在迁移快照期间排除旧调度 writer / Exclude legacy schedule writers for the migration snapshot.
LOCK TABLE assistant.ai_schedules IN ACCESS EXCLUSIVE MODE;

-- @brief 对不能无损映射的数据 fail closed / Fail closed for rows that cannot be mapped losslessly.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM assistant.ai_schedules AS legacy
    LEFT JOIN identity.users AS creator ON creator.id = legacy.user_id
    WHERE creator.id IS NULL OR legacy.user_id <= 0
  ) THEN
    RAISE EXCEPTION
      'cannot rebuild Assistant scheduling: orphaned or invalid creator identity exists'
      USING ERRCODE = '23503';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM assistant.ai_schedules AS legacy
    WHERE legacy.recurrence_unit NOT IN ('none', 'minute', 'hour', 'day')
       OR (
         legacy.recurrence_unit <> 'none'
         AND legacy.recurrence_interval <= 0
       )
  ) THEN
    RAISE EXCEPTION
      'cannot rebuild Assistant scheduling: invalid fixed recurrence exists'
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM assistant.ai_schedules AS legacy
    WHERE char_length(btrim(legacy.trigger_reason)) NOT BETWEEN 1 AND 200
       OR char_length(btrim(legacy.prompt)) NOT BETWEEN 1 AND 20000
       OR (
         legacy.context IS NOT NULL
         AND char_length(btrim(legacy.context)) > 20000
       )
  ) THEN
    RAISE EXCEPTION
      'cannot rebuild Assistant scheduling: invalid intent text exists'
      USING ERRCODE = '23514';
  END IF;
END;
$$;

CREATE SCHEMA IF NOT EXISTS scheduling;

-- @brief 单表保存调度聚合定义、游标与可靠队列状态 / Store schedule definition, cursor, and reliable-queue state in one aggregate table.
CREATE TABLE scheduling.assistant_schedules (
  schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  target_kind TEXT NOT NULL
    CHECK (target_kind IN ('private', 'group')),
  target_chat_id BIGINT NOT NULL CHECK (target_chat_id <> 0),
  target_thread_id BIGINT NULL
    CHECK (target_thread_id IS NULL OR target_thread_id > 0),
  target_conversation_id VARCHAR(512) NOT NULL
    CHECK (char_length(btrim(target_conversation_id)) BETWEEN 1 AND 512),
  target_delivery_stream_id VARCHAR(512) NOT NULL
    CHECK (char_length(btrim(target_delivery_stream_id)) BETWEEN 1 AND 512),
  trigger_reason VARCHAR(200) NOT NULL
    CHECK (char_length(btrim(trigger_reason)) BETWEEN 1 AND 200),
  context_snapshot TEXT NULL
    CHECK (
      context_snapshot IS NULL
      OR char_length(btrim(context_snapshot)) BETWEEN 1 AND 20000
    ),
  instruction TEXT NOT NULL
    CHECK (char_length(btrim(instruction)) BETWEEN 1 AND 20000),
  cadence_kind TEXT NOT NULL
    CHECK (
      cadence_kind IN (
        'one_shot',
        'fixed_interval',
        'calendar_daily',
        'calendar_weekly'
      )
    ),
  fixed_interval_seconds BIGINT NULL
    CHECK (fixed_interval_seconds IS NULL OR fixed_interval_seconds > 0),
  calendar_interval SMALLINT NULL
    CHECK (calendar_interval IS NULL OR calendar_interval > 0),
  calendar_anchor_date DATE NULL,
  calendar_local_time TIME WITHOUT TIME ZONE NULL,
  calendar_weekday_mask SMALLINT NULL
    CHECK (
      calendar_weekday_mask IS NULL
      OR calendar_weekday_mask BETWEEN 1 AND 127
    ),
  time_zone VARCHAR(64) NOT NULL
    CHECK (char_length(btrim(time_zone)) BETWEEN 1 AND 64),
  next_run_at TIMESTAMPTZ NOT NULL,
  misfire_policy TEXT NOT NULL DEFAULT 'fire_once'
    CHECK (misfire_policy IN ('fire_once', 'skip')),
  misfire_grace_seconds BIGINT NULL
    CHECK (
      misfire_grace_seconds IS NULL
      OR misfire_grace_seconds > 0
    ),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (
      status IN (
        'pending',
        'processing',
        'retry_wait',
        'completed',
        'cancelled',
        'expired',
        'failed_final'
      )
    ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ NULL,
  claim_token UUID NULL,
  lease_expires_at TIMESTAMPTZ NULL,
  last_accepted_for TIMESTAMPTZ NULL,
  last_accepted_at TIMESTAMPTZ NULL,
  misfire_count BIGINT NOT NULL DEFAULT 0 CHECK (misfire_count >= 0),
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  terminal_at TIMESTAMPTZ NULL,
  CONSTRAINT scheduling_assistant_schedules_target_shape_ck CHECK (
    (
      target_kind = 'private'
      AND target_chat_id > 0
      AND target_thread_id IS NULL
    )
    OR (
      target_kind = 'group'
      AND target_chat_id < 0
    )
  ),
  CONSTRAINT scheduling_assistant_schedules_cadence_shape_ck CHECK (
    (
      cadence_kind = 'one_shot'
      AND fixed_interval_seconds IS NULL
      AND calendar_interval IS NULL
      AND calendar_anchor_date IS NULL
      AND calendar_local_time IS NULL
      AND calendar_weekday_mask IS NULL
    )
    OR (
      cadence_kind = 'fixed_interval'
      AND fixed_interval_seconds IS NOT NULL
      AND calendar_interval IS NULL
      AND calendar_anchor_date IS NULL
      AND calendar_local_time IS NULL
      AND calendar_weekday_mask IS NULL
    )
    OR (
      cadence_kind = 'calendar_daily'
      AND fixed_interval_seconds IS NULL
      AND calendar_interval IS NOT NULL
      AND calendar_anchor_date IS NOT NULL
      AND calendar_local_time IS NOT NULL
      AND calendar_weekday_mask IS NULL
    )
    OR (
      cadence_kind = 'calendar_weekly'
      AND fixed_interval_seconds IS NULL
      AND calendar_interval IS NOT NULL
      AND calendar_anchor_date IS NOT NULL
      AND calendar_local_time IS NOT NULL
      AND calendar_weekday_mask IS NOT NULL
    )
  ),
  CONSTRAINT scheduling_assistant_schedules_ready_ck CHECK (
    (status IN ('pending', 'retry_wait')) = (next_attempt_at IS NOT NULL)
  ),
  CONSTRAINT scheduling_assistant_schedules_lease_ck CHECK (
    (status = 'processing') = (
      claim_token IS NOT NULL AND lease_expires_at IS NOT NULL
    )
  ),
  CONSTRAINT scheduling_assistant_schedules_terminal_ck CHECK (
    (status IN ('completed', 'cancelled', 'expired', 'failed_final')) =
      (terminal_at IS NOT NULL)
  ),
  CONSTRAINT scheduling_assistant_schedules_acceptance_ck CHECK (
    (last_accepted_for IS NULL) = (last_accepted_at IS NULL)
  ),
  CONSTRAINT scheduling_assistant_schedules_time_ck CHECK (
    updated_at >= created_at
    AND (terminal_at IS NULL OR terminal_at >= created_at)
    AND (last_accepted_at IS NULL OR last_accepted_at >= created_at)
  )
);

-- @brief 迁移旧 private prompt schedule 并保留 ID / Migrate legacy private prompt schedules while preserving IDs.
INSERT INTO scheduling.assistant_schedules (
  schedule_id,
  creator_user_id,
  target_kind,
  target_chat_id,
  target_thread_id,
  target_conversation_id,
  target_delivery_stream_id,
  trigger_reason,
  context_snapshot,
  instruction,
  cadence_kind,
  fixed_interval_seconds,
  calendar_interval,
  calendar_anchor_date,
  calendar_local_time,
  calendar_weekday_mask,
  time_zone,
  next_run_at,
  misfire_policy,
  misfire_grace_seconds,
  status,
  version,
  attempt_count,
  next_attempt_at,
  claim_token,
  lease_expires_at,
  last_accepted_for,
  last_accepted_at,
  misfire_count,
  last_error,
  created_at,
  updated_at,
  terminal_at
)
SELECT
  legacy.id,
  legacy.user_id,
  'private',
  legacy.user_id,
  NULL,
  'assistant-user:' || legacy.user_id::text,
  'telegram:primary:chat:' || legacy.user_id::text || ':thread:0',
  legacy.trigger_reason,
  CASE
    WHEN legacy.context IS NULL OR btrim(legacy.context) = '' THEN NULL
    ELSE legacy.context
  END,
  legacy.prompt,
  CASE
    WHEN legacy.recurrence_unit = 'none' THEN 'one_shot'
    ELSE 'fixed_interval'
  END,
  CASE legacy.recurrence_unit
    WHEN 'minute' THEN legacy.recurrence_interval::bigint * 60
    WHEN 'hour' THEN legacy.recurrence_interval::bigint * 3600
    WHEN 'day' THEN legacy.recurrence_interval::bigint * 86400
    ELSE NULL
  END,
  NULL,
  NULL,
  NULL,
  NULL,
  'UTC',
  legacy.run_at AT TIME ZONE 'UTC',
  'fire_once',
  NULL,
  CASE legacy.status
    WHEN 'pending' THEN 'pending'
    WHEN 'executing' THEN 'retry_wait'
    WHEN 'executed' THEN 'completed'
    WHEN 'cancelled' THEN 'cancelled'
    WHEN 'failed' THEN 'failed_final'
  END,
  0,
  CASE WHEN legacy.status = 'executing' THEN 1 ELSE 0 END,
  CASE legacy.status
    WHEN 'pending' THEN legacy.run_at AT TIME ZONE 'UTC'
    WHEN 'executing' THEN CURRENT_TIMESTAMP
    ELSE NULL
  END,
  NULL,
  NULL,
  CASE
    WHEN legacy.executed_at IS NOT NULL OR legacy.last_run_at IS NOT NULL
      THEN COALESCE(legacy.last_run_at, legacy.run_at) AT TIME ZONE 'UTC'
    ELSE NULL
  END,
  CASE
    WHEN legacy.executed_at IS NOT NULL OR legacy.last_run_at IS NOT NULL
      THEN COALESCE(
        legacy.executed_at,
        legacy.updated_at,
        legacy.created_at
      ) AT TIME ZONE 'UTC'
    ELSE NULL
  END,
  0,
  legacy.error,
  legacy.created_at AT TIME ZONE 'UTC',
  COALESCE(legacy.updated_at, legacy.created_at) AT TIME ZONE 'UTC',
  CASE legacy.status
    WHEN 'executed' THEN COALESCE(
      legacy.executed_at,
      legacy.updated_at,
      legacy.created_at
    ) AT TIME ZONE 'UTC'
    WHEN 'cancelled' THEN COALESCE(
      legacy.updated_at,
      legacy.created_at
    ) AT TIME ZONE 'UTC'
    WHEN 'failed' THEN COALESCE(
      legacy.updated_at,
      legacy.created_at
    ) AT TIME ZONE 'UTC'
    ELSE NULL
  END
FROM assistant.ai_schedules AS legacy
ORDER BY legacy.id;

-- @brief 验证逐 ID 完整迁移 / Verify complete one-for-one ID migration.
DO $$
BEGIN
  IF (
    SELECT count(*) FROM assistant.ai_schedules
  ) <> (
    SELECT count(*) FROM scheduling.assistant_schedules
  ) OR EXISTS (
    SELECT legacy.id
    FROM assistant.ai_schedules AS legacy
    EXCEPT
    SELECT schedule.schedule_id
    FROM scheduling.assistant_schedules AS schedule
  ) THEN
    RAISE EXCEPTION
      'cannot rebuild Assistant scheduling: row or identity migration mismatch'
      USING ERRCODE = 'P0001';
  END IF;
END;
$$;

-- @brief 将 identity sequence 推进到迁移后的最大 ID / Advance the identity sequence past the migrated maximum ID.
SELECT setval(
  pg_get_serial_sequence(
    'scheduling.assistant_schedules',
    'schedule_id'
  ),
  COALESCE(max(schedule_id), 1),
  count(*) > 0
)
FROM scheduling.assistant_schedules;

CREATE INDEX scheduling_assistant_schedules_ready_idx
  ON scheduling.assistant_schedules (
    next_attempt_at,
    next_run_at,
    schedule_id
  )
  WHERE status IN ('pending', 'retry_wait');

CREATE INDEX scheduling_assistant_schedules_expired_lease_idx
  ON scheduling.assistant_schedules (lease_expires_at, schedule_id)
  WHERE status = 'processing';

CREATE INDEX scheduling_assistant_schedules_creator_list_idx
  ON scheduling.assistant_schedules (
    creator_user_id,
    target_conversation_id,
    created_at DESC,
    schedule_id DESC
  );

CREATE UNIQUE INDEX scheduling_assistant_schedules_processing_target_uq
  ON scheduling.assistant_schedules (target_conversation_id)
  WHERE status = 'processing';

DROP TABLE assistant.ai_schedules;

-- migrate:down

DO $$
BEGIN
  RAISE EXCEPTION
    '0061_rebuild_assistant_scheduling is irreversible: the legacy table cannot represent calendar cadence, target identity, retry state, or version fencing'
    USING ERRCODE = '55000';
END;
$$;
