"""@brief Scheduling 聚合重建的迁移与快照契约 / Migration and snapshot contracts for the Scheduling aggregate rebuild."""

from __future__ import annotations

import re
from pathlib import Path

from fogmoe_dbctl.migrations import runner


_PROJECT_ROOT = Path(__file__).resolve().parents[1]
"""@brief 仓库根目录 / Repository root directory."""

_MIGRATION_PATH = (
    _PROJECT_ROOT
    / "src/fogmoe_dbctl/migrations/sql/postgresql/0061_rebuild_assistant_scheduling.sql"
)
"""@brief 0061 PostgreSQL migration / 0061 PostgreSQL migration."""

_VERSION_PATH = (
    _PROJECT_ROOT
    / "src/fogmoe_dbctl/migrations/versions/0061_rebuild_assistant_scheduling.py"
)
"""@brief 0061 Alembic version / 0061 Alembic version."""

_SNAPSHOT_PATH = _PROJECT_ROOT / "src/fogmoe_dbctl/schema.sql"
"""@brief 当前 DDL snapshot / Current DDL snapshot."""


def _table_ddl(sql: str) -> str:
    """@brief 提取并规范 Scheduling 主表 DDL / Extract and normalize the Scheduling aggregate table DDL.

    @param sql migration 或 snapshot SQL / Migration or snapshot SQL.
    @return 空白规范化的 CREATE TABLE / Whitespace-normalized CREATE TABLE.
    """

    marker = "CREATE TABLE scheduling.assistant_schedules ("
    start = sql.index(marker)
    end = sql.index("\n);", start) + len("\n);")
    return " ".join(sql[start:end].split())


def test_0061_version_and_snapshot_share_one_scheduling_aggregate() -> None:
    """@brief 0061 与 snapshot 共享单表聚合及严格状态约束 / 0061 and the snapshot share one aggregate table and strict state constraints."""

    version = _VERSION_PATH.read_text(encoding="utf-8")
    sections = runner._sections(
        _MIGRATION_PATH.read_text(encoding="utf-8"),
        _MIGRATION_PATH,
    )
    upgrade = sections["up"]
    snapshot = _SNAPSHOT_PATH.read_text(encoding="utf-8")

    assert 'revision = "0061_rebuild_assistant_scheduling"' in version
    assert 'down_revision = "0060_retire_asset_action_confirmations"' in version
    assert re.search(r"^-- Alembic head: \S+$", snapshot, flags=re.MULTILINE)
    assert "CREATE SCHEMA IF NOT EXISTS scheduling" in upgrade
    assert "CREATE SCHEMA IF NOT EXISTS scheduling" in snapshot
    assert _table_ddl(upgrade) == _table_ddl(snapshot)

    for storage in (upgrade, snapshot):
        for marker in (
            "schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "creator_user_id BIGINT NOT NULL",
            "REFERENCES identity.users(id) ON DELETE CASCADE",
            "target_kind IN ('private', 'group')",
            "target_conversation_id VARCHAR(512) NOT NULL",
            "target_delivery_stream_id VARCHAR(512) NOT NULL",
            "cadence_kind IN (",
            "'one_shot'",
            "'fixed_interval'",
            "'calendar_daily'",
            "'calendar_weekly'",
            "fixed_interval_seconds BIGINT NULL",
            "calendar_weekday_mask BETWEEN 1 AND 127",
            "time_zone VARCHAR(64) NOT NULL",
            "next_run_at TIMESTAMPTZ NOT NULL",
            "misfire_policy IN ('fire_once', 'skip')",
            "'pending'",
            "'processing'",
            "'retry_wait'",
            "'completed'",
            "'cancelled'",
            "'expired'",
            "'failed_final'",
            "version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0)",
            "scheduling_assistant_schedules_target_shape_ck",
            "scheduling_assistant_schedules_cadence_shape_ck",
            "scheduling_assistant_schedules_ready_ck",
            "scheduling_assistant_schedules_lease_ck",
            "scheduling_assistant_schedules_terminal_ck",
            "scheduling_assistant_schedules_acceptance_ck",
            "scheduling_assistant_schedules_time_ck",
            "CREATE INDEX scheduling_assistant_schedules_ready_idx",
            "CREATE INDEX scheduling_assistant_schedules_expired_lease_idx",
            "CREATE INDEX scheduling_assistant_schedules_creator_list_idx",
            "CREATE UNIQUE INDEX scheduling_assistant_schedules_processing_target_uq",
        ):
            assert marker in storage

    assert snapshot.count("CREATE TABLE scheduling.") == 1
    for forbidden_table in (
        "scheduling.schedule_occurrences",
        "scheduling.schedule_jobs",
        "scheduling.schedule_payloads",
        "scheduling.time_zones",
        "assistant.ai_schedules",
    ):
        assert forbidden_table not in snapshot


def test_0061_maps_legacy_rows_without_changing_time_or_cadence_semantics() -> None:
    """@brief 旧 naive UTC、固定周期、状态和 ID 均显式迁移 / Legacy naive UTC, fixed cadence, state, and IDs are migrated explicitly."""

    sections = runner._sections(
        _MIGRATION_PATH.read_text(encoding="utf-8"),
        _MIGRATION_PATH,
    )
    upgrade = sections["up"]

    for marker in (
        "LOCK TABLE assistant.ai_schedules IN ACCESS EXCLUSIVE MODE",
        "LEFT JOIN identity.users AS creator ON creator.id = legacy.user_id",
        "orphaned or invalid creator identity exists",
        "invalid fixed recurrence exists",
        "invalid intent text exists",
        "INSERT INTO scheduling.assistant_schedules",
        "legacy.id,",
        "'assistant-user:' || legacy.user_id::text",
        "'telegram:primary:chat:' || legacy.user_id::text || ':thread:0'",
        "WHEN 'minute' THEN legacy.recurrence_interval::bigint * 60",
        "WHEN 'hour' THEN legacy.recurrence_interval::bigint * 3600",
        "WHEN 'day' THEN legacy.recurrence_interval::bigint * 86400",
        "legacy.run_at AT TIME ZONE 'UTC'",
        "legacy.created_at AT TIME ZONE 'UTC'",
        "COALESCE(legacy.updated_at, legacy.created_at) AT TIME ZONE 'UTC'",
        "WHEN 'executing' THEN 'retry_wait'",
        "CASE WHEN legacy.status = 'executing' THEN 1 ELSE 0 END",
        "WHEN 'executing' THEN CURRENT_TIMESTAMP",
        "WHEN 'executed' THEN 'completed'",
        "WHEN 'failed' THEN 'failed_final'",
        "COALESCE(legacy.last_run_at, legacy.run_at) AT TIME ZONE 'UTC'",
        "row or identity migration mismatch",
        "pg_get_serial_sequence(",
        "DROP TABLE assistant.ai_schedules",
    ):
        assert marker in upgrade

    assert "calendar_daily" not in upgrade[upgrade.index("INSERT INTO") :]
    assert "calendar_weekly" not in upgrade[upgrade.index("INSERT INTO") :]
    assert "ALTER TABLE assistant.ai_schedules" not in upgrade
    assert "irreversible" in sections["down"]


def test_0061_runner_keeps_preflight_migration_and_drop_as_ordered_statements() -> None:
    """@brief SQL runner 保留预检、复制校验与最终 drop 的原子顺序 / The SQL runner preserves the atomic order of preflight, copy verification, and final drop."""

    sections = runner._sections(
        _MIGRATION_PATH.read_text(encoding="utf-8"),
        _MIGRATION_PATH,
    )
    statements = runner._split_sql_statements(sections["up"])

    lock_index = next(
        index
        for index, statement in enumerate(statements)
        if "LOCK TABLE assistant.ai_schedules" in statement
    )
    preflight_index = next(
        index
        for index, statement in enumerate(statements)
        if "orphaned or invalid creator identity exists" in statement
    )
    create_index = next(
        index
        for index, statement in enumerate(statements)
        if "CREATE TABLE scheduling.assistant_schedules" in statement
    )
    insert_index = next(
        index
        for index, statement in enumerate(statements)
        if "INSERT INTO scheduling.assistant_schedules" in statement
    )
    verify_index = next(
        index
        for index, statement in enumerate(statements)
        if "row or identity migration mismatch" in statement
    )
    drop_index = next(
        index
        for index, statement in enumerate(statements)
        if statement.strip() == "DROP TABLE assistant.ai_schedules"
    )

    assert lock_index < preflight_index < create_index < insert_index < verify_index
    assert verify_index < drop_index
