"""@brief 群组小镇应用命令与结果 / Group-town application commands and results."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from fogmoe_bot.domain.banking.money import TokenAmount
from fogmoe_bot.domain.town._validation import (
    normalize_idempotency_key,
    normalize_instant,
    normalize_text,
)
from fogmoe_bot.domain.town.models import (
    Town,
    TownContribution,
    TownProject,
    TownProjectKind,
)
from fogmoe_bot.domain.town.scope import TownScope
from fogmoe_bot.domain.world.scope import PersonalScope


class TownCode(StrEnum):
    """@brief 群组小镇用例结果代码 / Group-town use-case result codes."""

    SUCCESS = "success"
    """@brief 操作已成功提交 / Operation committed successfully."""

    NOT_REGISTERED = "not_registered"
    """@brief 用户没有可扣除的钱包 / User has no debitable wallet."""

    NOT_FOUND = "not_found"
    """@brief 小镇或项目不存在 / Town or project does not exist."""

    FORBIDDEN = "forbidden"
    """@brief 个人在此小镇没有所需权限 / Person lacks required permission in this town."""

    INSUFFICIENT_FUNDS = "insufficient_funds"
    """@brief 个人免费钱包余额不足 / Personal free-wallet balance is insufficient."""

    PROJECT_UNAVAILABLE = "project_unavailable"
    """@brief 项目不能接受资金或不能结算 / Project cannot accept funding or cannot settle."""

    CONFLICT = "conflict"
    """@brief 幂等键或乐观并发发生冲突 / Idempotency or optimistic-concurrency conflict."""


@dataclass(frozen=True, slots=True)
class EnsureTown:
    """@brief 为一个群组读取或创建唯一小镇 / Read or create the unique town for one group.

    @param town 目标群组小镇范围 / Target group-town scope.
    @param title 首次创建时使用的小镇名称 / Town name used on first creation.
    @param created_at 首次创建时刻 / First creation instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @note ``town`` 不接受裸 chat ID；调用方必须在 Telegram 边界先构造 ``TownScope``。/
        ``town`` does not accept a bare chat ID; callers must construct ``TownScope`` at the Telegram boundary.
    """

    town: TownScope
    """@brief 目标群组小镇范围 / Target group-town scope."""

    title: str
    """@brief 首次创建的小镇名称 / Initial town name."""

    created_at: datetime
    """@brief 首次创建时刻 / First creation instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证小镇读取或创建命令 / Validate the town ensure command.

        @return None / None.
        @raise TypeError 小镇范围非法时抛出 / Raised when town scope is invalid.
        @raise ValueError 名称、时刻或幂等键非法时抛出 /
            Raised when name, instant, or idempotency key is invalid.
        """

        if not isinstance(self.town, TownScope):
            raise TypeError("Town ensure command must use TownScope")
        object.__setattr__(
            self,
            "title",
            normalize_text(
                self.title,
                field="Town title",
                minimum_length=1,
                maximum_length=120,
            ),
        )
        object.__setattr__(
            self,
            "created_at",
            normalize_instant(self.created_at, field="Town ensure time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Town ensure idempotency key",
            ),
        )


@dataclass(frozen=True, slots=True)
class CreateTownProject:
    """@brief 在一座小镇中提议建设项目 / Propose a construction project in one town.

    @param town 目标群组小镇范围 / Target group-town scope.
    @param proposer 提议者个人范围 / Proposer personal scope.
    @param project_id 入口预先生成的项目标识 / Project identity generated by the entry point.
    @param kind 项目类别 / Project category.
    @param title 项目名称 / Project title.
    @param required_amount 项目所需免费金币 / Project-required free tokens.
    @param created_at 提议时刻 / Proposal instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @param prosperity_reward 建成时增加的繁荣度 / Prosperity added on completion.
    """

    town: TownScope
    """@brief 目标群组小镇范围 / Target group-town scope."""

    proposer: PersonalScope
    """@brief 提议者个人范围 / Proposer personal scope."""

    project_id: UUID
    """@brief 项目稳定标识 / Stable project identity."""

    kind: TownProjectKind
    """@brief 项目类别 / Project category."""

    title: str
    """@brief 项目名称 / Project title."""

    required_amount: TokenAmount
    """@brief 所需正数免费金币 / Required positive free-token amount."""

    created_at: datetime
    """@brief 提议时刻 / Proposal instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    prosperity_reward: int = 1
    """@brief 建成繁荣度奖励 / Completion prosperity reward."""

    def __post_init__(self) -> None:
        """@brief 验证项目提议命令 / Validate the project-proposal command.

        @return None / None.
        @raise TypeError 范围、标识、类别或金额类型非法时抛出 /
            Raised when scope, identity, category, or amount types are invalid.
        @raise ValueError 名称、时刻、幂等键或繁荣度非法时抛出 /
            Raised when title, instant, idempotency key, or prosperity is invalid.
        """

        if not isinstance(self.town, TownScope):
            raise TypeError("Town project command must use TownScope")
        if not isinstance(self.proposer, PersonalScope):
            raise TypeError("Town project proposer must use PersonalScope")
        if not isinstance(self.project_id, UUID):
            raise TypeError("Town project ID must be a UUID")
        if not isinstance(self.kind, TownProjectKind):
            raise TypeError("Town project kind must be a TownProjectKind")
        if not isinstance(self.required_amount, TokenAmount):
            raise TypeError("Town project required amount must use TokenAmount")
        if isinstance(self.prosperity_reward, bool) or not isinstance(
            self.prosperity_reward, int
        ):
            raise TypeError("Town project prosperity reward must be an integer")
        if self.prosperity_reward <= 0:
            raise ValueError("Town project prosperity reward must be positive")
        object.__setattr__(
            self,
            "title",
            normalize_text(
                self.title,
                field="Town project title",
                minimum_length=1,
                maximum_length=120,
            ),
        )
        object.__setattr__(
            self,
            "created_at",
            normalize_instant(self.created_at, field="Town project creation time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Town project idempotency key",
            ),
        )

    def project(self) -> TownProject:
        """@brief 构造对应的领域项目聚合 / Construct the corresponding domain project aggregate.

        @return 新的筹资项目 / New funding project.
        """

        return TownProject(
            project_id=self.project_id,
            kind=self.kind,
            title=self.title,
            required_amount=self.required_amount,
            created_by=self.proposer,
            created_at=self.created_at,
            prosperity_reward=self.prosperity_reward,
        )


@dataclass(frozen=True, slots=True)
class ContributeToTown:
    """@brief 以个人免费金币向群组小镇贡献 / Contribute personal free tokens to a group town.

    @param town 目标群组小镇范围 / Target group-town scope.
    @param contributor 贡献者个人范围 / Contributor personal scope.
    @param contribution_id 入口预先生成的贡献标识 / Contribution identity generated by the entry point.
    @param amount 待转入金库的正数免费金币 / Positive free tokens to transfer into treasury.
    @param requested_at 请求时刻 / Request instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @param project_id 可选定向项目标识 / Optional targeted project identity.
    @note 端口必须在一个事务内将个人 ``FREE`` 钱包借记、群组金库贷记、保存贡献、
        更新项目和写入回执。/ The port must in one transaction debit the personal ``FREE``
        wallet, credit the group treasury, save the contribution, update the project, and write a receipt.
    """

    town: TownScope
    """@brief 目标群组小镇范围 / Target group-town scope."""

    contributor: PersonalScope
    """@brief 贡献者个人范围 / Contributor personal scope."""

    contribution_id: UUID
    """@brief 贡献稳定标识 / Stable contribution identity."""

    amount: TokenAmount
    """@brief 待转入正数金额 / Positive amount to transfer."""

    requested_at: datetime
    """@brief 请求时刻 / Request instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    project_id: UUID | None = None
    """@brief 可选定向项目标识 / Optional targeted project identity."""

    def __post_init__(self) -> None:
        """@brief 验证小镇贡献命令 / Validate the town-contribution command.

        @return None / None.
        @raise TypeError 范围、标识或金额类型非法时抛出 /
            Raised when scope, identity, or amount types are invalid.
        """

        if not isinstance(self.town, TownScope):
            raise TypeError("Town contribution command must use TownScope")
        if not isinstance(self.contributor, PersonalScope):
            raise TypeError("Town contributor must use PersonalScope")
        if not isinstance(self.contribution_id, UUID):
            raise TypeError("Town contribution ID must be a UUID")
        if not isinstance(self.amount, TokenAmount):
            raise TypeError("Town contribution amount must use TokenAmount")
        if self.project_id is not None and not isinstance(self.project_id, UUID):
            raise TypeError("Town contribution project ID must be a UUID")
        object.__setattr__(
            self,
            "requested_at",
            normalize_instant(
                self.requested_at, field="Town contribution request time"
            ),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Town contribution idempotency key",
            ),
        )


@dataclass(frozen=True, slots=True)
class CompleteTownProject:
    """@brief 将足额项目通过金库结算为已建成 / Settle a fully funded project as completed.

    @param town 目标群组小镇范围 / Target group-town scope.
    @param operator 执行结算的个人范围 / Personal scope performing settlement.
    @param project_id 待建成项目标识 / Project identity to complete.
    @param completed_at 建成时刻 / Completion instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    @note 端口必须在同一事务中写入金库支出账本分录和项目完成状态。/
        The port must write the treasury-spend ledger entry and project-completion state in one transaction.
    """

    town: TownScope
    """@brief 目标群组小镇范围 / Target group-town scope."""

    operator: PersonalScope
    """@brief 执行结算的个人范围 / Personal scope performing settlement."""

    project_id: UUID
    """@brief 项目稳定标识 / Stable project identity."""

    completed_at: datetime
    """@brief 建成时刻 / Completion instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证项目结算命令 / Validate the project-completion command.

        @return None / None.
        @raise TypeError 范围或项目标识非法时抛出 / Raised when scope or project identity is invalid.
        """

        if not isinstance(self.town, TownScope):
            raise TypeError("Town completion command must use TownScope")
        if not isinstance(self.operator, PersonalScope):
            raise TypeError("Town completion operator must use PersonalScope")
        if not isinstance(self.project_id, UUID):
            raise TypeError("Town completion project ID must be a UUID")
        object.__setattr__(
            self,
            "completed_at",
            normalize_instant(self.completed_at, field="Town project completion time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Town completion idempotency key",
            ),
        )


@dataclass(frozen=True, slots=True)
class TownResult:
    """@brief 群组小镇操作的稳定结果 / Stable result of a group-town operation.

    @param code 操作结果代码 / Operation result code.
    @param town 操作后的可选小镇快照 / Optional town snapshot after the operation.
    @param project 操作涉及的可选项目 / Optional project involved in the operation.
    @param contribution 操作产生的可选贡献 / Optional contribution produced by the operation.
    @param replayed 是否来自幂等回放 / Whether result came from idempotent replay.
    """

    code: TownCode
    """@brief 操作结果代码 / Operation result code."""

    town: Town | None = None
    """@brief 可选小镇快照 / Optional town snapshot."""

    project: TownProject | None = None
    """@brief 可选项目快照 / Optional project snapshot."""

    contribution: TownContribution | None = None
    """@brief 可选贡献快照 / Optional contribution snapshot."""

    replayed: bool = False
    """@brief 是否来自幂等回放 / Whether this is an idempotent replay."""

    def __post_init__(self) -> None:
        """@brief 验证小镇结果载荷类型 / Validate town-result payload types.

        @return None / None.
        @raise TypeError 结果代码或可选载荷类型非法时抛出 /
            Raised when result code or optional payload types are invalid.
        """

        if not isinstance(self.code, TownCode):
            raise TypeError("Town result code must be a TownCode")
        if self.town is not None and not isinstance(self.town, Town):
            raise TypeError("Town result town must be a Town")
        if self.project is not None and not isinstance(self.project, TownProject):
            raise TypeError("Town result project must be a TownProject")
        if self.contribution is not None and not isinstance(
            self.contribution, TownContribution
        ):
            raise TypeError("Town result contribution must be a TownContribution")
        if not isinstance(self.replayed, bool):
            raise TypeError("Town result replayed flag must be a bool")
