-- FogMoe PostgreSQL schema snapshot
--
-- Source migrations: 0001_initial through 0013_add_ai_schedule_recurrence
-- Alembic head: 0013_add_ai_schedule_recurrence
--
-- This file is a DDL-only snapshot.  It intentionally excludes data migrations
-- (including the initial stake_reward_pool row and user-plan backfill) and the
-- dynamically maintained infra.alembic_version row.

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS conversation;
CREATE SCHEMA IF NOT EXISTS assistant;
CREATE SCHEMA IF NOT EXISTS economy;
CREATE SCHEMA IF NOT EXISTS moderation;
CREATE SCHEMA IF NOT EXISTS crypto;
CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS infra;

-- DB_MIGRATION_SCHEMA defaults to infra.  Its version value is data, so it is
-- intentionally not recorded in this schema-only snapshot.
CREATE TABLE infra.alembic_version (
  version_num VARCHAR(255) NOT NULL,
  CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE conversation.chat_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL UNIQUE,
  messages JSONB NOT NULL,
  timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  last_rotated_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE conversation.permanent_chat_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  conversation_snapshot JSONB NOT NULL,
  summary TEXT NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_permanent_user_created
  ON conversation.permanent_chat_records (user_id, created_at);

CREATE TABLE conversation.chat_records_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  message_type TEXT NOT NULL DEFAULT 'text'
    CHECK (message_type IN ('text','photo','sticker','voice','video','document','other')),
  content TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_group_created
  ON conversation.chat_records_group (group_id, created_at);
CREATE INDEX idx_group_message
  ON conversation.chat_records_group (group_id, message_id);

CREATE TABLE conversation.ai_user_diary_pages (
  user_id BIGINT NOT NULL,
  page_no INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, page_no)
);

CREATE TABLE identity.users (
  id BIGINT NOT NULL PRIMARY KEY,
  tg_uid BIGINT NULL UNIQUE,
  provider TEXT NOT NULL DEFAULT 'telegram'
    CHECK (provider IN ('telegram','local','web')),
  name TEXT NOT NULL,
  coins INT NOT NULL DEFAULT 0,
  permission INT DEFAULT 0,
  info VARCHAR(500) DEFAULT NULL,
  permanent_records_limit INT NOT NULL DEFAULT 100,
  recharge_blocked_until TIMESTAMP NULL,
  coins_paid INT NOT NULL DEFAULT 0,
  user_plan VARCHAR(10) NOT NULL DEFAULT 'free'
);

CREATE TABLE identity.web_password (
  user_id BIGINT NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE assistant.ai_user_affection (
  user_id BIGINT NOT NULL PRIMARY KEY,
  affection INT NOT NULL DEFAULT 0,
  impression VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_user_affection_user
    FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE assistant.ai_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  run_at TIMESTAMP NOT NULL,
  trigger_reason VARCHAR(200) NOT NULL,
  context TEXT NULL,
  prompt TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','executing','executed','cancelled','failed')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  executed_at TIMESTAMP NULL DEFAULT NULL,
  error TEXT NULL,
  recurrence_unit TEXT NOT NULL DEFAULT 'none'
    CHECK (recurrence_unit IN ('none','minute','hour','day')),
  recurrence_interval INT NOT NULL DEFAULT 1,
  last_run_at TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX idx_ai_schedules_user_status
  ON assistant.ai_schedules (user_id, status);
CREATE INDEX idx_ai_schedules_run
  ON assistant.ai_schedules (status, run_at);

CREATE TABLE economy.user_lottery (
  user_id BIGINT NOT NULL PRIMARY KEY,
  last_lottery_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE economy.user_task (
  user_id BIGINT NOT NULL,
  task_id INT NOT NULL,
  completed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, task_id)
);

CREATE TABLE economy.user_stakes (
  user_id BIGINT NOT NULL PRIMARY KEY,
  stake_amount INT NOT NULL,
  stake_time TIMESTAMP NOT NULL,
  last_reward_time TIMESTAMP NULL
);

CREATE TABLE economy.stake_reward_pool (
  id SMALLINT NOT NULL PRIMARY KEY,
  balance DECIMAL(20,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE economy.redemption_codes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL UNIQUE,
  amount INT NOT NULL,
  is_used BOOLEAN NOT NULL DEFAULT FALSE,
  used_by BIGINT DEFAULT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (used_by) REFERENCES identity.users(id) ON DELETE SET NULL
);

CREATE TABLE economy.user_invitations (
  invited_user_id BIGINT NOT NULL,
  referrer_id BIGINT NOT NULL,
  invitation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reward_claimed BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (invited_user_id),
  FOREIGN KEY (invited_user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (referrer_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE economy.user_checkin (
  user_id BIGINT NOT NULL PRIMARY KEY,
  last_checkin_date DATE NOT NULL,
  consecutive_days INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE economy.kindness_gifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL,
  amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kindness_recipient_created
  ON economy.kindness_gifts (recipient_id, created_at);

CREATE TABLE economy.user_give_daily (
  user_id BIGINT NOT NULL,
  give_date DATE NOT NULL,
  give_count INT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, give_date)
);

CREATE TABLE moderation.group_verification (
  group_id BIGINT NOT NULL PRIMARY KEY,
  group_name TEXT NOT NULL
);

CREATE TABLE moderation.verification_tasks (
  user_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  expire_time TIMESTAMP NOT NULL,
  token_hash VARCHAR(64),
  PRIMARY KEY (user_id, group_id)
);

CREATE TABLE moderation.group_keywords (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  response TEXT NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_keyword_unique UNIQUE (group_id, keyword)
);

CREATE TABLE moderation.group_spam_control (
  group_id BIGINT NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  enabled_by BIGINT,
  enabled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  block_links BOOLEAN NOT NULL DEFAULT FALSE,
  block_mentions BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE moderation.group_spam_keywords (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  is_regex BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_spam_keyword_unique UNIQUE (group_id, keyword)
);

CREATE TABLE crypto.user_btc_predictions (
  user_id BIGINT NOT NULL PRIMARY KEY,
  predict_type VARCHAR(10) NOT NULL,
  amount INT NOT NULL,
  start_price DECIMAL(20,8) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE crypto.token_swap_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username VARCHAR(255) NOT NULL,
  wallet_address VARCHAR(50) NOT NULL,
  amount INT NOT NULL,
  request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'pending'
);

CREATE TABLE crypto.group_chart_tokens (
  group_id BIGINT NOT NULL PRIMARY KEY,
  chain VARCHAR(20) NOT NULL,
  ca VARCHAR(100) NOT NULL,
  set_by BIGINT NOT NULL,
  buy_alert_threshold FLOAT NULL,
  set_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.user_omikuji (
  user_id BIGINT NOT NULL,
  fortune_date DATE NOT NULL,
  fortune VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, fortune_date)
);

CREATE TABLE game.rpg_characters (
  character_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL,
  level INT DEFAULT 1,
  hp INT DEFAULT 10,
  max_hp INT DEFAULT 10,
  atk INT DEFAULT 2,
  matk INT DEFAULT 0,
  def INT DEFAULT 1,
  experience BIGINT DEFAULT 0,
  allow_battle BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE game.rpg_equipment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type TEXT NOT NULL
    CHECK (type IN ('weapon', 'offhand', 'armor', 'treasure1', 'treasure2')),
  atk_bonus INT DEFAULT 0,
  def_bonus INT DEFAULT 0,
  hp_bonus INT DEFAULT 0,
  matk_bonus INT DEFAULT 0,
  description TEXT,
  price INT NOT NULL,
  rarity INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type TEXT NOT NULL
    CHECK (type IN ('consumable', 'material', 'quest')),
  effect TEXT,
  description TEXT,
  price INT NOT NULL,
  use_limit INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_player_equipment (
  user_id BIGINT NOT NULL PRIMARY KEY,
  weapon_id INT DEFAULT NULL,
  offhand_id INT DEFAULT NULL,
  armor_id INT DEFAULT NULL,
  treasure1_id INT DEFAULT NULL,
  treasure2_id INT DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (weapon_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (offhand_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (armor_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (treasure1_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (treasure2_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL
);

CREATE TABLE game.rpg_player_inventory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  quantity INT DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES game.rpg_items(id) ON DELETE CASCADE,
  CONSTRAINT rpg_player_inventory_unique UNIQUE (user_id, item_id)
);

CREATE TABLE game.rpg_shop (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type TEXT NOT NULL CHECK (item_type IN ('equipment', 'item')),
  item_id INT NOT NULL,
  price INT NOT NULL,
  stock INT DEFAULT -1,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT rpg_shop_item_unique UNIQUE (item_type, item_id)
);

CREATE INDEX idx_rpg_shop_item ON game.rpg_shop (item_type, item_id);

CREATE TABLE game.rpg_player_equipment_stats (
  user_id BIGINT NOT NULL PRIMARY KEY,
  total_atk_bonus INT DEFAULT 0,
  total_def_bonus INT DEFAULT 0,
  total_hp_bonus INT DEFAULT 0,
  total_matk_bonus INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);
