-- FogMoe PostgreSQL schema snapshot
--
-- Source migrations: 0001_initial through 0040_memory_context_boundaries
-- Alembic head: 0040_memory_context_boundaries
--
-- This file is a DDL-only snapshot.  It intentionally excludes data migrations
-- (including the initial stake_reward_pool row and user-plan backfill) and the
-- dynamically maintained infra.alembic_version row.

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS conversation;
CREATE SCHEMA IF NOT EXISTS assistant;
CREATE SCHEMA IF NOT EXISTS economy;
CREATE SCHEMA IF NOT EXISTS moderation;
CREATE SCHEMA IF NOT EXISTS crypto;
CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS infra;
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS observability;
CREATE SCHEMA IF NOT EXISTS context_window;
CREATE SCHEMA IF NOT EXISTS memory;

-- DB_MIGRATION_SCHEMA defaults to infra.  Its version value is data, so it is
-- intentionally not recorded in this schema-only snapshot.
CREATE TABLE infra.alembic_version (
  version_num VARCHAR(255) NOT NULL,
  CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE conversation.group_message_projection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  message_type TEXT NOT NULL DEFAULT 'text'
    CHECK (message_type IN ('text','photo','sticker','voice','video','document','other')),
  content TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_update_id BIGINT,
  content_encoding TEXT NOT NULL DEFAULT 'plain',
  is_edited BOOLEAN NOT NULL DEFAULT FALSE,
  is_canonical BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT group_message_projection_source_update_ck CHECK (
    source_update_id IS NULL OR source_update_id >= 0
  ),
  CONSTRAINT group_message_projection_encoding_ck CHECK (
    content_encoding IN ('plain', 'base64')
  ),
  CONSTRAINT group_message_projection_time_ck CHECK (
    updated_at >= created_at
  )
);

CREATE INDEX idx_group_message_projection_created
  ON conversation.group_message_projection (group_id, created_at);
CREATE INDEX idx_group_message_projection_message
  ON conversation.group_message_projection (group_id, message_id);
CREATE UNIQUE INDEX uq_group_message_projection_canonical
  ON conversation.group_message_projection (group_id, message_id)
  WHERE is_canonical;
CREATE INDEX idx_group_message_projection_recent
  ON conversation.group_message_projection (group_id, message_id DESC, id DESC)
  WHERE is_canonical;

CREATE TABLE conversation.ai_user_diary_pages (
  user_id BIGINT NOT NULL,
  page_no INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, page_no)
);

-- One database namespace serves one logical Telegram bot.  update_id is the
-- durable idempotency key shared by every process instance consuming that bot.
CREATE TABLE conversation.inbound_updates (
  update_id BIGINT PRIMARY KEY CHECK (update_id >= 0),
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'processing', 'retry_wait', 'processed', 'failed_final')
  ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ,
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  last_error TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMPTZ,
  traceparent VARCHAR(55) NOT NULL,
  CONSTRAINT inbound_updates_claimable_time_ck CHECK (
    (status IN ('pending', 'retry_wait')) = (next_attempt_at IS NOT NULL)
  ),
  CONSTRAINT inbound_updates_lease_ck CHECK (
    (status = 'processing') = (
      claim_token IS NOT NULL AND lease_expires_at IS NOT NULL
    )
  ),
  CONSTRAINT inbound_updates_processed_at_ck CHECK (
    (status = 'processed') = (processed_at IS NOT NULL)
  ),
  CONSTRAINT inbound_updates_traceparent_ck CHECK (
    traceparent IS NULL OR traceparent ~ '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'
  )
);

CREATE INDEX idx_inbound_updates_ready
  ON conversation.inbound_updates (next_attempt_at, update_id)
  WHERE status IN ('pending', 'retry_wait');

CREATE INDEX idx_inbound_updates_expired_lease
  ON conversation.inbound_updates (lease_expires_at, update_id)
  WHERE status = 'processing';

CREATE INDEX idx_inbound_updates_conversation
  ON conversation.inbound_updates (conversation_id, received_at, update_id);

CREATE INDEX idx_inbound_updates_stream_head
  ON conversation.inbound_updates (conversation_id, update_id)
  WHERE status IN ('pending', 'processing', 'retry_wait');

CREATE TABLE conversation.conversation_turns (
  turn_id UUID PRIMARY KEY,
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  source_update_id BIGINT UNIQUE REFERENCES conversation.inbound_updates(update_id),
  state TEXT NOT NULL DEFAULT 'received' CHECK (
    state IN (
      'received',
      'accepted',
      'waiting_inference',
      'inference_retry_wait',
      'inference_completed',
      'waiting_delivery',
      'delivery_retry_wait',
      'delivered',
      'cancelled',
      'failed_final'
    )
  ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  inference_attempts INTEGER NOT NULL DEFAULT 0 CHECK (inference_attempts >= 0),
  delivery_attempts INTEGER NOT NULL DEFAULT 0 CHECK (delivery_attempts >= 0),
  next_retry_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  source_kind VARCHAR(100) NOT NULL,
  source_key VARCHAR(255) NOT NULL,
  CONSTRAINT conversation_turns_retry_time_ck CHECK (
    (state IN ('inference_retry_wait', 'delivery_retry_wait')) = (next_retry_at IS NOT NULL)
  ),
  CONSTRAINT conversation_turns_completed_at_ck CHECK (
    (state IN ('delivered', 'cancelled', 'failed_final')) = (completed_at IS NOT NULL)
  ),
  CONSTRAINT conversation_turns_source_kind_ck CHECK (
    source_kind ~ '^[a-z][a-z0-9_.-]{0,99}$'
  ),
  CONSTRAINT conversation_turns_source_key_ck CHECK (
    char_length(source_key) BETWEEN 1 AND 255
  ),
  CONSTRAINT conversation_turns_source_identity_uq UNIQUE (
    source_kind,
    source_key
  ),
  CONSTRAINT conversation_turns_telegram_source_ck CHECK (
    (source_kind = 'telegram.update') = (source_update_id IS NOT NULL)
    AND (
      source_kind <> 'telegram.update'
      OR source_key = source_update_id::TEXT
    )
  )
);

CREATE INDEX idx_conversation_turns_stream
  ON conversation.conversation_turns (conversation_id, created_at, turn_id);

CREATE INDEX idx_conversation_turns_retry
  ON conversation.conversation_turns (next_retry_at, turn_id)
  WHERE state IN ('inference_retry_wait', 'delivery_retry_wait');

CREATE INDEX idx_conversation_turns_active
  ON conversation.conversation_turns (conversation_id, updated_at, turn_id)
  WHERE state NOT IN ('delivered', 'cancelled', 'failed_final');

CREATE TABLE conversation.inference_activities (
  activity_id UUID PRIMARY KEY,
  turn_id UUID NOT NULL UNIQUE
    REFERENCES conversation.conversation_turns(turn_id),
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  request JSONB NOT NULL CHECK (jsonb_typeof(request) = 'object'),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'processing', 'retry', 'completed', 'failed', 'cancelled')
  ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ,
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  completion_token UUID,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  traceparent VARCHAR(55) NOT NULL,
  CONSTRAINT inference_activities_claimable_time_ck CHECK (
    (status IN ('pending', 'retry')) = (next_attempt_at IS NOT NULL)
  ),
  CONSTRAINT inference_activities_lease_ck CHECK (
    (status = 'processing') = (
      claim_token IS NOT NULL AND lease_expires_at IS NOT NULL
    )
  ),
  CONSTRAINT inference_activities_claim_pair_ck CHECK (
    (claim_token IS NULL) = (lease_expires_at IS NULL)
  ),
  CONSTRAINT inference_activities_completed_at_ck CHECK (
    (status = 'completed') = (completed_at IS NOT NULL)
  ),
  CONSTRAINT inference_activities_completion_token_ck CHECK (
    (status = 'completed') = (completion_token IS NOT NULL)
  ),
  CONSTRAINT inference_activities_traceparent_ck CHECK (
    traceparent IS NULL OR traceparent ~ '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'
  )
);

CREATE INDEX idx_inference_activities_ready
  ON conversation.inference_activities (next_attempt_at, activity_id)
  WHERE status IN ('pending', 'retry');

CREATE INDEX idx_inference_activities_expired_lease
  ON conversation.inference_activities (lease_expires_at, activity_id)
  WHERE status = 'processing';

CREATE UNIQUE INDEX uq_inference_activities_processing_conversation
  ON conversation.inference_activities (conversation_id)
  WHERE status = 'processing';

CREATE INDEX idx_inference_activities_conversation
  ON conversation.inference_activities (conversation_id, created_at, activity_id);

CREATE TABLE conversation.conversation_messages (
  message_id UUID PRIMARY KEY,
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  sequence BIGINT NOT NULL CHECK (sequence >= 1),
  turn_id UUID REFERENCES conversation.conversation_turns(turn_id),
  source_update_id BIGINT REFERENCES conversation.inbound_updates(update_id),
  role TEXT NOT NULL CHECK (role IN ('system', 'user', 'assistant', 'tool')),
  content JSONB NOT NULL CHECK (jsonb_typeof(content) = 'object'),
  idempotency_key VARCHAR(255) NOT NULL CHECK (char_length(idempotency_key) >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT conversation_messages_sequence_uq UNIQUE (conversation_id, sequence),
  CONSTRAINT conversation_messages_idempotency_uq UNIQUE (
    conversation_id,
    idempotency_key
  )
);

CREATE INDEX idx_conversation_messages_turn
  ON conversation.conversation_messages (turn_id, sequence)
  WHERE turn_id IS NOT NULL;

CREATE INDEX idx_conversation_messages_source_update
  ON conversation.conversation_messages (source_update_id)
  WHERE source_update_id IS NOT NULL;

-- History reset is an append-only visibility boundary.  It preserves audit
-- rows and lets already accepted Turns retain their pre-reset history snapshot.
CREATE TABLE conversation.conversation_history_resets (
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  source_kind VARCHAR(100) NOT NULL CHECK (
    source_kind ~ '^[a-z][a-z0-9_.-]{0,99}$'
  ),
  source_key VARCHAR(255) NOT NULL CHECK (
    char_length(source_key) BETWEEN 1 AND 255
  ),
  source_update_id BIGINT UNIQUE
    REFERENCES conversation.inbound_updates(update_id),
  through_sequence BIGINT NOT NULL CHECK (through_sequence >= 0),
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (source_kind, source_key),
  CONSTRAINT conversation_history_resets_telegram_source_ck CHECK (
    (source_kind = 'telegram.update') = (source_update_id IS NOT NULL)
    AND (
      source_kind <> 'telegram.update'
      OR source_key = source_update_id::TEXT
    )
  )
);

CREATE INDEX idx_conversation_history_resets_boundary
  ON conversation.conversation_history_resets (
    conversation_id,
    through_sequence DESC,
    created_at DESC
  );

CREATE TABLE conversation.outbound_messages (
  message_id UUID PRIMARY KEY,
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  turn_id UUID REFERENCES conversation.conversation_turns(turn_id),
  delivery_stream_id TEXT NOT NULL CHECK (
    char_length(delivery_stream_id) BETWEEN 1 AND 512
  ),
  stream_sequence BIGINT NOT NULL CHECK (stream_sequence >= 1),
  kind VARCHAR(100) NOT NULL CHECK (char_length(kind) >= 1),
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  idempotency_key VARCHAR(255) NOT NULL CHECK (char_length(idempotency_key) >= 1),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'processing', 'retry_wait', 'delivered', 'failed_final', 'cancelled')
  ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ,
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  external_message_id TEXT,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delivered_at TIMESTAMPTZ,
  traceparent VARCHAR(55) NOT NULL,
  CONSTRAINT outbound_messages_idempotency_uq UNIQUE (
    conversation_id,
    idempotency_key
  ),
  CONSTRAINT outbound_messages_stream_sequence_uq UNIQUE (
    delivery_stream_id,
    stream_sequence
  ),
  CONSTRAINT outbound_messages_claimable_time_ck CHECK (
    (status IN ('pending', 'retry_wait')) = (next_attempt_at IS NOT NULL)
  ),
  CONSTRAINT outbound_messages_lease_ck CHECK (
    (status = 'processing') = (
      claim_token IS NOT NULL AND lease_expires_at IS NOT NULL
    )
  ),
  CONSTRAINT outbound_messages_delivered_at_ck CHECK (
    (status = 'delivered') = (delivered_at IS NOT NULL)
  ),
  CONSTRAINT outbound_messages_traceparent_ck CHECK (
    traceparent IS NULL OR traceparent ~ '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'
  )
);

CREATE INDEX idx_outbound_messages_ready
  ON conversation.outbound_messages (
    next_attempt_at,
    delivery_stream_id,
    stream_sequence
  )
  WHERE status IN ('pending', 'retry_wait');

CREATE INDEX idx_outbound_messages_expired_lease
  ON conversation.outbound_messages (lease_expires_at, message_id)
  WHERE status = 'processing';

CREATE INDEX idx_outbound_messages_stream_head
  ON conversation.outbound_messages (delivery_stream_id, stream_sequence)
  WHERE status IN ('pending', 'processing', 'retry_wait');

CREATE TABLE context_window.compactions (
  compaction_id UUID PRIMARY KEY,
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  owner_user_id BIGINT NOT NULL CHECK (owner_user_id > 0),
  epoch_floor_sequence BIGINT NOT NULL,
  from_sequence BIGINT NOT NULL,
  through_sequence BIGINT NOT NULL,
  anchor_turn_id UUID NOT NULL
    REFERENCES conversation.conversation_turns(turn_id) ON DELETE RESTRICT,
  predecessor_compaction_id UUID
    REFERENCES context_window.compactions(compaction_id) ON DELETE RESTRICT,
  projection_version SMALLINT NOT NULL CHECK (projection_version > 0),
  source_digest CHAR(64) NOT NULL CHECK (source_digest ~ '^[0-9a-f]{64}$'),
  source_snapshot JSON NOT NULL CHECK (json_typeof(source_snapshot) = 'array'),
  source_row_count INTEGER NOT NULL CHECK (source_row_count > 0),
  source_token_count INTEGER NOT NULL CHECK (source_token_count >= 0),
  status TEXT NOT NULL CHECK (
    status IN (
      'pending',
      'processing',
      'retry_wait',
      'completed',
      'failed_final',
      'cancelled'
    )
  ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ,
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  completion_token UUID,
  summary_text TEXT,
  summary_token_count INTEGER CHECK (
    summary_token_count BETWEEN 1 AND 2500
  ),
  summary_route_key VARCHAR(512),
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  CONSTRAINT compactions_source_ck CHECK (
    json_array_length(source_snapshot) > 0
  ),
  CONSTRAINT compactions_range_ck CHECK (
    epoch_floor_sequence >= 0
    AND from_sequence > epoch_floor_sequence
    AND through_sequence >= from_sequence
  ),
  CONSTRAINT compactions_claimable_time_ck CHECK (
    (status IN ('pending', 'retry_wait')) = (next_attempt_at IS NOT NULL)
  ),
  CONSTRAINT compactions_lease_ck CHECK (
    (status = 'processing') = (
      claim_token IS NOT NULL AND lease_expires_at IS NOT NULL
    )
  ),
  CONSTRAINT compactions_claim_pair_ck CHECK (
    (claim_token IS NULL) = (lease_expires_at IS NULL)
  ),
  CONSTRAINT compactions_terminal_time_ck CHECK (
    (status IN ('completed', 'failed_final', 'cancelled')) =
    (completed_at IS NOT NULL)
  ),
  CONSTRAINT compactions_completion_token_ck CHECK (
    (status = 'completed') = (completion_token IS NOT NULL)
  ),
  CONSTRAINT compactions_summary_shape_ck CHECK (
    (summary_text IS NULL AND summary_token_count IS NULL AND summary_route_key IS NULL)
    OR (
      summary_text IS NOT NULL
      AND char_length(btrim(summary_text)) > 0
      AND summary_token_count IS NOT NULL
      AND summary_route_key IS NOT NULL
      AND char_length(btrim(summary_route_key)) > 0
    )
  ),
  CONSTRAINT compactions_completed_summary_ck CHECK (
    status <> 'completed' OR summary_text IS NOT NULL
  ),
  CONSTRAINT compactions_time_order_ck CHECK (
    updated_at >= created_at
    AND (completed_at IS NULL OR completed_at >= created_at)
  ),
  CONSTRAINT compactions_range_uq UNIQUE (
    conversation_id,
    epoch_floor_sequence,
    through_sequence,
    projection_version
  )
);

CREATE UNIQUE INDEX compactions_active_epoch_uq
  ON context_window.compactions (conversation_id, epoch_floor_sequence)
  WHERE status IN ('pending', 'processing', 'retry_wait');

CREATE INDEX compactions_ready_idx
  ON context_window.compactions (next_attempt_at, compaction_id)
  WHERE status IN ('pending', 'retry_wait');

CREATE INDEX compactions_expired_lease_idx
  ON context_window.compactions (lease_expires_at, compaction_id)
  WHERE status = 'processing';

CREATE INDEX compactions_projection_idx
  ON context_window.compactions (
    conversation_id,
    epoch_floor_sequence,
    through_sequence DESC,
    completed_at DESC
  )
  WHERE status = 'completed';

CREATE TABLE identity.users (
  id BIGINT NOT NULL PRIMARY KEY,
  tg_uid BIGINT NULL UNIQUE,
  provider TEXT NOT NULL DEFAULT 'telegram'
    CHECK (provider IN ('telegram','local','web')),
  name TEXT NOT NULL,
  coins INT NOT NULL DEFAULT 0,
  permission INT DEFAULT 0,
  info VARCHAR(500) DEFAULT NULL,
  permanent_records_limit INT NOT NULL DEFAULT 100,
  recharge_blocked_until TIMESTAMP NULL,
  coins_paid INT NOT NULL DEFAULT 0,
  user_plan VARCHAR(10) NOT NULL DEFAULT 'free'
);

CREATE TABLE memory.records (
  memory_id UUID PRIMARY KEY,
  owner_user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL CHECK (
    char_length(conversation_id) BETWEEN 1 AND 512
  ),
  source_kind TEXT NOT NULL CHECK (
    source_kind IN ('compaction_checkpoint', 'legacy_archive')
  ),
  source_id UUID NOT NULL UNIQUE,
  source_digest CHAR(64) NOT NULL CHECK (
    source_digest ~ '^[0-9a-f]{64}$'
  ),
  snapshot JSON NOT NULL CHECK (json_typeof(snapshot) = 'array'),
  summary_text TEXT,
  legacy_record_id BIGINT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT memory_records_summary_ck CHECK (
    summary_text IS NULL OR char_length(btrim(summary_text)) > 0
  )
);

CREATE INDEX memory_records_owner_created_idx
  ON memory.records (owner_user_id, created_at DESC, memory_id DESC);

CREATE TABLE identity.operation_receipts (
  idempotency_key VARCHAR(200) PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) > 0),
  operation_kind VARCHAR(80) NOT NULL
    CHECK (char_length(btrim(operation_kind)) > 0),
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  result JSONB NOT NULL CHECK (jsonb_typeof(result) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX identity_operation_receipts_user_created_idx
  ON identity.operation_receipts (user_id, created_at, idempotency_key);

CREATE TABLE admin.announcements (
  announcement_id UUID PRIMARY KEY,
  idempotency_key VARCHAR(255) NOT NULL UNIQUE
    CHECK (char_length(btrim(idempotency_key)) BETWEEN 1 AND 255),
  requested_by BIGINT NOT NULL CHECK (requested_by > 0),
  source_update_id BIGINT NOT NULL UNIQUE
    REFERENCES conversation.inbound_updates(update_id) ON DELETE RESTRICT,
  body TEXT NOT NULL
    CHECK (char_length(btrim(body)) BETWEEN 1 AND 3500),
  recipient_count INTEGER NOT NULL DEFAULT 0 CHECK (recipient_count >= 0),
  state TEXT NOT NULL DEFAULT 'expanding'
    CHECK (state IN ('expanding', 'delivering', 'completed')),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  CONSTRAINT admin_announcements_time_order_ck CHECK (updated_at >= created_at),
  CONSTRAINT admin_announcements_completed_shape_ck CHECK (
    (state = 'completed') = (completed_at IS NOT NULL)
  )
);

CREATE INDEX admin_announcements_state_created_idx
  ON admin.announcements (state, created_at, announcement_id);

CREATE TABLE admin.announcement_recipients (
  announcement_id UUID NOT NULL
    REFERENCES admin.announcements(announcement_id) ON DELETE CASCADE,
  recipient_kind TEXT NOT NULL
    CHECK (recipient_kind IN ('user', 'group', 'completion')),
  chat_id BIGINT NOT NULL CHECK (chat_id <> 0),
  message_thread_id BIGINT CHECK (
    message_thread_id IS NULL OR message_thread_id > 0
  ),
  reply_to_message_id BIGINT CHECK (
    reply_to_message_id IS NULL OR reply_to_message_id > 0
  ),
  status TEXT NOT NULL CHECK (
    status IN (
      'blocked',
      'pending',
      'processing',
      'retry_wait',
      'expanded',
      'failed_final'
    )
  ),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ,
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  outbound_message_id UUID UNIQUE
    REFERENCES conversation.outbound_messages(message_id) ON DELETE RESTRICT,
  last_error VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  expanded_at TIMESTAMPTZ,
  terminal_at TIMESTAMPTZ,
  PRIMARY KEY (announcement_id, recipient_kind, chat_id),
  CONSTRAINT admin_announcement_recipients_address_ck CHECK (
    (recipient_kind = 'completion') = (reply_to_message_id IS NOT NULL)
  ),
  CONSTRAINT admin_announcement_recipients_blocked_ck CHECK (
    status <> 'blocked' OR recipient_kind = 'completion'
  ),
  CONSTRAINT admin_announcement_recipients_claimable_ck CHECK (
    (status IN ('pending', 'retry_wait')) = (next_attempt_at IS NOT NULL)
  ),
  CONSTRAINT admin_announcement_recipients_lease_ck CHECK (
    (status = 'processing') =
    (claim_token IS NOT NULL AND lease_expires_at IS NOT NULL)
  ),
  CONSTRAINT admin_announcement_recipients_expanded_ck CHECK (
    (status = 'expanded') =
    (outbound_message_id IS NOT NULL AND expanded_at IS NOT NULL)
  ),
  CONSTRAINT admin_announcement_recipients_failed_ck CHECK (
    (status = 'failed_final') = (terminal_at IS NOT NULL)
  ),
  CONSTRAINT admin_announcement_recipients_time_order_ck CHECK (
    updated_at >= created_at
  )
);

CREATE INDEX admin_announcement_recipients_ready_idx
  ON admin.announcement_recipients
    (next_attempt_at, announcement_id, recipient_kind, chat_id)
  WHERE status IN ('pending', 'retry_wait');

CREATE INDEX admin_announcement_recipients_expired_idx
  ON admin.announcement_recipients
    (lease_expires_at, announcement_id, recipient_kind, chat_id)
  WHERE status = 'processing';

CREATE TABLE media.picture_offers (
  offer_id UUID PRIMARY KEY,
  source_id TEXT NOT NULL CHECK (char_length(btrim(source_id)) BETWEEN 1 AND 255),
  sample_url TEXT,
  file_url TEXT,
  tags TEXT NOT NULL DEFAULT '',
  width INTEGER CHECK (width IS NULL OR width > 0),
  height INTEGER CHECK (height IS NULL OR height > 0),
  file_size BIGINT CHECK (file_size IS NULL OR file_size > 0),
  score INTEGER,
  rating TEXT NOT NULL CHECK (rating IN ('safe', 'nsfw')),
  requester_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  expires_at TIMESTAMPTZ NOT NULL,
  state TEXT NOT NULL CHECK (
    state IN ('preview_pending', 'available', 'charged', 'delivered', 'refunded')
  ),
  charged_user_id BIGINT
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  claim_expires_at TIMESTAMPTZ,
  preview_cost SMALLINT NOT NULL CHECK (preview_cost > 0),
  hd_cost SMALLINT CHECK (hd_cost IS NULL OR hd_cost > 0),
  preview_confirm_by TIMESTAMPTZ NOT NULL,
  preview_refunded BOOLEAN NOT NULL DEFAULT FALSE,
  hd_refunded BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (sample_url IS NOT NULL OR file_url IS NOT NULL),
  CHECK (state <> 'charged' OR charged_user_id IS NOT NULL),
  CHECK (state NOT IN ('charged', 'delivered') OR hd_cost IS NOT NULL),
  CHECK (claim_expires_at IS NULL OR state = 'charged')
);

CREATE INDEX picture_offers_recovery_idx
  ON media.picture_offers (state, preview_confirm_by, claim_expires_at, expires_at);
CREATE INDEX picture_offers_requester_created_idx
  ON media.picture_offers (requester_id, created_at DESC);

CREATE TABLE media.music_sessions (
  search_id UUID PRIMARY KEY,
  requester_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  query TEXT NOT NULL CHECK (char_length(query) BETWEEN 1 AND 200),
  platform TEXT NOT NULL CHECK (platform IN ('wy', 'qq', 'kw', 'mg', 'qi')),
  tracks JSONB NOT NULL CHECK (jsonb_typeof(tracks) = 'array'),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX music_sessions_expiry_idx
  ON media.music_sessions (expires_at);
CREATE INDEX music_sessions_requester_created_idx
  ON media.music_sessions (requester_id, created_at DESC);

CREATE TABLE media.picture_request_receipts (
  idempotency_key VARCHAR(200) PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) BETWEEN 1 AND 200),
  requester_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  rating TEXT NOT NULL CHECK (rating IN ('safe', 'nsfw')),
  request_fingerprint CHAR(64) NOT NULL CHECK (
    request_fingerprint ~ '^[0-9a-f]{64}$'
  ),
  offer_id UUID NOT NULL UNIQUE,
  outbound_message_id UUID NOT NULL UNIQUE
    REFERENCES conversation.outbound_messages(message_id) ON DELETE RESTRICT,
  result JSONB NOT NULL CHECK (jsonb_typeof(result) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX picture_request_receipts_requester_created_idx
  ON media.picture_request_receipts
    (requester_id, created_at DESC, idempotency_key);

CREATE TABLE identity.web_password (
  user_id BIGINT NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE assistant.ai_user_affection (
  user_id BIGINT NOT NULL PRIMARY KEY,
  affection INT NOT NULL DEFAULT 0,
  impression VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_user_affection_user
    FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE assistant.ai_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  run_at TIMESTAMP NOT NULL,
  trigger_reason VARCHAR(200) NOT NULL,
  context TEXT NULL,
  prompt TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','executing','executed','cancelled','failed')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  executed_at TIMESTAMP NULL DEFAULT NULL,
  error TEXT NULL,
  recurrence_unit TEXT NOT NULL DEFAULT 'none'
    CHECK (recurrence_unit IN ('none','minute','hour','day')),
  recurrence_interval INT NOT NULL DEFAULT 1,
  last_run_at TIMESTAMP NULL DEFAULT NULL,
  claim_token UUID NULL,
  lease_expires_at TIMESTAMP NULL
);

CREATE INDEX idx_ai_schedules_user_status
  ON assistant.ai_schedules (user_id, status);
CREATE INDEX idx_ai_schedules_run
  ON assistant.ai_schedules (status, run_at);
CREATE INDEX idx_ai_schedules_lease
  ON assistant.ai_schedules (status, lease_expires_at);

CREATE TABLE assistant.tool_agent_steps (
  turn_id UUID NOT NULL
    REFERENCES conversation.conversation_turns(turn_id) ON DELETE CASCADE,
  step_no SMALLINT NOT NULL CHECK (step_no BETWEEN 0 AND 32),
  request_hash CHAR(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  route_key VARCHAR(512) NOT NULL CHECK (char_length(btrim(route_key)) > 0),
  response JSONB NOT NULL CHECK (jsonb_typeof(response) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (turn_id, step_no)
);

CREATE TABLE assistant.tool_effect_receipts (
  turn_id UUID NOT NULL
    REFERENCES conversation.conversation_turns(turn_id) ON DELETE CASCADE,
  invocation_id VARCHAR(128) NOT NULL
    CHECK (char_length(btrim(invocation_id)) > 0),
  effect_kind VARCHAR(100) NOT NULL
    CHECK (char_length(btrim(effect_kind)) > 0),
  tool_name VARCHAR(100) NOT NULL
    CHECK (char_length(btrim(tool_name)) > 0),
  provider_call_id VARCHAR(512) NOT NULL
    CHECK (char_length(btrim(provider_call_id)) > 0),
  request_hash CHAR(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  request JSONB NOT NULL CHECK (jsonb_typeof(request) = 'object'),
  mutating BOOLEAN NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'succeeded', 'failed_final')),
  result JSONB,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  PRIMARY KEY (turn_id, invocation_id, effect_kind),
  CHECK (
    (status = 'processing') =
    (claim_token IS NOT NULL AND lease_expires_at IS NOT NULL)
  ),
  CHECK (
    (status = 'succeeded') =
    (result IS NOT NULL AND completed_at IS NOT NULL)
  )
);

CREATE INDEX tool_effect_receipts_recovery_idx
  ON assistant.tool_effect_receipts (lease_expires_at, turn_id, invocation_id)
  WHERE status = 'processing';

CREATE INDEX tool_effect_receipts_kind_created_idx
  ON assistant.tool_effect_receipts (effect_kind, created_at, turn_id);

CREATE TABLE assistant.billing_reservations (
  turn_id UUID PRIMARY KEY
    REFERENCES conversation.conversation_turns(turn_id) ON DELETE RESTRICT,
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  cost SMALLINT NOT NULL CHECK (cost > 0),
  free_reserved SMALLINT,
  paid_reserved SMALLINT,
  pool_contribution NUMERIC(20, 2) NOT NULL
    CHECK (pool_contribution > 0),
  status TEXT NOT NULL CHECK (status IN ('reserved', 'settled', 'released')),
  reserved_at TIMESTAMPTZ NOT NULL,
  settled_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  legacy_eager BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT assistant_billing_native_split_ck CHECK (
    (
      NOT legacy_eager
      AND free_reserved IS NOT NULL
      AND paid_reserved IS NOT NULL
      AND free_reserved >= 0
      AND paid_reserved >= 0
      AND free_reserved + paid_reserved = cost
    ) OR (
      legacy_eager
      AND free_reserved IS NULL
      AND paid_reserved IS NULL
      AND status = 'settled'
    )
  ),
  CONSTRAINT assistant_billing_terminal_shape_ck CHECK (
    (status = 'reserved' AND settled_at IS NULL AND released_at IS NULL)
    OR (status = 'settled' AND settled_at IS NOT NULL AND released_at IS NULL)
    OR (status = 'released' AND settled_at IS NULL AND released_at IS NOT NULL)
  ),
  CONSTRAINT assistant_billing_time_order_ck CHECK (
    (settled_at IS NULL OR settled_at >= reserved_at)
    AND (released_at IS NULL OR released_at >= reserved_at)
  )
);

CREATE INDEX assistant_billing_reservations_user_reserved_idx
  ON assistant.billing_reservations (user_id, reserved_at, turn_id)
  WHERE status = 'reserved';

CREATE TABLE economy.user_lottery (
  user_id BIGINT NOT NULL PRIMARY KEY,
  last_lottery_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE economy.user_task (
  user_id BIGINT NOT NULL,
  task_id INT NOT NULL,
  completed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, task_id)
);

CREATE TABLE economy.user_stakes (
  user_id BIGINT NOT NULL PRIMARY KEY,
  stake_amount INT NOT NULL,
  stake_time TIMESTAMP NOT NULL,
  last_reward_time TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE economy.stake_reward_pool (
  id SMALLINT NOT NULL PRIMARY KEY,
  balance DECIMAL(20,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE economy.stake_pool_postings (
  posting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pool_id SMALLINT NOT NULL,
  idempotency_key VARCHAR(200) NOT NULL UNIQUE
    CHECK (char_length(btrim(idempotency_key)) > 0),
  delta NUMERIC(20, 2) NOT NULL CHECK (delta <> 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX stake_pool_postings_pool_created_idx
  ON economy.stake_pool_postings (pool_id, created_at, posting_id);

CREATE TABLE economy.operation_receipts (
  idempotency_key VARCHAR(200) PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) > 0),
  operation_kind VARCHAR(80) NOT NULL
    CHECK (char_length(btrim(operation_kind)) > 0),
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  result JSONB NOT NULL CHECK (jsonb_typeof(result) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX operation_receipts_user_created_idx
  ON economy.operation_receipts (user_id, created_at);

CREATE TABLE economy.redemption_codes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL UNIQUE,
  amount INT NOT NULL,
  is_used BOOLEAN NOT NULL DEFAULT FALSE,
  used_by BIGINT DEFAULT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (used_by) REFERENCES identity.users(id) ON DELETE SET NULL
);

CREATE TABLE economy.user_invitations (
  invited_user_id BIGINT NOT NULL,
  referrer_id BIGINT NOT NULL,
  invitation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reward_claimed BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (invited_user_id),
  FOREIGN KEY (invited_user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (referrer_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE economy.user_checkin (
  user_id BIGINT NOT NULL PRIMARY KEY,
  last_checkin_date DATE NOT NULL,
  consecutive_days INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE economy.shop_pity (
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  game TEXT NOT NULL CHECK (game IN ('scratch', 'huanle')),
  business_date DATE NOT NULL,
  misses INTEGER NOT NULL DEFAULT 0 CHECK (misses >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, game)
);

CREATE TABLE economy.kindness_gifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL,
  amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kindness_recipient_created
  ON economy.kindness_gifts (recipient_id, created_at);

CREATE TABLE economy.user_give_daily (
  user_id BIGINT NOT NULL,
  give_date DATE NOT NULL,
  give_count INT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, give_date)
);

CREATE TABLE moderation.group_verification (
  group_id BIGINT NOT NULL PRIMARY KEY,
  group_name TEXT NOT NULL
);

CREATE TABLE moderation.verification_tasks (
  user_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  message_id BIGINT,
  expire_time TIMESTAMPTZ NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  member_name TEXT NOT NULL DEFAULT '用户',
  version BIGINT NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ,
  claim_token UUID,
  lease_expires_at TIMESTAMPTZ,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT verification_tasks_status_ck CHECK (status IN (
      'creating', 'pending', 'passing', 'expiring', 'cancelling',
      'passed', 'expired', 'cancelled'
    )),
  CONSTRAINT verification_tasks_version_ck CHECK (version >= 0),
  CONSTRAINT verification_tasks_attempt_count_ck CHECK (attempt_count >= 0),
  CONSTRAINT verification_tasks_token_hash_ck CHECK (
    token_hash ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT verification_tasks_lease_ck CHECK (
    (claim_token IS NULL) = (lease_expires_at IS NULL)
  ),
  CONSTRAINT verification_tasks_message_ck CHECK (
    message_id IS NOT NULL OR status IN ('creating', 'cancelling', 'cancelled')
  ),
  CONSTRAINT verification_tasks_schedule_ck CHECK (
    (status IN ('passed', 'expired', 'cancelled')) = (next_attempt_at IS NULL)
  ),
  PRIMARY KEY (user_id, group_id)
);

CREATE INDEX verification_tasks_ready_idx
  ON moderation.verification_tasks (next_attempt_at, group_id, user_id)
  WHERE status IN ('creating', 'pending', 'passing', 'expiring', 'cancelling')
    AND claim_token IS NULL;

CREATE INDEX verification_tasks_expired_lease_idx
  ON moderation.verification_tasks (lease_expires_at, group_id, user_id)
  WHERE claim_token IS NOT NULL;

CREATE TABLE moderation.group_keywords (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  response TEXT NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_keyword_unique UNIQUE (group_id, keyword)
);

CREATE TABLE moderation.group_spam_control (
  group_id BIGINT NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  enabled_by BIGINT,
  enabled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  block_links BOOLEAN NOT NULL DEFAULT FALSE,
  block_mentions BOOLEAN NOT NULL DEFAULT FALSE,
  exempt_administrators BOOLEAN NOT NULL DEFAULT TRUE,
  rule_merge_mode TEXT NOT NULL DEFAULT 'override_global'
    CHECK (rule_merge_mode IN ('global_only', 'extend_global', 'override_global')),
  failure_mode TEXT NOT NULL DEFAULT 'fail_closed'
    CHECK (failure_mode IN ('fail_open', 'fail_closed')),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE moderation.group_spam_keywords (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  is_regex BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_spam_keyword_unique UNIQUE (group_id, keyword)
);

CREATE TABLE moderation.member_warning_windows (
  chat_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  window_started_at TIMESTAMPTZ NOT NULL,
  warning_count INTEGER NOT NULL CHECK (warning_count > 0),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE moderation.effects (
  effect_id UUID PRIMARY KEY,
  source_update_id BIGINT NOT NULL CHECK (source_update_id >= 0),
  kind TEXT NOT NULL CHECK (kind IN ('spam_enforcement', 'keyword_reply')),
  chat_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL CHECK (message_id >= 0),
  status TEXT NOT NULL
    CHECK (status IN ('pending', 'message_deleted', 'delivered', 'failed')),
  warning_count INTEGER NULL CHECK (warning_count IS NULL OR warning_count > 0),
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT moderation_effect_source_unique UNIQUE (source_update_id, kind),
  CONSTRAINT moderation_effect_warning_shape CHECK (
    (kind = 'spam_enforcement' AND (warning_count IS NOT NULL OR status = 'pending'))
    OR (kind = 'keyword_reply' AND warning_count IS NULL)
  )
);

CREATE INDEX moderation_effect_group_updated_idx
  ON moderation.effects (chat_id, updated_at);

CREATE TABLE moderation.reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL CHECK (message_id >= 0),
  reporter_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT moderation_report_idempotency
    UNIQUE (chat_id, message_id, reporter_id)
);

CREATE INDEX moderation_reports_message_idx
  ON moderation.reports (chat_id, message_id, created_at);

CREATE TABLE moderation.toggle_command_receipts (
  idempotency_key VARCHAR(200) PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) > 0),
  operation_kind VARCHAR(80) NOT NULL CHECK (
    operation_kind IN ('spam_control', 'member_verification')
  ),
  chat_id BIGINT NOT NULL,
  actor_id BIGINT NOT NULL,
  request_payload JSONB NOT NULL CHECK (
    jsonb_typeof(request_payload) = 'object'
  ),
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX toggle_command_receipts_chat_created_idx
  ON moderation.toggle_command_receipts
    (operation_kind, chat_id, created_at, idempotency_key);

CREATE TABLE crypto.user_btc_predictions (
  user_id BIGINT NOT NULL PRIMARY KEY,
  predict_type VARCHAR(10) NOT NULL,
  amount INT NOT NULL,
  start_price DECIMAL(20,8) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  request_key TEXT NOT NULL,
  chat_id BIGINT NOT NULL,
  end_price DECIMAL(20,8),
  is_correct BOOLEAN,
  reward INTEGER,
  settled_at TIMESTAMPTZ,
  CONSTRAINT user_btc_predictions_request_key_ck
    CHECK (char_length(btrim(request_key)) BETWEEN 1 AND 512),
  CONSTRAINT user_btc_predictions_request_key_uk UNIQUE (request_key),
  CONSTRAINT user_btc_predictions_reward_ck
    CHECK (reward IS NULL OR reward >= 0),
  CONSTRAINT user_btc_predictions_outcome_shape_ck CHECK (
    (
      end_price IS NULL
      AND is_correct IS NULL
      AND reward IS NULL
      AND settled_at IS NULL
    )
    OR
    (
      end_price IS NOT NULL
      AND end_price > 0
      AND is_correct IS NOT NULL
      AND reward IS NOT NULL
      AND settled_at IS NOT NULL
    )
  ),
  CONSTRAINT user_btc_predictions_pending_outcome_ck CHECK (
    is_completed
    OR (
      end_price IS NULL
      AND is_correct IS NULL
      AND reward IS NULL
      AND settled_at IS NULL
    )
  )
);

CREATE INDEX idx_user_btc_predictions_due
  ON crypto.user_btc_predictions (end_time, user_id)
  WHERE is_completed = FALSE;

CREATE TABLE crypto.token_swap_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username VARCHAR(255) NOT NULL,
  wallet_address VARCHAR(50) NOT NULL,
  amount INT NOT NULL,
  request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'pending',
  idempotency_key TEXT NOT NULL,
  CONSTRAINT token_swap_request_idempotency_key_ck
    CHECK (char_length(btrim(idempotency_key)) BETWEEN 1 AND 512),
  CONSTRAINT token_swap_request_idempotency_key_uk UNIQUE (idempotency_key)
);

CREATE UNIQUE INDEX uq_token_swap_requests_one_pending_per_user
  ON crypto.token_swap_requests (user_id)
  WHERE status = 'pending';

CREATE TABLE crypto.swap_request_conflicts (
  request_id INTEGER PRIMARY KEY
    REFERENCES crypto.token_swap_requests(id) ON DELETE RESTRICT,
  canonical_request_id INTEGER NOT NULL
    REFERENCES crypto.token_swap_requests(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (request_id <> canonical_request_id)
);

CREATE TABLE crypto.operation_receipts (
  idempotency_key TEXT PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) BETWEEN 1 AND 512),
  operation_kind TEXT NOT NULL
    CHECK (char_length(btrim(operation_kind)) BETWEEN 1 AND 100),
  actor_id BIGINT NOT NULL,
  result JSONB NOT NULL CHECK (jsonb_typeof(result) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crypto.group_chart_tokens (
  group_id BIGINT NOT NULL PRIMARY KEY,
  chain VARCHAR(20) NOT NULL,
  ca VARCHAR(100) NOT NULL,
  set_by BIGINT NOT NULL,
  buy_alert_threshold FLOAT NULL,
  set_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.user_omikuji (
  user_id BIGINT NOT NULL,
  fortune_date DATE NOT NULL,
  fortune VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_omikuji_fortune_ck CHECK (
    fortune IN ('大吉', '中吉', '小吉', '末吉', '凶', '大凶')
  ),
  PRIMARY KEY (user_id, fortune_date)
);

CREATE TABLE game.migration_0027_omikuji_repairs (
  user_id BIGINT NOT NULL,
  fortune_date DATE NOT NULL,
  fortune VARCHAR(10) NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, fortune_date),
  FOREIGN KEY (user_id, fortune_date)
    REFERENCES game.user_omikuji(user_id, fortune_date) ON DELETE CASCADE
);

CREATE TABLE game.rpg_characters (
  character_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL,
  level INT NOT NULL DEFAULT 1,
  hp INT NOT NULL DEFAULT 10,
  max_hp INT NOT NULL DEFAULT 10,
  atk INT NOT NULL DEFAULT 2,
  matk INT NOT NULL DEFAULT 0,
  def INT NOT NULL DEFAULT 1,
  experience BIGINT NOT NULL DEFAULT 0,
  allow_battle BOOLEAN NOT NULL DEFAULT TRUE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT rpg_characters_version_ck CHECK (version >= 0),
  CONSTRAINT rpg_characters_stats_ck CHECK (
    level > 0
    AND max_hp > 0
    AND hp BETWEEN 0 AND max_hp
    AND atk >= 0
    AND matk >= 0
    AND def >= 0
    AND experience >= 0
  ),
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE game.migration_0027_character_repairs (
  character_id INTEGER PRIMARY KEY
    REFERENCES game.rpg_characters(character_id) ON DELETE CASCADE,
  level INTEGER,
  hp INTEGER,
  max_hp INTEGER,
  atk INTEGER,
  matk INTEGER,
  def INTEGER,
  experience BIGINT,
  allow_battle BOOLEAN,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_equipment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type TEXT NOT NULL
    CHECK (type IN ('weapon', 'offhand', 'armor', 'treasure1', 'treasure2')),
  atk_bonus INT DEFAULT 0,
  def_bonus INT DEFAULT 0,
  hp_bonus INT DEFAULT 0,
  matk_bonus INT DEFAULT 0,
  description TEXT,
  price INT NOT NULL,
  rarity INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type TEXT NOT NULL
    CHECK (type IN ('consumable', 'material', 'quest')),
  effect TEXT,
  description TEXT,
  price INT NOT NULL,
  use_limit INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_player_equipment (
  user_id BIGINT NOT NULL PRIMARY KEY,
  weapon_id INT DEFAULT NULL,
  offhand_id INT DEFAULT NULL,
  armor_id INT DEFAULT NULL,
  treasure1_id INT DEFAULT NULL,
  treasure2_id INT DEFAULT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT rpg_player_equipment_version_ck CHECK (version >= 0),
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (weapon_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (offhand_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (armor_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (treasure1_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (treasure2_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL
);

CREATE TABLE game.rpg_player_inventory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT rpg_player_inventory_quantity_ck CHECK (quantity > 0),
  CONSTRAINT rpg_player_inventory_version_ck CHECK (version >= 0),
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES game.rpg_items(id) ON DELETE CASCADE,
  CONSTRAINT rpg_player_inventory_unique UNIQUE (user_id, item_id)
);

CREATE TABLE game.migration_0027_inventory_repairs (
  inventory_id INTEGER PRIMARY KEY
    REFERENCES game.rpg_player_inventory(id) ON DELETE CASCADE,
  quantity INTEGER,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_shop (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type TEXT NOT NULL CHECK (item_type IN ('equipment', 'item')),
  item_id INT NOT NULL,
  price INT NOT NULL,
  stock INT DEFAULT -1,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT rpg_shop_item_unique UNIQUE (item_type, item_id)
);

CREATE INDEX idx_rpg_shop_item ON game.rpg_shop (item_type, item_id);

CREATE TABLE game.rpg_player_equipment_stats (
  user_id BIGINT NOT NULL PRIMARY KEY,
  total_atk_bonus INT DEFAULT 0,
  total_def_bonus INT DEFAULT 0,
  total_hp_bonus INT DEFAULT 0,
  total_matk_bonus INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE game.game_sessions (
  session_id UUID PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('gamble', 'sicbo')),
  scope_key TEXT NOT NULL
    CHECK (char_length(btrim(scope_key)) BETWEEN 1 AND 255),
  owner_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  chat_id BIGINT NOT NULL CHECK (chat_id <> 0),
  message_id BIGINT NOT NULL CHECK (message_id > 0),
  state JSONB NOT NULL CHECK (jsonb_typeof(state) = 'object'),
  status TEXT NOT NULL CHECK (
    status IN ('active', 'settled', 'cancelled', 'expired')
  ),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  settled_at TIMESTAMPTZ,
  notification_enqueued_at TIMESTAMPTZ,
  CONSTRAINT game_sessions_time_order_ck CHECK (
    expires_at > created_at AND updated_at >= created_at
  ),
  CONSTRAINT game_sessions_settlement_shape_ck CHECK (
    (status = 'settled') = (settled_at IS NOT NULL)
  ),
  CONSTRAINT game_sessions_notification_shape_ck CHECK (
    notification_enqueued_at IS NULL OR status = 'settled'
  )
);

CREATE UNIQUE INDEX uq_game_sessions_active_scope
  ON game.game_sessions (kind, scope_key)
  WHERE status = 'active';
CREATE INDEX idx_game_sessions_due
  ON game.game_sessions (expires_at, session_id)
  WHERE status = 'active';
CREATE INDEX idx_game_sessions_unnotified_gamble
  ON game.game_sessions (settled_at, session_id)
  WHERE kind = 'gamble'
    AND status = 'settled'
    AND notification_enqueued_at IS NULL;

CREATE TABLE game.game_receipts (
  idempotency_key TEXT PRIMARY KEY
    CHECK (char_length(btrim(idempotency_key)) BETWEEN 1 AND 255),
  operation TEXT NOT NULL CHECK (
    operation IN (
      'gamble.open', 'gamble.bet', 'sicbo.open', 'sicbo.select',
      'sicbo.cancel', 'sicbo.play', 'omikuji.draw', 'rpg.allow',
      'rpg.heal', 'rpg.monster_battle', 'rpg.player_battle',
      'rpg.equip', 'rpg.unequip', 'rpg.use_item',
      'rpg.add_item', 'rpg.remove_item'
    )
  ),
  user_id BIGINT NOT NULL CHECK (user_id > 0),
  result JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT game_receipts_result_schema_ck CHECK (
    jsonb_typeof(result) = 'object'
    AND result ? 'schema'
    AND result ? 'code'
    AND result -> 'schema' = '1'::JSONB
    AND jsonb_typeof(result -> 'code') = 'string'
  )
);

CREATE TABLE game.rpg_battle_cooldowns (
  user_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE CASCADE,
  battle_kind TEXT NOT NULL CHECK (battle_kind IN ('player', 'monster')),
  last_battle_at TIMESTAMPTZ,
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  PRIMARY KEY (user_id, battle_kind)
);

CREATE TABLE game.rps_sessions (
  game_id TEXT PRIMARY KEY CHECK (game_id ~ '^[A-Za-z0-9_-]{8,24}$'),
  status TEXT NOT NULL CHECK (
    status IN ('waiting', 'choosing', 'finished', 'cancelled', 'expired', 'invalidated')
  ),
  version BIGINT NOT NULL CHECK (version >= 0),
  player_one_id BIGINT NOT NULL
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  player_two_id BIGINT
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  state JSONB NOT NULL CHECK (
    jsonb_typeof(state) = 'object'
    AND state -> 'schema' = '1'::JSONB
  ),
  delivery JSONB CHECK (
    delivery IS NULL OR jsonb_typeof(delivery) = 'object'
  ),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  terminal_at TIMESTAMPTZ,
  CONSTRAINT rps_sessions_players_ck CHECK (
    player_two_id IS NULL OR player_two_id <> player_one_id
  ),
  CONSTRAINT rps_sessions_time_ck CHECK (
    expires_at > created_at
    AND updated_at >= created_at
    AND (terminal_at IS NULL OR terminal_at >= created_at)
  ),
  CONSTRAINT rps_sessions_terminal_ck CHECK (
    (status IN ('waiting', 'choosing')) = (terminal_at IS NULL)
  ),
  CONSTRAINT rps_sessions_phase_ck CHECK (
    (status = 'waiting' AND version = 0 AND player_two_id IS NULL)
    OR (status = 'choosing' AND version >= 1 AND player_two_id IS NOT NULL)
    OR (status = 'finished' AND version >= 2 AND player_two_id IS NOT NULL)
    OR (status = 'cancelled')
    OR (status IN ('expired', 'invalidated') AND player_two_id IS NULL)
  )
);

CREATE UNIQUE INDEX uq_rps_single_waiting_room
  ON game.rps_sessions (status)
  WHERE status = 'waiting';

CREATE INDEX idx_rps_sessions_due
  ON game.rps_sessions (expires_at, game_id)
  WHERE status IN ('waiting', 'choosing');

CREATE INDEX idx_rps_sessions_terminal
  ON game.rps_sessions (terminal_at DESC, game_id)
  WHERE terminal_at IS NOT NULL;

CREATE TABLE game.rps_player_slots (
  user_id BIGINT PRIMARY KEY
    REFERENCES identity.users(id) ON DELETE RESTRICT,
  game_id TEXT NOT NULL
    REFERENCES game.rps_sessions(game_id) ON DELETE CASCADE
);

CREATE INDEX idx_rps_player_slots_game
  ON game.rps_player_slots (game_id);

CREATE TABLE observability.resources (
  resource_id UUID PRIMARY KEY,
  service_name VARCHAR(255) NOT NULL CHECK (char_length(btrim(service_name)) > 0),
  service_version VARCHAR(100) NOT NULL CHECK (char_length(btrim(service_version)) > 0),
  deployment_environment VARCHAR(100) NOT NULL
    CHECK (char_length(btrim(deployment_environment)) > 0),
  service_instance_id VARCHAR(255) NOT NULL
    CHECK (char_length(btrim(service_instance_id)) > 0),
  started_at TIMESTAMPTZ NOT NULL,
  stopped_at TIMESTAMPTZ,
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  CONSTRAINT observability_resources_time_ck CHECK (
    stopped_at IS NULL OR stopped_at >= started_at
  )
);

CREATE INDEX observability_resources_service_started_idx
  ON observability.resources (service_name, started_at DESC);

CREATE TABLE observability.log_records (
  occurred_at TIMESTAMPTZ NOT NULL,
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  observed_at TIMESTAMPTZ NOT NULL,
  resource_id UUID NOT NULL REFERENCES observability.resources(resource_id),
  trace_id BYTEA,
  span_id BYTEA,
  severity_number SMALLINT NOT NULL CHECK (severity_number BETWEEN 1 AND 24),
  severity_text VARCHAR(16) NOT NULL,
  logger_name VARCHAR(255) NOT NULL,
  event_name VARCHAR(255),
  body VARCHAR(16384) NOT NULL,
  exception_type VARCHAR(255),
  exception_message VARCHAR(4096),
  exception_stack VARCHAR(16384),
  turn_id UUID,
  update_id BIGINT,
  activity_id UUID,
  outbound_message_id UUID,
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  PRIMARY KEY (occurred_at, log_id),
  CONSTRAINT observability_log_trace_id_ck CHECK (
    trace_id IS NULL OR octet_length(trace_id) = 16
  ),
  CONSTRAINT observability_log_span_id_ck CHECK (
    span_id IS NULL OR octet_length(span_id) = 8
  ),
  CONSTRAINT observability_log_context_ck CHECK (
    span_id IS NULL OR trace_id IS NOT NULL
  )
) PARTITION BY RANGE (occurred_at);

CREATE INDEX observability_log_trace_idx
  ON observability.log_records (trace_id, occurred_at DESC)
  WHERE trace_id IS NOT NULL;
CREATE INDEX observability_log_event_idx
  ON observability.log_records (event_name, occurred_at DESC)
  WHERE event_name IS NOT NULL;
CREATE INDEX observability_log_error_idx
  ON observability.log_records (occurred_at DESC, severity_number)
  WHERE severity_number >= 13;
CREATE INDEX observability_log_turn_idx
  ON observability.log_records (turn_id, occurred_at DESC)
  WHERE turn_id IS NOT NULL;

CREATE TABLE observability.spans (
  started_at TIMESTAMPTZ NOT NULL,
  trace_id BYTEA NOT NULL CHECK (octet_length(trace_id) = 16),
  span_id BYTEA NOT NULL CHECK (octet_length(span_id) = 8),
  parent_span_id BYTEA CHECK (
    parent_span_id IS NULL OR octet_length(parent_span_id) = 8
  ),
  resource_id UUID NOT NULL REFERENCES observability.resources(resource_id),
  span_name VARCHAR(255) NOT NULL,
  span_kind VARCHAR(16) NOT NULL CHECK (
    span_kind IN ('internal', 'server', 'client', 'producer', 'consumer')
  ),
  ended_at TIMESTAMPTZ NOT NULL,
  duration_ns BIGINT NOT NULL CHECK (duration_ns >= 0),
  status_code VARCHAR(16) NOT NULL CHECK (
    status_code IN ('unset', 'ok', 'error')
  ),
  status_message VARCHAR(2000),
  turn_id UUID,
  update_id BIGINT,
  activity_id UUID,
  outbound_message_id UUID,
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  PRIMARY KEY (started_at, trace_id, span_id),
  CONSTRAINT observability_spans_time_ck CHECK (ended_at >= started_at)
) PARTITION BY RANGE (started_at);

CREATE INDEX observability_spans_trace_idx
  ON observability.spans (trace_id, started_at);
CREATE INDEX observability_spans_name_started_idx
  ON observability.spans (span_name, started_at DESC);
CREATE INDEX observability_spans_error_idx
  ON observability.spans (started_at DESC, span_name)
  WHERE status_code = 'error';
CREATE INDEX observability_spans_turn_idx
  ON observability.spans (turn_id, started_at)
  WHERE turn_id IS NOT NULL;

CREATE TABLE observability.metric_points (
  observed_at TIMESTAMPTZ NOT NULL,
  metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  resource_id UUID NOT NULL REFERENCES observability.resources(resource_id),
  metric_name VARCHAR(255) NOT NULL,
  metric_kind VARCHAR(16) NOT NULL CHECK (metric_kind IN ('counter', 'gauge')),
  value DOUBLE PRECISION NOT NULL CHECK (
    value NOT IN (
      'NaN'::DOUBLE PRECISION,
      'Infinity'::DOUBLE PRECISION,
      '-Infinity'::DOUBLE PRECISION
    )
  ),
  unit VARCHAR(63) NOT NULL,
  exemplar_trace_id BYTEA CHECK (
    exemplar_trace_id IS NULL OR octet_length(exemplar_trace_id) = 16
  ),
  attributes JSONB NOT NULL DEFAULT '{}'::JSONB
    CHECK (jsonb_typeof(attributes) = 'object'),
  PRIMARY KEY (observed_at, metric_id),
  CONSTRAINT observability_metric_counter_ck CHECK (
    metric_kind <> 'counter' OR value >= 0
  )
) PARTITION BY RANGE (observed_at);

CREATE INDEX observability_metric_name_time_idx
  ON observability.metric_points (metric_name, observed_at DESC);
CREATE INDEX observability_metric_exemplar_idx
  ON observability.metric_points (exemplar_trace_id, observed_at DESC)
  WHERE exemplar_trace_id IS NOT NULL;

CREATE FUNCTION observability.ensure_daily_partitions(partition_day DATE)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  lower_bound TIMESTAMPTZ := partition_day::TIMESTAMP AT TIME ZONE 'UTC';
  upper_bound TIMESTAMPTZ := (partition_day + 1)::TIMESTAMP AT TIME ZONE 'UTC';
  suffix TEXT := to_char(partition_day, 'YYYYMMDD');
BEGIN
  IF partition_day < DATE '2020-01-01'
     OR partition_day > (CURRENT_DATE + 366) THEN
    RAISE EXCEPTION 'observability partition day out of allowed range: %', partition_day;
  END IF;

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS observability.%I PARTITION OF observability.log_records FOR VALUES FROM (%L) TO (%L)',
    'log_records_' || suffix, lower_bound, upper_bound
  );
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS observability.%I PARTITION OF observability.spans FOR VALUES FROM (%L) TO (%L)',
    'spans_' || suffix, lower_bound, upper_bound
  );
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS observability.%I PARTITION OF observability.metric_points FOR VALUES FROM (%L) TO (%L)',
    'metric_points_' || suffix, lower_bound, upper_bound
  );
END;
$$;

CREATE FUNCTION observability.drop_partitions_before(retain_from DATE)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  child RECORD;
  dropped INTEGER := 0;
  partition_day DATE;
BEGIN
  IF retain_from < DATE '2020-01-01' OR retain_from > CURRENT_DATE THEN
    RAISE EXCEPTION 'observability retention boundary out of allowed range: %', retain_from;
  END IF;

  FOR child IN
    SELECT child_namespace.nspname AS schema_name,
           child_class.relname AS table_name
    FROM pg_inherits
    JOIN pg_class AS parent_class ON parent_class.oid = inhparent
    JOIN pg_namespace AS parent_namespace
      ON parent_namespace.oid = parent_class.relnamespace
    JOIN pg_class AS child_class ON child_class.oid = inhrelid
    JOIN pg_namespace AS child_namespace
      ON child_namespace.oid = child_class.relnamespace
    WHERE parent_namespace.nspname = 'observability'
      AND parent_class.relname IN ('log_records', 'spans', 'metric_points')
  LOOP
    IF child.table_name ~ '^[a-z_]+_[0-9]{8}$' THEN
      partition_day := to_date(right(child.table_name, 8), 'YYYYMMDD');
      IF partition_day < retain_from THEN
        EXECUTE format('DROP TABLE %I.%I', child.schema_name, child.table_name);
        dropped := dropped + 1;
      END IF;
    END IF;
  END LOOP;
  RETURN dropped;
END;
$$;

CREATE VIEW observability.pipeline_health AS
SELECT 'inbox'::TEXT AS stage,
       count(*) FILTER (WHERE status = 'pending') AS pending_count,
       count(*) FILTER (WHERE status = 'processing') AS processing_count,
       count(*) FILTER (WHERE status = 'retry_wait') AS retry_count,
       count(*) FILTER (WHERE status = 'failed_final') AS failed_final_count,
       min(next_attempt_at) FILTER (
         WHERE status IN ('pending', 'retry_wait')
       ) AS oldest_ready_at,
       count(*) FILTER (
         WHERE status = 'processing' AND lease_expires_at < CURRENT_TIMESTAMP
       ) AS expired_lease_count
FROM conversation.inbound_updates
UNION ALL
SELECT 'inference',
       count(*) FILTER (WHERE status = 'pending'),
       count(*) FILTER (WHERE status = 'processing'),
       count(*) FILTER (WHERE status = 'retry'),
       count(*) FILTER (WHERE status = 'failed'),
       min(next_attempt_at) FILTER (WHERE status IN ('pending', 'retry')),
       count(*) FILTER (
         WHERE status = 'processing' AND lease_expires_at < CURRENT_TIMESTAMP
       )
FROM conversation.inference_activities
UNION ALL
SELECT 'outbox',
       count(*) FILTER (WHERE status = 'pending'),
       count(*) FILTER (WHERE status = 'processing'),
       count(*) FILTER (WHERE status = 'retry_wait'),
       count(*) FILTER (WHERE status = 'failed_final'),
       min(next_attempt_at) FILTER (
         WHERE status IN ('pending', 'retry_wait')
       ),
       count(*) FILTER (
         WHERE status = 'processing' AND lease_expires_at < CURRENT_TIMESTAMP
       )
FROM conversation.outbound_messages;

CREATE VIEW observability.turn_latency AS
SELECT turn.turn_id,
       turn.source_update_id AS update_id,
       turn.state,
       inbound.received_at,
       turn.created_at AS turn_created_at,
       activity.created_at AS inference_created_at,
       activity.completed_at AS inference_completed_at,
       delivery.first_created_at AS delivery_created_at,
       delivery.last_delivered_at AS delivered_at,
       EXTRACT(EPOCH FROM (turn.created_at - inbound.received_at)) * 1000
         AS ingress_to_turn_ms,
       EXTRACT(EPOCH FROM (activity.completed_at - activity.created_at)) * 1000
         AS inference_total_ms,
       EXTRACT(EPOCH FROM (delivery.last_delivered_at - delivery.first_created_at)) * 1000
         AS delivery_total_ms,
       EXTRACT(EPOCH FROM (turn.completed_at - inbound.received_at)) * 1000
         AS end_to_end_ms,
       turn.inference_attempts,
       turn.delivery_attempts
FROM conversation.conversation_turns AS turn
LEFT JOIN conversation.inbound_updates AS inbound
  ON inbound.update_id = turn.source_update_id
LEFT JOIN conversation.inference_activities AS activity
  ON activity.turn_id = turn.turn_id
LEFT JOIN LATERAL (
  SELECT min(outbound.created_at) AS first_created_at,
         max(outbound.delivered_at) AS last_delivered_at
  FROM conversation.outbound_messages AS outbound
  WHERE outbound.turn_id = turn.turn_id
) AS delivery ON TRUE;
