"""@brief 个人 RPG 应用命令与结果 / Personal-RPG application commands and results."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from enum import StrEnum
from uuid import UUID

from fogmoe_bot.domain.personal_rpg._validation import (
    normalize_day,
    normalize_idempotency_key,
    normalize_instant,
    normalize_text,
)
from fogmoe_bot.domain.personal_rpg.catalog import (
    CraftingRecipe,
    RecipeCode,
    recipe_for,
)
from fogmoe_bot.domain.personal_rpg.character import PersonalCharacter
from fogmoe_bot.domain.personal_rpg.exploration import (
    DailyExploration,
    ExplorationRoute,
    create_daily_exploration,
)
from fogmoe_bot.domain.personal_rpg.profile import PersonalRpgProfile
from fogmoe_bot.domain.world.scope import PersonalScope


class PersonalRpgCode(StrEnum):
    """@brief 个人 RPG 用例结果代码 / Personal-RPG use-case result codes."""

    SUCCESS = "success"
    """@brief 操作已成功提交 / Operation committed successfully."""

    NOT_REGISTERED = "not_registered"
    """@brief 个人角色尚未创建 / Personal character has not been created."""

    ALREADY_EXISTS = "already_exists"
    """@brief 个人角色已经存在 / Personal character already exists."""

    ALREADY_EXPLORED = "already_explored"
    """@brief 当日探索已经结算 / Daily exploration has already settled."""

    MATERIALS_INSUFFICIENT = "materials_insufficient"
    """@brief 制作所需材料不足 / Crafting materials are insufficient."""

    ALREADY_COLLECTED = "already_collected"
    """@brief 配方产物已经收录到图鉴 / Recipe output is already recorded in the compendium."""

    CONFLICT = "conflict"
    """@brief 幂等键或乐观并发发生冲突 / Idempotency or optimistic concurrency conflict."""


@dataclass(frozen=True, slots=True)
class CreatePersonalCharacter:
    """@brief 创建一个只属于私聊个人范围的角色 / Create one character owned only by a private personal scope.

    @param scope 角色所属个人范围 / Personal scope owning the character.
    @param name 角色展示名称 / Character display name.
    @param created_at 创建 UTC 时刻 / Creation UTC instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    """

    scope: PersonalScope
    """@brief 角色所属个人范围 / Owning personal scope."""

    name: str
    """@brief 角色展示名称 / Character display name."""

    created_at: datetime
    """@brief 创建 UTC 时刻 / Creation UTC instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证创建角色命令 / Validate the character-creation command.

        @return None / None.
        @raise TypeError 个人范围类型非法时抛出 / Raised when personal scope type is invalid.
        @raise ValueError 名称、时刻或幂等键非法时抛出 / Raised when name, instant, or idempotency key is invalid.
        """

        if not isinstance(self.scope, PersonalScope):
            raise TypeError("Personal RPG character creation must use PersonalScope")
        object.__setattr__(
            self,
            "name",
            normalize_text(
                self.name,
                field="Personal RPG character name",
                minimum_length=1,
                maximum_length=40,
            ),
        )
        object.__setattr__(
            self,
            "created_at",
            normalize_instant(
                self.created_at,
                field="Personal RPG character creation time",
            ),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Personal RPG character creation idempotency key",
            ),
        )

    def profile(self) -> PersonalRpgProfile:
        """@brief 构造空白个人 RPG 进度 / Construct blank personal-RPG progression.

        @return 新角色对应的空白进度聚合 / Blank progression aggregate for the new character.
        """

        return PersonalRpgProfile(PersonalCharacter(scope=self.scope, name=self.name))


@dataclass(frozen=True, slots=True)
class ExploreDaily:
    """@brief 对一个私聊个人角色执行每日探索 / Run daily exploration for one private personal character.

    @param exploration_id 调用方生成的稳定探索标识 / Stable exploration identity generated by caller.
    @param scope 发起探索的个人范围 / Personal scope initiating exploration.
    @param day UTC 业务日 / UTC business day.
    @param route 已选探索路线 / Selected exploration route.
    @param explored_at 执行探索 UTC 时刻 / Exploration UTC instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    """

    exploration_id: UUID
    """@brief 稳定探索标识 / Stable exploration identity."""

    scope: PersonalScope
    """@brief 发起探索的个人范围 / Personal scope initiating exploration."""

    day: date
    """@brief UTC 业务日 / UTC business day."""

    route: ExplorationRoute
    """@brief 已选探索路线 / Selected exploration route."""

    explored_at: datetime
    """@brief 执行探索 UTC 时刻 / Exploration UTC instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证每日探索命令 / Validate the daily-exploration command.

        @return None / None.
        @raise TypeError 标识、范围或路线类型非法时抛出 / Raised when identity, scope, or route type is invalid.
        @raise ValueError 业务日、探索时刻或幂等键非法时抛出 /
            Raised when business day, exploration time, or idempotency key is invalid.
        """

        if not isinstance(self.exploration_id, UUID):
            raise TypeError("Personal RPG exploration ID must be a UUID")
        if not isinstance(self.scope, PersonalScope):
            raise TypeError("Personal RPG exploration must use PersonalScope")
        if not isinstance(self.route, ExplorationRoute):
            raise TypeError("Personal RPG exploration route must be ExplorationRoute")
        normalized_day = normalize_day(self.day, field="Personal RPG exploration day")
        normalized_explored_at = normalize_instant(
            self.explored_at,
            field="Personal RPG exploration time",
        )
        if normalized_explored_at.date() != normalized_day:
            raise ValueError(
                "Personal RPG exploration time must fall on its UTC business day"
            )
        object.__setattr__(self, "day", normalized_day)
        object.__setattr__(self, "explored_at", normalized_explored_at)
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Personal RPG exploration idempotency key",
            ),
        )

    def exploration(self) -> DailyExploration:
        """@brief 构造固定奖励且可审计的探索快照 / Construct a fixed-reward auditable exploration snapshot.

        @return 确定性每日探索 / Deterministic daily exploration.
        """

        return create_daily_exploration(
            exploration_id=self.exploration_id,
            scope=self.scope,
            day=self.day,
            route=self.route,
            explored_at=self.explored_at,
        )


@dataclass(frozen=True, slots=True)
class CraftPersonalRecipe:
    """@brief 使用个人材料制作一个图鉴配方 / Craft one compendium recipe with personal materials.

    @param craft_id 调用方生成的稳定制作标识 / Stable crafting identity generated by caller.
    @param scope 制作者个人范围 / Crafter personal scope.
    @param recipe_code 固定配方编码 / Fixed recipe code.
    @param crafted_at 制作 UTC 时刻 / Crafting UTC instant.
    @param idempotency_key 业务幂等键 / Business idempotency key.
    """

    craft_id: UUID
    """@brief 稳定制作标识 / Stable crafting identity."""

    scope: PersonalScope
    """@brief 制作者个人范围 / Crafter personal scope."""

    recipe_code: RecipeCode
    """@brief 固定配方编码 / Fixed recipe code."""

    crafted_at: datetime
    """@brief 制作 UTC 时刻 / Crafting UTC instant."""

    idempotency_key: str
    """@brief 业务幂等键 / Business idempotency key."""

    def __post_init__(self) -> None:
        """@brief 验证制作配方命令 / Validate the recipe-crafting command.

        @return None / None.
        @raise TypeError 标识、范围或配方编码类型非法时抛出 /
            Raised when identity, scope, or recipe-code type is invalid.
        @raise ValueError 制作时刻或幂等键非法时抛出 /
            Raised when crafting instant or idempotency key is invalid.
        """

        if not isinstance(self.craft_id, UUID):
            raise TypeError("Personal RPG craft ID must be a UUID")
        if not isinstance(self.scope, PersonalScope):
            raise TypeError("Personal RPG crafting must use PersonalScope")
        if not isinstance(self.recipe_code, RecipeCode):
            raise TypeError("Personal RPG crafting must use RecipeCode")
        object.__setattr__(
            self,
            "crafted_at",
            normalize_instant(self.crafted_at, field="Personal RPG crafting time"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            normalize_idempotency_key(
                self.idempotency_key,
                field="Personal RPG crafting idempotency key",
            ),
        )

    def recipe(self) -> CraftingRecipe:
        """@brief 读取被冻结的固定配方 / Load the frozen fixed recipe.

        @return 对应配方快照 / Corresponding recipe snapshot.
        """

        return recipe_for(self.recipe_code)


@dataclass(frozen=True, slots=True)
class PersonalRpgResult:
    """@brief 个人 RPG 持久化用例结果 / Personal-RPG persistence use-case result.

    @param code 操作结果代码 / Operation result code.
    @param profile 可选个人进度快照 / Optional personal progression snapshot.
    @param exploration 可选已结算探索 / Optional settled exploration.
    @param recipe 可选已制作配方 / Optional crafted recipe.
    @param replayed 是否来自幂等回放 / Whether the result comes from idempotent replay.
    """

    code: PersonalRpgCode
    """@brief 操作结果代码 / Operation result code."""

    profile: PersonalRpgProfile | None = None
    """@brief 可选个人进度快照 / Optional personal progression snapshot."""

    exploration: DailyExploration | None = None
    """@brief 可选已结算探索 / Optional settled exploration."""

    recipe: CraftingRecipe | None = None
    """@brief 可选已制作配方 / Optional crafted recipe."""

    replayed: bool = False
    """@brief 幂等回放标记 / Idempotent replay marker."""

    def __post_init__(self) -> None:
        """@brief 验证结果快照形状 / Validate result-snapshot shape.

        @return None / None.
        @raise TypeError 结果代码、快照或回放标记类型非法时抛出 /
            Raised when code, snapshot, or replay flag type is invalid.
        """

        if not isinstance(self.code, PersonalRpgCode):
            raise TypeError("Personal RPG result code must be PersonalRpgCode")
        if self.profile is not None and not isinstance(
            self.profile, PersonalRpgProfile
        ):
            raise TypeError("Personal RPG result profile must be PersonalRpgProfile")
        if self.exploration is not None and not isinstance(
            self.exploration,
            DailyExploration,
        ):
            raise TypeError("Personal RPG result exploration must be DailyExploration")
        if self.recipe is not None and not isinstance(self.recipe, CraftingRecipe):
            raise TypeError("Personal RPG result recipe must be CraftingRecipe")
        if not isinstance(self.replayed, bool):
            raise TypeError("Personal RPG result replayed flag must be a bool")
