"""@brief Assistant 投递端口 / Assistant delivery ports."""

from typing import Any, Protocol


class VisibleContentSink(Protocol):
    """@brief 用户可见内容投递端口 / User-visible content delivery port."""

    def __call__(self, content: str) -> str | None:
        """@brief 投递可见文本 / Deliver visible text.

        @param content 文本内容 / Text content.
        @return 实际投递文本；None 表示未完成 / Delivered text; None when incomplete.
        """
        ...

    def send_media(self, media_type: str, result: dict[str, Any]) -> list[Any]:
        """@brief 投递 Runtime 生成的媒体 / Deliver media generated by the Runtime.

        @param media_type 媒体能力类型 / Media capability type.
        @param result Runtime 内部媒体结果 / Runtime internal media result.
        @return 已发送消息 / Sent messages.
        """
        ...
