-- migrate:up

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS conversation;
CREATE SCHEMA IF NOT EXISTS assistant;
CREATE SCHEMA IF NOT EXISTS economy;
CREATE SCHEMA IF NOT EXISTS moderation;
CREATE SCHEMA IF NOT EXISTS crypto;
CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS infra;

CREATE TABLE conversation.chat_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL UNIQUE,
  messages JSONB NOT NULL,
  timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversation.permanent_chat_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  conversation_snapshot JSONB NOT NULL,
  summary TEXT NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_permanent_user_created
  ON conversation.permanent_chat_records (user_id, created_at);

CREATE TABLE conversation.chat_records_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  message_type TEXT NOT NULL DEFAULT 'text'
    CHECK (message_type IN ('text','photo','sticker','voice','video','document','other')),
  content TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_group_created
  ON conversation.chat_records_group (group_id, created_at);
CREATE INDEX idx_group_message
  ON conversation.chat_records_group (group_id, message_id);

CREATE TABLE identity.users (
  id BIGINT NOT NULL PRIMARY KEY,
  tg_uid BIGINT NULL UNIQUE,
  provider TEXT NOT NULL DEFAULT 'telegram'
    CHECK (provider IN ('telegram','local','web')),
  name TEXT NOT NULL,
  coins INT NOT NULL DEFAULT 0,
  permission INT DEFAULT 0,
  info VARCHAR(500) DEFAULT NULL
);

CREATE TABLE economy.user_lottery (
  user_id BIGINT NOT NULL PRIMARY KEY,
  last_lottery_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE economy.user_task (
  user_id BIGINT NOT NULL,
  task_id INT NOT NULL,
  completed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, task_id)
);

CREATE TABLE moderation.group_verification (
  group_id BIGINT NOT NULL PRIMARY KEY,
  group_name TEXT NOT NULL
);

CREATE TABLE moderation.verification_tasks (
  user_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  expire_time TIMESTAMP NOT NULL,
  PRIMARY KEY (user_id, group_id)
);

CREATE TABLE economy.user_stakes (
  user_id BIGINT NOT NULL PRIMARY KEY,
  stake_amount INT NOT NULL,
  stake_time TIMESTAMP NOT NULL,
  last_reward_time TIMESTAMP NULL
);

CREATE TABLE crypto.user_btc_predictions (
  user_id BIGINT NOT NULL PRIMARY KEY,
  predict_type VARCHAR(10) NOT NULL,
  amount INT NOT NULL,
  start_price DECIMAL(20,8) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE crypto.token_swap_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username VARCHAR(255) NOT NULL,
  wallet_address VARCHAR(50) NOT NULL,
  amount INT NOT NULL,
  request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'pending'
);

CREATE TABLE moderation.group_keywords (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  response TEXT NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_keyword_unique UNIQUE (group_id, keyword)
);

CREATE TABLE moderation.group_spam_control (
  group_id BIGINT NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  enabled_by BIGINT,
  enabled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  block_links BOOLEAN NOT NULL DEFAULT FALSE,
  block_mentions BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE moderation.group_spam_keywords (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  is_regex BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_spam_keyword_unique UNIQUE (group_id, keyword)
);

CREATE TABLE game.user_omikuji (
  user_id BIGINT NOT NULL,
  fortune_date DATE NOT NULL,
  fortune VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, fortune_date)
);

CREATE TABLE economy.redemption_codes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL UNIQUE,
  amount INT NOT NULL,
  is_used BOOLEAN NOT NULL DEFAULT FALSE,
  used_by BIGINT DEFAULT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (used_by) REFERENCES identity.users(id) ON DELETE SET NULL
);

CREATE TABLE economy.user_invitations (
  invited_user_id BIGINT NOT NULL,
  referrer_id BIGINT NOT NULL,
  invitation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reward_claimed BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (invited_user_id),
  FOREIGN KEY (invited_user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (referrer_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE economy.user_checkin (
  user_id BIGINT NOT NULL PRIMARY KEY,
  last_checkin_date DATE NOT NULL,
  consecutive_days INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crypto.group_chart_tokens (
  group_id BIGINT NOT NULL PRIMARY KEY,
  chain VARCHAR(20) NOT NULL,
  ca VARCHAR(100) NOT NULL,
  set_by BIGINT NOT NULL,
  buy_alert_threshold FLOAT NULL,
  set_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_characters (
  character_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL,
  level INT DEFAULT 1,
  hp INT DEFAULT 10,
  max_hp INT DEFAULT 10,
  atk INT DEFAULT 2,
  matk INT DEFAULT 0,
  def INT DEFAULT 1,
  experience BIGINT DEFAULT 0,
  allow_battle BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE game.rpg_equipment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type TEXT NOT NULL
    CHECK (type IN ('weapon', 'offhand', 'armor', 'treasure1', 'treasure2')),
  atk_bonus INT DEFAULT 0,
  def_bonus INT DEFAULT 0,
  hp_bonus INT DEFAULT 0,
  matk_bonus INT DEFAULT 0,
  description TEXT,
  price INT NOT NULL,
  rarity INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type TEXT NOT NULL
    CHECK (type IN ('consumable', 'material', 'quest')),
  effect TEXT,
  description TEXT,
  price INT NOT NULL,
  use_limit INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game.rpg_player_equipment (
  user_id BIGINT NOT NULL PRIMARY KEY,
  weapon_id INT DEFAULT NULL,
  offhand_id INT DEFAULT NULL,
  armor_id INT DEFAULT NULL,
  treasure1_id INT DEFAULT NULL,
  treasure2_id INT DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (weapon_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (offhand_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (armor_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (treasure1_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL,
  FOREIGN KEY (treasure2_id) REFERENCES game.rpg_equipment(id) ON DELETE SET NULL
);

CREATE TABLE game.rpg_player_inventory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  quantity INT DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES game.rpg_items(id) ON DELETE CASCADE,
  CONSTRAINT rpg_player_inventory_unique UNIQUE (user_id, item_id)
);

CREATE TABLE game.rpg_shop (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type TEXT NOT NULL CHECK (item_type IN ('equipment', 'item')),
  item_id INT NOT NULL,
  price INT NOT NULL,
  stock INT DEFAULT -1,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT rpg_shop_item_unique UNIQUE (item_type, item_id)
);

CREATE INDEX idx_rpg_shop_item ON game.rpg_shop (item_type, item_id);

CREATE TABLE game.rpg_player_equipment_stats (
  user_id BIGINT NOT NULL PRIMARY KEY,
  total_atk_bonus INT DEFAULT 0,
  total_def_bonus INT DEFAULT 0,
  total_hp_bonus INT DEFAULT 0,
  total_matk_bonus INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE identity.web_password (
  user_id BIGINT NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

CREATE TABLE economy.kindness_gifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL,
  amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kindness_recipient_created
  ON economy.kindness_gifts (recipient_id, created_at);

CREATE TABLE assistant.ai_user_affection (
  user_id BIGINT NOT NULL PRIMARY KEY,
  affection INT NOT NULL DEFAULT 0,
  impression VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_user_affection_user
    FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE
);

-- migrate:down

DROP TABLE IF EXISTS assistant.ai_user_affection;
DROP TABLE IF EXISTS economy.kindness_gifts;
DROP TABLE IF EXISTS identity.web_password;
DROP TABLE IF EXISTS game.rpg_player_equipment_stats;
DROP TABLE IF EXISTS game.rpg_shop;
DROP TABLE IF EXISTS game.rpg_player_inventory;
DROP TABLE IF EXISTS game.rpg_player_equipment;
DROP TABLE IF EXISTS game.rpg_items;
DROP TABLE IF EXISTS game.rpg_equipment;
DROP TABLE IF EXISTS game.rpg_characters;
DROP TABLE IF EXISTS crypto.group_chart_tokens;
DROP TABLE IF EXISTS economy.user_checkin;
DROP TABLE IF EXISTS economy.user_invitations;
DROP TABLE IF EXISTS economy.redemption_codes;
DROP TABLE IF EXISTS game.user_omikuji;
DROP TABLE IF EXISTS moderation.group_spam_keywords;
DROP TABLE IF EXISTS moderation.group_spam_control;
DROP TABLE IF EXISTS moderation.group_keywords;
DROP TABLE IF EXISTS crypto.token_swap_requests;
DROP TABLE IF EXISTS crypto.user_btc_predictions;
DROP TABLE IF EXISTS economy.user_stakes;
DROP TABLE IF EXISTS moderation.verification_tasks;
DROP TABLE IF EXISTS moderation.group_verification;
DROP TABLE IF EXISTS economy.user_task;
DROP TABLE IF EXISTS economy.user_lottery;
DROP TABLE IF EXISTS identity.users;
DROP TABLE IF EXISTS conversation.chat_records_group;
DROP TABLE IF EXISTS conversation.permanent_chat_records;
DROP TABLE IF EXISTS conversation.chat_records;

DROP SCHEMA IF EXISTS game;
DROP SCHEMA IF EXISTS crypto;
DROP SCHEMA IF EXISTS moderation;
DROP SCHEMA IF EXISTS economy;
DROP SCHEMA IF EXISTS assistant;
DROP SCHEMA IF EXISTS conversation;
DROP SCHEMA IF EXISTS identity;
