"""@brief 随机活动用例命令 / Chance-activity use-case commands."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from fogmoe_bot.domain.chance.fairness import MAX_NONCE, ClientSeed
from fogmoe_bot.domain.chance.money import FreeTokenStake
from fogmoe_bot.domain.chance.rules import ChanceRuleset
from fogmoe_bot.domain.chance.scope import (
    GroupRoundScope,
    PersonalRoundScope,
    RoundScope,
)


@dataclass(frozen=True, slots=True)
class CommitChanceRound:
    """@brief 在玩家种子之前建立随机活动承诺的命令 / Command to commit a chance round before the player seed.

    @param round_id 由调用方生成的稳定轮次 UUID / Stable round UUID generated by the caller.
    @param scope 明确个人或群组活动范围 / Explicit personal or group activity scope.
    @param player_id 下单玩家标识 / Wagering-player identity.
    @param ruleset 当前冻结的规则集 / Currently frozen ruleset.
    @param rule_code 玩家选择的规则编码 / Rule code selected by the player.
    @param stake 仅免费金币押注 / Free-token-only stake.
    @param nonce 轮次内业务 nonce / Business nonce within the round.
    """

    round_id: UUID
    """@brief 稳定轮次 UUID / Stable round UUID."""

    scope: RoundScope
    """@brief 个人或群组范围 / Personal or group scope."""

    player_id: int
    """@brief 下单玩家标识 / Wagering-player identity."""

    ruleset: ChanceRuleset
    """@brief 冻结规则集 / Frozen ruleset."""

    rule_code: str
    """@brief 玩家选中规则 / Player-selected rule."""

    stake: FreeTokenStake
    """@brief 免费金币押注 / Free-token stake."""

    nonce: int
    """@brief 业务 nonce / Business nonce."""

    def __post_init__(self) -> None:
        """@brief 在获取服务器熵前校验开轮命令 / Validate an open-round command before consuming server entropy.

        @return None / None.
        @raise TypeError 轮次字段类型不匹配时抛出 / Raised when round field types do not match.
        @raise ValueError 玩家身份、范围或赔率非法时抛出 /
            Raised when player identity, scope, or odds are invalid.
        """

        if not isinstance(self.round_id, UUID):
            raise TypeError("Chance command requires a UUID round identifier")
        _validate_scope(self.scope)
        if isinstance(self.player_id, bool) or not isinstance(self.player_id, int):
            raise TypeError("Chance command player must be an integer")
        if self.player_id <= 0:
            raise ValueError("Chance command player must be positive")
        if isinstance(self.scope, PersonalRoundScope) and (
            self.scope.user_id != self.player_id
        ):
            raise ValueError("Personal chance rounds may only be played by their owner")
        if not isinstance(self.ruleset, ChanceRuleset):
            raise TypeError("Chance command requires ChanceRuleset")
        if not isinstance(self.stake, FreeTokenStake):
            raise TypeError("Chance commands accept only FreeTokenStake")
        if isinstance(self.nonce, bool) or not isinstance(self.nonce, int):
            raise TypeError("Chance command nonce must be an integer")
        if self.nonce < 0 or self.nonce > MAX_NONCE:
            raise ValueError("Chance command nonce falls outside the protocol range")
        self.ruleset.quote(self.rule_code, self.stake)


@dataclass(frozen=True, slots=True)
class CommitDurableChanceRound:
    """@brief 建立并耐久化随机活动承诺的命令 / Command to durably persist a chance commitment.

    ``actor_id`` 与 ``round.player_id`` 分开建模，使工作流可显式拒绝委托下注
    （delegated wagering）。
    ``actor_id`` and ``round.player_id`` are modeled separately so the workflow can explicitly
    reject delegated wagering.

    @param actor_id 发起请求的用户标识 / User identity initiating the request.
    @param round 经过边界校验的承诺命令 / Boundary-validated commitment command.
    @param idempotency_key 来源事件的稳定幂等键 / Stable idempotency key of the source event.
    """

    actor_id: int
    """@brief 发起用户标识 / Initiating-user identity."""

    round: CommitChanceRound
    """@brief 承诺命令 / Commitment command."""

    idempotency_key: str
    """@brief 稳定幂等键 / Stable idempotency key."""

    def __post_init__(self) -> None:
        """@brief 校验耐久承诺命令形状 / Validate durable commitment-command shape.

        @return None / None.
        @raise TypeError 数学命令类型不匹配时抛出 / Raised when the commitment-command type does not match.
        @raise ValueError 身份或幂等键非法时抛出 / Raised when identity or idempotency key is invalid.
        """

        _validate_actor_id(self.actor_id)
        if not isinstance(self.round, CommitChanceRound):
            raise TypeError("Durable chance commitment requires CommitChanceRound")
        object.__setattr__(
            self, "idempotency_key", _normalize_idempotency_key(self.idempotency_key)
        )


@dataclass(frozen=True, slots=True)
class BindAndSettleChanceRound:
    """@brief 绑定玩家种子并原子结算的命令 / Command to bind a player seed and settle atomically.

    该命令不携带服务器种子；端口必须在事务内从私有承诺态读取它。
    This command carries no server seed; the port must load it from private committed state inside
    its transaction.

    @param round_id 已公开承诺的轮次 UUID / UUID of the publicly committed round.
    @param actor_id 请求绑定和结算的用户 / User requesting bind and settlement.
    @param scope 请求所在的明确个人或群组范围 / Explicit personal or group request scope.
    @param client_seed 玩家在揭示前提交的种子 / Player seed supplied before reveal.
    @param idempotency_key 来源事件的稳定幂等键 / Stable idempotency key of the source event.
    """

    round_id: UUID
    """@brief 已承诺轮次 UUID / Committed round UUID."""

    actor_id: int
    """@brief 发起用户标识 / Initiating-user identity."""

    scope: RoundScope
    """@brief 请求所在范围 / Request scope."""

    client_seed: ClientSeed
    """@brief 玩家客户端种子 / Player client seed."""

    idempotency_key: str
    """@brief 稳定幂等键 / Stable idempotency key."""

    def __post_init__(self) -> None:
        """@brief 校验绑定和结算命令 / Validate bind-and-settle command.

        @return None / None.
        @raise TypeError 轮次、范围或种子类型不匹配时抛出 /
            Raised when round, scope, or seed type does not match.
        @raise ValueError 身份或幂等键非法时抛出 / Raised when identity or idempotency key is invalid.
        """

        if not isinstance(self.round_id, UUID):
            raise TypeError("Chance bind-and-settle requires a UUID round identifier")
        _validate_actor_id(self.actor_id)
        _validate_scope(self.scope)
        if not isinstance(self.client_seed, ClientSeed):
            raise TypeError("Chance bind-and-settle requires ClientSeed")
        object.__setattr__(
            self, "idempotency_key", _normalize_idempotency_key(self.idempotency_key)
        )


@dataclass(frozen=True, slots=True)
class LookupChanceRound:
    """@brief 查询一个耐久随机活动轮次的命令 / Command to look up one durable chance round.

    @param round_id 待查询轮次 UUID / UUID of the round to look up.
    @param actor_id 请求查看的用户 / User requesting visibility.
    @param scope 请求所在的明确个人或群组范围 / Explicit personal or group request scope.
    """

    round_id: UUID
    """@brief 轮次 UUID / Round UUID."""

    actor_id: int
    """@brief 请求用户标识 / Requesting-user identity."""

    scope: RoundScope
    """@brief 请求所在范围 / Request scope."""

    def __post_init__(self) -> None:
        """@brief 校验查询命令 / Validate lookup command.

        @return None / None.
        @raise TypeError 轮次或范围类型不匹配时抛出 / Raised when round or scope type does not match.
        @raise ValueError 身份非法时抛出 / Raised when identity is invalid.
        """

        if not isinstance(self.round_id, UUID):
            raise TypeError("Chance lookup requires a UUID round identifier")
        _validate_actor_id(self.actor_id)
        _validate_scope(self.scope)


def _validate_actor_id(actor_id: int) -> None:
    """@brief 校验工作流调用者身份 / Validate workflow actor identity.

    @param actor_id 待校验调用者标识 / Actor identity to validate.
    @return None / None.
    @raise ValueError 调用者不是正整数时抛出 / Raised when the actor is not a positive integer.
    """

    if isinstance(actor_id, bool) or not isinstance(actor_id, int) or actor_id <= 0:
        raise ValueError("Chance workflow actor must be a positive integer")


def _validate_scope(scope: RoundScope) -> None:
    """@brief 校验显式轮次范围 / Validate explicit round scope.

    @param scope 个人或群组范围 / Personal or group scope.
    @return None / None.
    @raise TypeError 范围不是受支持的显式类型时抛出 /
        Raised when scope is not a supported explicit type.
    """

    if not isinstance(scope, (PersonalRoundScope, GroupRoundScope)):
        raise TypeError("Chance workflow scope must be personal or group")


def _normalize_idempotency_key(value: str) -> str:
    """@brief 规范化来源事件幂等键 / Normalize a source-event idempotency key.

    @param value 原始幂等键 / Raw idempotency key.
    @return 去除首尾空白后的稳定键 / Stable key with surrounding whitespace removed.
    @raise ValueError 键为空或过长时抛出 / Raised when the key is empty or oversized.
    """

    if not isinstance(value, str):
        raise ValueError("Chance idempotency key must be text")
    normalized = value.strip()
    if not 1 <= len(normalized) <= 200:
        raise ValueError("Chance idempotency key must contain 1-200 characters")
    return normalized
