"""@brief 随机活动应用命令与私有准备态 / Chance-activity application commands and private preparation state."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from fogmoe_bot.domain.chance.fairness import MAX_NONCE, ClientSeed, ServerSeed
from fogmoe_bot.domain.chance.money import FreeTokenStake
from fogmoe_bot.domain.chance.rounds import (
    ChanceRound,
    ChanceSettlement,
    CommittedChanceRound,
)
from fogmoe_bot.domain.chance.rules import ChanceQuote, ChanceRuleset
from fogmoe_bot.domain.chance.scope import (
    GroupRoundScope,
    PersonalRoundScope,
    RoundScope,
)


@dataclass(frozen=True, slots=True)
class CommitChanceRound:
    """@brief 在玩家种子之前建立随机活动承诺的命令 / Command to commit a chance round before the player seed.

    @param round_id 由调用方生成的稳定轮次 UUID / Stable round UUID generated by the caller.
    @param scope 明确个人或群组活动范围 / Explicit personal or group activity scope.
    @param player_id 下单玩家标识 / Wagering-player identity.
    @param ruleset 当前冻结的规则集 / Currently frozen ruleset.
    @param rule_code 玩家选择的规则编码 / Rule code selected by the player.
    @param stake 仅免费金币押注 / Free-token-only stake.
    @param nonce 轮次内业务 nonce / Business nonce within the round.
    """

    round_id: UUID
    """@brief 稳定轮次 UUID / Stable round UUID."""

    scope: RoundScope
    """@brief 个人或群组范围 / Personal or group scope."""

    player_id: int
    """@brief 下单玩家标识 / Wagering-player identity."""

    ruleset: ChanceRuleset
    """@brief 冻结规则集 / Frozen ruleset."""

    rule_code: str
    """@brief 玩家选中规则 / Player-selected rule."""

    stake: FreeTokenStake
    """@brief 免费金币押注 / Free-token stake."""

    nonce: int
    """@brief 业务 nonce / Business nonce."""

    def __post_init__(self) -> None:
        """@brief 在获取服务器熵前校验开轮命令 / Validate an open-round command before consuming server entropy.

        @return None / None.
        @raise TypeError 轮次字段类型不匹配时抛出 / Raised when round field types do not match.
        @raise ValueError 玩家身份、范围或赔率非法时抛出 /
            Raised when player identity, scope, or odds are invalid.
        """

        if not isinstance(self.round_id, UUID):
            raise TypeError("Chance command requires a UUID round identifier")
        if not isinstance(self.scope, (PersonalRoundScope, GroupRoundScope)):
            raise TypeError("Chance command scope must be personal or group")
        if isinstance(self.player_id, bool) or not isinstance(self.player_id, int):
            raise TypeError("Chance command player must be an integer")
        if self.player_id <= 0:
            raise ValueError("Chance command player must be positive")
        if isinstance(self.scope, PersonalRoundScope) and (
            self.scope.user_id != self.player_id
        ):
            raise ValueError("Personal chance rounds may only be played by their owner")
        if not isinstance(self.ruleset, ChanceRuleset):
            raise TypeError("Chance command requires ChanceRuleset")
        if not isinstance(self.stake, FreeTokenStake):
            raise TypeError("Chance commands accept only FreeTokenStake")
        if isinstance(self.nonce, bool) or not isinstance(self.nonce, int):
            raise TypeError("Chance command nonce must be an integer")
        if self.nonce < 0 or self.nonce > MAX_NONCE:
            raise ValueError("Chance command nonce falls outside the protocol range")
        self.ruleset.quote(self.rule_code, self.stake)


@dataclass(frozen=True, slots=True)
class PrivateCommittedChanceRound:
    """@brief 已承诺、尚待玩家种子的私有状态 / Private committed state awaiting a player seed.

    此对象必须先被持久化，公开 ``committed_round.commitment`` 后，才可以调用
    ``bind_client_seed``。绝不可在 Telegram 文案或日志中序列化 ``server_seed``。
    This object must be persisted and expose ``committed_round.commitment`` before
    ``bind_client_seed`` may be called. Its ``server_seed`` must never be serialized into
    Telegram copy or logs.

    @param committed_round 可公开展示承诺的轮次 / Round whose commitment may be displayed publicly.
    @param server_seed 尚未揭示的服务器种子 / Unrevealed server seed.
    """

    committed_round: CommittedChanceRound
    """@brief 可公开的承诺轮次信息 / Public committed-round information."""

    server_seed: ServerSeed
    """@brief 必须在结算前保密的服务器种子 / Server seed that must remain secret before settlement."""

    def __post_init__(self) -> None:
        """@brief 校验私有承诺状态 / Validate private committed state.

        @return None / None.
        @raise TypeError 承诺轮次或服务器种子类型不匹配时抛出 /
            Raised when committed-round or server-seed type does not match.
        """

        if not isinstance(self.committed_round, CommittedChanceRound):
            raise TypeError("Private chance commitment requires CommittedChanceRound")
        if not isinstance(self.server_seed, ServerSeed):
            raise TypeError("Private chance commitment requires ServerSeed")

    def quote(self) -> ChanceQuote:
        """@brief 读取本轮固定赔率报价 / Read this round's fixed odds quote.

        @return 严格负期望报价 / Strictly negative-EV quote.
        """

        return self.committed_round.quote

    def bind_client_seed(self, client_seed: ClientSeed) -> PreparedChanceRound:
        """@brief 在承诺发布后绑定玩家种子 / Bind a player seed after commitment publication.

        @param client_seed 玩家在揭示前提交的种子 / Player seed submitted before reveal.
        @return 可结算的私有准备态 / Private prepared state ready for settlement.
        """

        return PreparedChanceRound(
            round=self.committed_round.bind_client_seed(client_seed),
            server_seed=self.server_seed,
        )


@dataclass(frozen=True, slots=True)
class PreparedChanceRound:
    """@brief 已绑定玩家种子、尚未揭示种子的私有准备态 / Private prepared state with player seed bound and server seed unrevealed.

    @param round 已绑定玩家种子的完整轮次 / Full round with player seed bound.
    @param server_seed 尚未揭示的服务器种子 / Unrevealed server seed.
    """

    round: ChanceRound
    """@brief 可结算的完整轮次 / Full round ready for settlement."""

    server_seed: ServerSeed
    """@brief 必须在结算前保密的服务器种子 / Server seed that must remain secret before settlement."""

    def __post_init__(self) -> None:
        """@brief 校验可结算私有状态 / Validate settle-ready private state.

        @return None / None.
        @raise TypeError 完整轮次或服务器种子类型不匹配时抛出 /
            Raised when full-round or server-seed type does not match.
        """

        if not isinstance(self.round, ChanceRound):
            raise TypeError("Prepared chance round requires ChanceRound")
        if not isinstance(self.server_seed, ServerSeed):
            raise TypeError("Prepared chance round requires ServerSeed")

    def settlement(self) -> ChanceSettlement:
        """@brief 使用保存种子结算该轮 / Settle this round using its retained seed.

        @return 包含可复验公平性证明的结算 / Settlement with a verifiable fairness proof.
        """

        return self.round.settle(self.server_seed)
