"""@brief Workspace Bash 执行应用契约 / Application contracts for Workspace Bash execution."""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass, field

from fogmoe_bot.domain.workspace import path as workspace_path
from fogmoe_bot.domain.workspace.runtime import (
    WorkspaceRequestHash,
    WorkspaceRequestId,
)
from fogmoe_bot.domain.workspace.scope import (
    GroupRuntimeScope,
    PersonalRuntimeScope,
    RuntimeScope,
)

MAX_BASH_COMMAND_CHARACTERS = 16 * 1024
"""@brief 单次 Bash 程序文本最大字符数 / Maximum characters in one Bash program.

该字符上限与 native ``argv`` 单元素 16 KiB 上限保持一致。真正的传输边界仍按
``MAX_BASH_COMMAND_BYTES`` 计算，避免多字节 Unicode 文本绕过字符数限制。/ This character
cap matches the native 16 KiB per-``argv``-element ceiling. The actual transport boundary is
still measured by ``MAX_BASH_COMMAND_BYTES`` so multibyte Unicode text cannot bypass it.
"""

MAX_BASH_COMMAND_BYTES = 16 * 1024
"""@brief 单次 Bash 程序的 native argv 字节上限 / Native argv-byte limit for one Bash program."""

MAX_BASH_STDIN_BYTES = 65_536
"""@brief 单次 Bash 标准输入最大 UTF-8 字节数 / Maximum UTF-8 bytes in one Bash standard input."""

DEFAULT_BASH_TIMEOUT_SECONDS = 30
"""@brief 默认 Bash wall-clock deadline / Default Bash wall-clock deadline."""

MAX_BASH_TIMEOUT_SECONDS = 300
"""@brief 单次 Bash wall-clock hard deadline / Hard wall-clock deadline for one Bash command."""

DEFAULT_BASH_OUTPUT_LIMIT_BYTES = 65_536
"""@brief 默认 stdout/stderr 合并输出限制 / Default combined stdout/stderr output limit."""

MAX_BASH_OUTPUT_LIMIT_BYTES = 96 * 1024
"""@brief 与 SOCK_SEQPACKET 单帧协议一致的 stdout/stderr 合并输出硬限制 / Hard combined stdout/stderr cap aligned with the SOCK_SEQPACKET single-frame protocol.

该上限小于 broker 在已验证 socket buffer 中可发送的最大 frame，避免合法的 Agent 请求在
AF_UNIX ``EMSGSIZE`` 处失败并把 journal 留为 pending。/ This cap stays below the largest
frame the broker can send through its verified socket buffer, avoiding an otherwise valid Agent
request failing at AF_UNIX ``EMSGSIZE`` and leaving a journal pending.
"""

MAX_ADD_FILE_BYTES = 8 * 1024 * 1024
"""@brief 单次 add_file 的逻辑字节上限（8 MiB） / Logical byte cap for one add_file operation (8 MiB).

@note 这是 Bot 到 native control plane 的协议预算，不替代 XFS project quota（XFS 项目配额）对
    persistent OverlayFS upper layer 的内核强制容量限制。/ This is a Bot-to-native-control-plane
    protocol budget; it does not replace the kernel-enforced persistent-OverlayFS capacity limit
    supplied by XFS project quota.
"""

MAX_ADD_FILE_CHUNK_BYTES = 64 * 1024
"""@brief 单个 add_file chunk 的字节上限 / Byte cap for one add_file chunk.

@note 该值为经 metadata 包装后的 SOCK_SEQPACKET frame 留出余量；native 层仍必须独立校验。
    This leaves room for metadata inside a SOCK_SEQPACKET frame; the native layer must validate it independently.
"""

_PAYLOAD_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$")
"""@brief 由可信上层生成的 payload opaque ID 语法 / Payload opaque-ID grammar generated by a trusted upper layer."""

_PAYLOAD_SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
"""@brief payload 内容 SHA-256 的规范小写语法 / Canonical lowercase syntax for a payload-content SHA-256."""

_PAYLOAD_RUNTIME_PATH_PATTERN = re.compile(
    r"^/workspace/uploads/[A-Za-z0-9][A-Za-z0-9_-]{0,127}/payload$"
)
"""@brief native 唯一允许写入的 payload runtime 路径语法 / Only runtime-path grammar writable by native payload ingress."""


@dataclass(frozen=True, slots=True)
class RunBashCommand:
    """@brief 在已认证 Workspace 内执行一段 Bash / Execute one Bash program inside an authenticated Workspace.

    @param scope 个人或整群的强隔离范围 / Strongly isolated personal-or-whole-group scope.
    @param command 在 runtime 内执行的 Bash 程序 / Bash program executed inside the runtime.
    @param request_id 可重试命令的稳定 ID / Stable ID of the retryable command.
    @param request_hash 完整调用语义的 SHA-256 摘要 / SHA-256 digest of complete invocation semantics.
    @param stdin 提供给命令的 UTF-8 标准输入 / UTF-8 standard input supplied to the command.
    @param working_directory Overlay 内的相对工作目录 / Relative working directory inside the Overlay.
    @param timeout_seconds wall-clock deadline（秒） / Wall-clock deadline in seconds.
    @param output_limit_bytes stdout/stderr 合并字节上限 / Combined stdout/stderr byte cap.
    @note 该命令有意保留 Bash 语言能力；隔离应由 native supervisor 的 namespace、mount、
        cgroup、seccomp 和 OverlayFS 实现，而不是由 Python 过滤 shell 文本。/ This command
        intentionally retains Bash language power; isolation is implemented by the native
        supervisor's namespaces, mounts, cgroups, seccomp, and OverlayFS rather than Python
        filtering shell text.
    """

    scope: RuntimeScope
    command: str
    request_id: WorkspaceRequestId
    request_hash: WorkspaceRequestHash
    stdin: str = ""
    working_directory: workspace_path.WorkspaceRelativePath = field(
        default_factory=workspace_path.WorkspaceRelativePath
    )
    timeout_seconds: int = DEFAULT_BASH_TIMEOUT_SECONDS
    output_limit_bytes: int = DEFAULT_BASH_OUTPUT_LIMIT_BYTES

    def __post_init__(self) -> None:
        """@brief 验证 Bash 命令的资源与幂等边界 / Validate resource and idempotency boundaries of a Bash command.

        @return None / None.
        @raise TypeError 字段不是其强类型或严格基础类型时抛出 /
            Raised when a field is not its strong type or strict primitive type.
        @raise ValueError 程序、输入、路径、timeout 或输出预算越界时抛出 /
            Raised when program, input, path, timeout, or output budget is out of bounds.
        """

        if not isinstance(self.scope, PersonalRuntimeScope | GroupRuntimeScope):
            raise TypeError("RunBashCommand requires a typed workspace runtime scope")
        if not isinstance(self.command, str):
            raise TypeError("RunBashCommand command must be a string")
        command_bytes = _require_utf8(self.command, label="RunBashCommand command")
        if (
            not self.command.strip()
            or len(self.command) > MAX_BASH_COMMAND_CHARACTERS
            or command_bytes > MAX_BASH_COMMAND_BYTES
            or "\x00" in self.command
        ):
            raise ValueError(
                "RunBashCommand command must be non-blank, within the native argv "
                "budget, and NUL-free"
            )
        if not isinstance(self.request_id, WorkspaceRequestId):
            raise TypeError("RunBashCommand requires a WorkspaceRequestId")
        if not isinstance(self.request_hash, WorkspaceRequestHash):
            raise TypeError("RunBashCommand requires a WorkspaceRequestHash")
        if not isinstance(self.stdin, str):
            raise TypeError("RunBashCommand stdin must be a string")
        stdin_bytes = _require_utf8(self.stdin, label="RunBashCommand stdin")
        if "\x00" in self.stdin or stdin_bytes > MAX_BASH_STDIN_BYTES:
            raise ValueError(
                "RunBashCommand stdin is invalid or exceeds its byte limit"
            )
        if not isinstance(
            self.working_directory,
            workspace_path.WorkspaceRelativePath,
        ):
            raise TypeError("RunBashCommand requires a WorkspaceRelativePath")
        if isinstance(self.timeout_seconds, bool) or not isinstance(
            self.timeout_seconds, int
        ):
            raise TypeError("RunBashCommand timeout_seconds must be an integer")
        if not 1 <= self.timeout_seconds <= MAX_BASH_TIMEOUT_SECONDS:
            raise ValueError(
                "RunBashCommand timeout_seconds must be between 1 and "
                f"{MAX_BASH_TIMEOUT_SECONDS}"
            )
        if isinstance(self.output_limit_bytes, bool) or not isinstance(
            self.output_limit_bytes, int
        ):
            raise TypeError("RunBashCommand output_limit_bytes must be an integer")
        if not 1 <= self.output_limit_bytes <= MAX_BASH_OUTPUT_LIMIT_BYTES:
            raise ValueError(
                "RunBashCommand output_limit_bytes must be between 1 and "
                f"{MAX_BASH_OUTPUT_LIMIT_BYTES}"
            )


@dataclass(frozen=True, slots=True)
class RunBashResult:
    """@brief 一次已监督 Bash 执行的规范结果 / Canonical result of one supervised Bash execution.

    @param stdout 已按 native 输出预算截断的文本标准输出 / Text standard output already bounded by the native output budget.
    @param stderr 已按 native 输出预算截断的文本标准错误 / Text standard error already bounded by the native output budget.
    @param exit_code 正常退出码；超时时为 ``None`` / Normal exit code; ``None`` on timeout.
    @param timed_out native supervisor 是否因 deadline 终止任务树 / Whether the native supervisor terminated the task tree for its deadline.
    @param truncated stdout 或 stderr 是否达到输出预算 / Whether stdout or stderr reached the output budget.
    @param replayed 是否由 native execution journal 回放 / Whether the native execution journal replayed the result.
    @param request_id 已执行或回放的稳定请求 ID / Stable request ID executed or replayed.
    @note 非零 exit code 仍是一次已完成的、可持久化的工具结果；它不是需要自动重试的
        transport 失败。/ A non-zero exit code remains a completed, persistable tool result;
        it is not a transport failure to retry automatically.
    """

    stdout: str
    stderr: str
    exit_code: int | None
    timed_out: bool
    truncated: bool
    replayed: bool
    request_id: WorkspaceRequestId

    def __post_init__(self) -> None:
        """@brief 验证原生 supervisor 的执行结果 / Validate the native-supervisor execution result.

        @return None / None.
        @raise TypeError 字段类型不符合协议时抛出 / Raised when field types violate the protocol.
        @raise ValueError exit status 和 timeout 语义矛盾时抛出 /
            Raised when exit-status and timeout semantics contradict one another.
        """

        if not isinstance(self.stdout, str) or not isinstance(self.stderr, str):
            raise TypeError("RunBashResult stdout and stderr must be strings")
        if not isinstance(self.timed_out, bool):
            raise TypeError("RunBashResult timed_out must be a bool")
        if not isinstance(self.truncated, bool):
            raise TypeError("RunBashResult truncated must be a bool")
        if not isinstance(self.replayed, bool):
            raise TypeError("RunBashResult replayed must be a bool")
        if not isinstance(self.request_id, WorkspaceRequestId):
            raise TypeError("RunBashResult requires a WorkspaceRequestId")
        if self.exit_code is not None and (
            isinstance(self.exit_code, bool)
            or not isinstance(self.exit_code, int)
            or not 0 <= self.exit_code <= 255
        ):
            raise ValueError("RunBashResult exit_code must be an unsigned exit status")
        if self.timed_out != (self.exit_code is None):
            raise ValueError(
                "RunBashResult timeout results must have no exit code, and vice versa"
            )

    @property
    def succeeded(self) -> bool:
        """@brief 判断命令是否以零退出码完成 / Determine whether the command completed with exit code zero.

        @return 零退出且未超时则为 ``True`` / ``True`` only for zero exit without timeout.
        """

        return not self.timed_out and self.exit_code == 0


@dataclass(frozen=True, slots=True)
class AddFileCommand:
    """@brief 将不解释的 byte stream 原子写入受限 Workspace 目标 / Atomically place an uninterpreted byte stream at a constrained Workspace target.

    @param scope 个人或整群的强隔离范围 / Strongly isolated personal-or-whole-group scope.
    @param opaque_id 可信上层生成的、仅用于目录隔离的不透明 ID / Opaque ID generated by a trusted upper layer solely for directory isolation.
    @param chunks 只消费一次的二进制 chunk iterable / Single-consumption iterable of binary chunks.
    @param byte_size 声明的完整文件字节数 / Declared total file byte size.
    @param sha256 完整文件的规范小写 SHA-256 / Canonical lowercase SHA-256 of the complete file.
    @param request_id 可重试上传的稳定 ID / Stable ID of a retryable upload.
    @param request_hash 完整上传意图的 SHA-256 摘要 / SHA-256 digest of the complete upload intent.
    @note ``opaque_id`` 不是文件名，也不能由模型、Telegram 原始路径或 MIME/shebang 派生；目标
        一律为 ``/workspace/uploads/<opaque_id>/payload``。``chunks`` 的内容只能被 native
        ingress 消费一次，adapter 不得为了“检查类型”而预读它。/ ``opaque_id`` is not a
        filename and must not be derived from model, Telegram raw paths, or MIME/shebang; the
        target is always ``/workspace/uploads/<opaque_id>/payload``. The contents of ``chunks``
        may be consumed only once by native ingress; an adapter must not pre-read it merely to
        inspect its type.
    """

    scope: RuntimeScope
    """@brief 文件所属的强类型 runtime scope / Typed runtime scope owning the file."""
    opaque_id: str
    """@brief 可信生成的 opaque directory component / Trusted generated opaque directory component."""
    chunks: Iterable[bytes]
    """@brief 一次性文件 byte stream / Single-use file byte stream."""
    byte_size: int
    """@brief 完整文件的声明字节数 / Declared byte count of the complete file."""
    sha256: str
    """@brief 完整文件的规范小写 SHA-256 / Canonical lowercase SHA-256 of the complete file."""
    request_id: WorkspaceRequestId
    """@brief durable upload invocation ID / Durable upload invocation ID."""
    request_hash: WorkspaceRequestHash
    """@brief durable upload intent hash / Durable upload intent hash."""

    def __post_init__(self) -> None:
        """@brief 验证文件写入意图的边界，不预读 stream / Validate file-ingress boundaries without pre-reading the stream.

        @return None / None.
        @raise TypeError scope、stream、强类型标识或基础类型不正确时抛出 /
            Raised when scope, stream, strong identifiers, or primitive types are invalid.
        @raise ValueError ID、大小或 SHA-256 不符合固定协议时抛出 /
            Raised when the ID, size, or SHA-256 violates the fixed protocol.
        """

        if not isinstance(self.scope, PersonalRuntimeScope | GroupRuntimeScope):
            raise TypeError("AddFileCommand requires a typed workspace runtime scope")
        if not isinstance(self.opaque_id, str):
            raise TypeError("AddFileCommand opaque_id must be a string")
        if _PAYLOAD_ID_PATTERN.fullmatch(self.opaque_id) is None:
            raise ValueError(
                "AddFileCommand opaque_id must be a safe opaque identifier"
            )
        if isinstance(
            self.chunks, str | bytes | bytearray | memoryview
        ) or not isinstance(self.chunks, Iterable):
            raise TypeError("AddFileCommand chunks must be an iterable of bytes chunks")
        if isinstance(self.byte_size, bool) or not isinstance(self.byte_size, int):
            raise TypeError("AddFileCommand byte_size must be an integer")
        if not 0 <= self.byte_size <= MAX_ADD_FILE_BYTES:
            raise ValueError(
                "AddFileCommand byte_size must be within the add_file byte budget"
            )
        if not isinstance(self.sha256, str):
            raise TypeError("AddFileCommand sha256 must be a string")
        if _PAYLOAD_SHA256_PATTERN.fullmatch(self.sha256) is None:
            raise ValueError(
                "AddFileCommand sha256 must be a lowercase SHA-256 hex digest"
            )
        if not isinstance(self.request_id, WorkspaceRequestId):
            raise TypeError("AddFileCommand requires a WorkspaceRequestId")
        if not isinstance(self.request_hash, WorkspaceRequestHash):
            raise TypeError("AddFileCommand requires a WorkspaceRequestHash")

    @property
    def runtime_path(self) -> str:
        """@brief 返回 native 唯一允许发布文件的 runtime 路径 / Return the only runtime path where native may publish the file.

        @return 固定 uploads 树中的文件路径 / File path in the fixed uploads tree.
        """

        return f"/workspace/uploads/{self.opaque_id}/payload"


@dataclass(frozen=True, slots=True)
class ReplayFileCommand:
    """@brief 只读查询既有 native payload journal 的文件意图 / File intent for a read-only lookup of an existing native payload journal.

    @param scope 个人或整群的强隔离范围 / Strongly isolated personal-or-whole-group scope.
    @param opaque_id 可信上层生成的固定 uploads 目录 ID / Trusted fixed uploads-directory ID generated by an upper layer.
    @param byte_size 既有 immutable intent 声明的完整文件字节数 / Complete file byte size declared by the existing immutable intent.
    @param sha256 既有 immutable intent 声明的完整文件 SHA-256 / Complete file SHA-256 declared by the existing immutable intent.
    @param request_id 要查询的稳定 journal 调用 ID / Stable journal invocation ID to query.
    @param request_hash 要查询的完整调用语义 SHA-256 / SHA-256 of complete invocation semantics to query.
    @note 该类型刻意没有 ``chunks``：它只能读取 completed payload journal，绝不能创建
        pending journal、激活 payload stream 或修改 OverlayFS。/ This type intentionally has
        no ``chunks``: it may read only a completed payload journal and must not create a pending
        journal, activate a payload stream, or mutate OverlayFS.
    """

    scope: RuntimeScope
    """@brief 文件所属的强类型 runtime scope / Typed runtime scope owning the file."""
    opaque_id: str
    """@brief 可信固定 opaque directory component / Trusted fixed opaque directory component."""
    byte_size: int
    """@brief immutable intent 声明的完整字节数 / Complete byte count declared by the immutable intent."""
    sha256: str
    """@brief immutable intent 声明的 SHA-256 / SHA-256 declared by the immutable intent."""
    request_id: WorkspaceRequestId
    """@brief 要查询的 durable upload invocation ID / Durable upload invocation ID to query."""
    request_hash: WorkspaceRequestHash
    """@brief 要查询的 durable upload intent hash / Durable upload intent hash to query."""

    def __post_init__(self) -> None:
        """@brief 校验只读 journal 查询边界 / Validate read-only journal-lookup boundaries.

        @return None / None.
        @raise TypeError scope、强类型标识或基础类型不正确时抛出 / Raised when scope, strong identifiers, or primitive types are invalid.
        @raise ValueError ID、大小或 SHA-256 不符合固定协议时抛出 / Raised when ID, size, or SHA-256 violates the fixed protocol.
        """

        if not isinstance(self.scope, PersonalRuntimeScope | GroupRuntimeScope):
            raise TypeError(
                "ReplayFileCommand requires a typed workspace runtime scope"
            )
        if not isinstance(self.opaque_id, str):
            raise TypeError("ReplayFileCommand opaque_id must be a string")
        if _PAYLOAD_ID_PATTERN.fullmatch(self.opaque_id) is None:
            raise ValueError(
                "ReplayFileCommand opaque_id must be a safe opaque identifier"
            )
        if isinstance(self.byte_size, bool) or not isinstance(self.byte_size, int):
            raise TypeError("ReplayFileCommand byte_size must be an integer")
        if not 0 <= self.byte_size <= MAX_ADD_FILE_BYTES:
            raise ValueError(
                "ReplayFileCommand byte_size must be within the add_file byte budget"
            )
        if not isinstance(self.sha256, str):
            raise TypeError("ReplayFileCommand sha256 must be a string")
        if _PAYLOAD_SHA256_PATTERN.fullmatch(self.sha256) is None:
            raise ValueError(
                "ReplayFileCommand sha256 must be a lowercase SHA-256 hex digest"
            )
        if not isinstance(self.request_id, WorkspaceRequestId):
            raise TypeError("ReplayFileCommand requires a WorkspaceRequestId")
        if not isinstance(self.request_hash, WorkspaceRequestHash):
            raise TypeError("ReplayFileCommand requires a WorkspaceRequestHash")

    @property
    def runtime_path(self) -> str:
        """@brief 返回 journal 完成后唯一允许的 runtime 路径 / Return the sole runtime path allowed after journal completion.

        @return 固定 uploads 树中的 payload 路径 / Payload path in the fixed uploads tree.
        """

        return f"/workspace/uploads/{self.opaque_id}/payload"


@dataclass(frozen=True, slots=True)
class AddFileResult:
    """@brief 一次已原子发布或 durable replay 的文件收据 / Receipt for an atomically published or durably replayed file.

    @param request_id 已发布或回放的稳定请求 ID / Stable request ID published or replayed.
    @param replayed 是否由 native 文件 journal 回放 / Whether the native file journal replayed this receipt.
    @param path runtime 内固定文件路径 / Fixed file path inside the runtime.
    @param byte_size 已验证文件的字节数 / Byte count of the verified file.
    @param sha256 已验证文件的规范小写 SHA-256 / Canonical lowercase SHA-256 of the verified file.
    """

    request_id: WorkspaceRequestId
    """@brief durable upload invocation ID / Durable upload invocation ID."""
    replayed: bool
    """@brief 是否来自 durable journal 回放 / Whether this came from durable journal replay."""
    path: str
    """@brief 文件的受限 runtime 路径 / Constrained runtime path of the file."""
    byte_size: int
    """@brief 已发布文件的字节数 / Byte count of the published file."""
    sha256: str
    """@brief 已发布文件的规范小写 SHA-256 / Canonical lowercase SHA-256 of the published file."""

    def __post_init__(self) -> None:
        """@brief 验证 native 文件收据 / Validate the native file receipt.

        @return None / None.
        @raise TypeError 字段类型不符合固定协议时抛出 / Raised when field types violate the fixed protocol.
        @raise ValueError 路径、大小或 SHA-256 不符合固定协议时抛出 /
            Raised when path, size, or SHA-256 violates the fixed protocol.
        """

        if not isinstance(self.request_id, WorkspaceRequestId):
            raise TypeError("AddFileResult requires a WorkspaceRequestId")
        if not isinstance(self.replayed, bool):
            raise TypeError("AddFileResult replayed must be a bool")
        if not isinstance(self.path, str):
            raise TypeError("AddFileResult path must be a string")
        if _PAYLOAD_RUNTIME_PATH_PATTERN.fullmatch(self.path) is None:
            raise ValueError("AddFileResult path is outside the fixed file tree")
        if isinstance(self.byte_size, bool) or not isinstance(self.byte_size, int):
            raise TypeError("AddFileResult byte_size must be an integer")
        if not 0 <= self.byte_size <= MAX_ADD_FILE_BYTES:
            raise ValueError(
                "AddFileResult byte_size must be within the add_file byte budget"
            )
        if not isinstance(self.sha256, str):
            raise TypeError("AddFileResult sha256 must be a string")
        if _PAYLOAD_SHA256_PATTERN.fullmatch(self.sha256) is None:
            raise ValueError(
                "AddFileResult sha256 must be a lowercase SHA-256 hex digest"
            )


def _require_utf8(value: str, *, label: str) -> int:
    """@brief 验证文本可无损传给 native UTF-8 协议 / Verify text can be losslessly sent through the native UTF-8 protocol.

    @param value 待编码文本 / Text to encode.
    @param label 面向开发者的字段名 / Developer-facing field name.
    @return UTF-8 字节数 / UTF-8 byte count.
    @raise ValueError 文本含无法 UTF-8 编码的 surrogate 时抛出 /
        Raised when the text contains a surrogate that cannot be UTF-8 encoded.
    """

    try:
        return len(value.encode("utf-8"))
    except UnicodeEncodeError as error:
        raise ValueError(f"{label} must be valid UTF-8 text") from error


__all__ = [
    "AddFileCommand",
    "AddFileResult",
    "DEFAULT_BASH_OUTPUT_LIMIT_BYTES",
    "DEFAULT_BASH_TIMEOUT_SECONDS",
    "MAX_ADD_FILE_BYTES",
    "MAX_ADD_FILE_CHUNK_BYTES",
    "MAX_BASH_COMMAND_BYTES",
    "MAX_BASH_COMMAND_CHARACTERS",
    "MAX_BASH_OUTPUT_LIMIT_BYTES",
    "MAX_BASH_STDIN_BYTES",
    "MAX_BASH_TIMEOUT_SECONDS",
    "RunBashCommand",
    "RunBashResult",
    "ReplayFileCommand",
]
