# Description: Configuration file for the bot
# replace with secure storage (e.g., environment variable / secrets manager)
from pathlib import Path
from typing import Literal
from urllib.parse import quote_plus

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parents[3]


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=BASE_DIR / ".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    GEMINI_API_KEY: str | None = None
    GEMINI_API_BASE: str | None = None
    GEMINI_OPENAI_COMPATIBLE: bool = False
    GEMINI_CHAT_MODEL: str | None = None
    GEMINI_CHAT_FALLBACK_MODEL: str | None = None
    GEMINI_SUMMARY_MODEL: str | None = None
    GEMINI_SUMMARY_FALLBACK_MODEL: str | None = None
    GEMINI_TRANSLATE_MODEL: str | None = None

    ZAI_API_KEY: str | None = None
    ZAI_API_BASE: str | None = None
    ZHIPU_CHAT_MODEL: str | None = None
    ZHIPU_SUMMARY_MODEL: str | None = None
    ZHIPU_TRANSLATE_MODEL: str | None = None

    SERPAPI_API_KEY: str | None = None
    TELEGRAM_BOT_TOKEN: str | None = None
    TELEGRAM_CONNECT_TIMEOUT: float = 10.0
    TELEGRAM_READ_TIMEOUT: float = 30.0
    TELEGRAM_WRITE_TIMEOUT: float = 30.0
    TELEGRAM_POOL_TIMEOUT: float = 10.0
    TELEGRAM_GET_UPDATES_TIMEOUT: int = 30
    TELEGRAM_GET_UPDATES_CONNECT_TIMEOUT: float = 10.0
    TELEGRAM_GET_UPDATES_READ_TIMEOUT: float = 35.0
    TELEGRAM_GET_UPDATES_WRITE_TIMEOUT: float = 30.0
    TELEGRAM_GET_UPDATES_POOL_TIMEOUT: float = 10.0
    TELEGRAM_GET_UPDATES_CONNECTION_POOL_SIZE: int = 2
    TELEGRAM_POLLING_RETRY_INITIAL_DELAY: float = 1.0
    TELEGRAM_POLLING_RETRY_MAX_DELAY: float = 30.0
    RUNTIME_MAX_CONCURRENCY: int = 32
    RUNTIME_GLOBAL_CAPACITY: int = 512
    RUNTIME_PER_KEY_CAPACITY: int = 8
    RUNTIME_MAILBOX_IDLE_TTL_SECONDS: float = 300.0
    RUNTIME_SHUTDOWN_GRACE_SECONDS: float = 30.0
    SCHEDULING_POLL_INTERVAL: float = 1.0
    SCHEDULING_WORKER_COUNT: int = 3
    SCHEDULING_LEASE_SECONDS: int = 1800
    INBOX_WORKER_COUNT: int = 16
    INBOX_POLL_INTERVAL: float = 0.1
    INBOX_LEASE_SECONDS: int = 60
    INFERENCE_WORKER_COUNT: int = 8
    INFERENCE_POLL_INTERVAL: float = 0.25
    INFERENCE_PROVIDER_TIMEOUT_SECONDS: int = 90
    INFERENCE_LEASE_SECONDS: int = 180
    INFERENCE_ATTEMPT_TIMEOUT_SECONDS: int = 120
    OUTBOX_WORKER_COUNT: int = 16
    OUTBOX_POLL_INTERVAL: float = 0.1
    OUTBOX_LEASE_SECONDS: int = 60
    OUTBOX_ATTEMPT_TIMEOUT_SECONDS: int = 25
    COMPACTION_WORKER_COUNT: int = 2
    COMPACTION_POLL_INTERVAL: float = 0.5
    COMPACTION_PROVIDER_TIMEOUT_SECONDS: int = 30
    COMPACTION_ATTEMPT_TIMEOUT_SECONDS: int = 120
    COMPACTION_LEASE_SECONDS: int = 180
    RETRIEVAL_WORKER_COUNT: int = 2
    RETRIEVAL_BATCH_SIZE: int = 16
    RETRIEVAL_POLL_INTERVAL: float = 0.5
    RETRIEVAL_LEASE_SECONDS: int = 120
    RETRIEVAL_EMBEDDING_API_KEY: str | None = None
    RETRIEVAL_EMBEDDING_API_BASE: str = "https://openrouter.ai/api/v1"
    RETRIEVAL_EMBEDDING_MODEL: str = "qwen/qwen3-embedding-8b"
    RETRIEVAL_EMBEDDING_SPACE_ID: str = "qwen3-embedding-8b.1024.episodic-v1"
    RETRIEVAL_EMBEDDING_DIMENSIONS: Literal[1024] = 1024
    RETRIEVAL_EMBEDDING_TIMEOUT_SECONDS: float = 30.0
    RETRIEVAL_QUERY_INSTRUCTION: str = (
        "Retrieve prior conversation evidence relevant to the user's current question, "
        "including events, decisions, preferences, corrections, and temporal context."
    )
    CONVERSATION_HISTORY_CACHE_CAPACITY: int = 256
    CONVERSATION_HISTORY_CACHE_TTL_SECONDS: float = 900.0
    NETWORK_PROXY_URL: str | None = None

    OPENAI_API_KEY: str | None = None
    OPENAI_BASE_URL: str | None = None
    OPENAI_CHAT_MODEL: str | None = None
    OPENAI_SUMMARY_MODEL: str | None = None
    OPENAI_TRANSLATE_MODEL: str | None = None

    OPENROUTER_API_KEY: str | None = None
    OPENROUTER_API_BASE: str | None = None
    OPENROUTER_CHAT_MODEL: str | None = None
    OPENROUTER_SUMMARY_MODEL: str | None = None
    OPENROUTER_TRANSLATE_MODEL: str | None = None

    AZURE_OPENAI_API_KEY: str | None = None
    AZURE_OPENAI_API_ENDPOINT: str | None = None
    AZURE_OPENAI_API_VERSION: str | None = None
    AZURE_OPENAI_DEPLOYMENT: str | None = None
    AZURE_OPENAI_BASE_URL: str | None = None
    AZURE_OPENAI_CHAT_MODEL: str | None = None
    AZURE_OPENAI_SUMMARY_MODEL: str | None = None
    AZURE_OPENAI_TRANSLATE_MODEL: str | None = None

    SILICONFLOW_API_KEY: str | None = None
    SILICONFLOW_API_BASE: str = "https://api.siliconflow.cn/v1"
    SILICONFLOW_CHAT_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"
    SILICONFLOW_SUMMARY_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"
    SILICONFLOW_TRANSLATE_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"

    AI_SUMMARY_PROVIDER: str | None = None
    AI_SUMMARY_FALLBACK_PROVIDER: str | None = None
    AI_TRANSLATE_PROVIDER: str | None = None
    AI_TRANSLATE_FALLBACK_PROVIDER: str | None = None
    AI_CHAT_ORDER: str = ""
    AI_CHAT_TEXT_ONLY_MODELS: str = "deepseek-ai/DeepSeek-V4-Flash"

    # Token estimates apply DEFAULT_GUARD_RATIO before comparing these limits.
    CHAT_TOKEN_WARN_LIMIT: int = 114000
    CHAT_TOKEN_LIMIT: int = 120000
    CHAT_RESERVED_TOKENS: int = 8192

    JUDGE0_API_URL: str = "https://ce.judge0.com"
    JUDGE0_API_KEY: str | None = None

    IMAGE_GEN_API_URL: str = ""
    IMAGE_GEN_API_TOKEN: str = ""
    IMAGE_GEN_TIMEOUT: int = 30

    FISH_AUDIO_API_KEY: str | None = None
    FISH_AUDIO_MODEL: str = "s2.1-pro-free"
    FISH_AUDIO_REFERENCE_ID: str = "dc020cb237df4248907565718715b20b"

    ADMIN_USER_ID: int = 1002288404
    ADMIN_CONTACT_NAME: str | None = None
    NEW_USER_BONUS_COINS: int = 10

    POSTGRES_HOST: str | None = None
    POSTGRES_USER: str | None = None
    POSTGRES_PASSWORD: str | None = None
    POSTGRES_DATABASE: str | None = None
    POSTGRES_PORT: int | None = None
    DB_POOL_SIZE: int = 5
    DB_MAX_OVERFLOW: int = 10
    DB_POOL_RECYCLE: int = 1800
    DB_CONNECT_TIMEOUT: int = 10
    DB_SEARCH_PATH: str = "identity,conversation,assistant,economy,moderation,crypto,game,media,admin,public"
    DATABASE_URL: str | None = None

    LOG_LEVEL: str = "INFO"
    LOG_FILE_MAX_BYTES: int = 1 * 1024 * 1024
    LOG_FILE_BACKUP_COUNT: int = 5
    LOG_QUEUE_MAX_SIZE: int = 10_000

    OBSERVABILITY_ENABLED: bool = True
    OBSERVABILITY_ENVIRONMENT: str = "production"
    OBSERVABILITY_QUEUE_CAPACITY: int = 20_000
    OBSERVABILITY_BATCH_SIZE: int = 250
    OBSERVABILITY_FLUSH_INTERVAL_SECONDS: float = 1.0
    OBSERVABILITY_RETRY_MAX_DELAY_SECONDS: float = 30.0
    OBSERVABILITY_SHUTDOWN_FLUSH_TIMEOUT_SECONDS: float = 3.0
    OBSERVABILITY_DB_COMMAND_TIMEOUT_SECONDS: float = 2.0
    OBSERVABILITY_METRIC_INTERVAL_SECONDS: float = 15.0
    OBSERVABILITY_RETENTION_DAYS: int = 30

    @field_validator("GEMINI_OPENAI_COMPATIBLE", mode="before")
    @classmethod
    def _parse_gemini_openai_compatible(cls, value: object) -> bool:
        if value is None:
            return False
        if isinstance(value, bool):
            return value
        return str(value).strip().lower() in {
            "1",
            "true",
            "yes",
            "on",
        }

    @field_validator("POSTGRES_PORT", mode="before")
    @classmethod
    def _parse_optional_port(cls, value: object) -> object:
        if value is None:
            return None
        if isinstance(value, str) and not value.strip():
            return None
        return value

    @field_validator("ADMIN_CONTACT_NAME", mode="before")
    @classmethod
    def _parse_optional_administrator_contact_name(cls, value: object) -> str | None:
        """@brief 规范化管理员展示名回退配置 / Normalize the administrator display-name fallback.

        @param value 环境变量原值 / Raw environment-variable value.
        @return 去除首尾空白的名称；空值为 None / Trimmed name, or None for a blank value.
        """

        if value is None:
            return None
        normalized = str(value).strip()
        return normalized or None


SETTINGS = AppSettings()


GEMINI_API_KEY = SETTINGS.GEMINI_API_KEY
GEMINI_API_BASE = SETTINGS.GEMINI_API_BASE
GEMINI_OPENAI_COMPATIBLE = SETTINGS.GEMINI_OPENAI_COMPATIBLE
GEMINI_CHAT_MODEL = SETTINGS.GEMINI_CHAT_MODEL
GEMINI_CHAT_FALLBACK_MODEL = SETTINGS.GEMINI_CHAT_FALLBACK_MODEL
GEMINI_SUMMARY_MODEL = SETTINGS.GEMINI_SUMMARY_MODEL
GEMINI_SUMMARY_FALLBACK_MODEL = SETTINGS.GEMINI_SUMMARY_FALLBACK_MODEL
GEMINI_TRANSLATE_MODEL = SETTINGS.GEMINI_TRANSLATE_MODEL

ZAI_API_KEY = SETTINGS.ZAI_API_KEY
ZAI_API_BASE = SETTINGS.ZAI_API_BASE
ZHIPU_CHAT_MODEL = SETTINGS.ZHIPU_CHAT_MODEL
ZHIPU_SUMMARY_MODEL = SETTINGS.ZHIPU_SUMMARY_MODEL
ZHIPU_TRANSLATE_MODEL = SETTINGS.ZHIPU_TRANSLATE_MODEL
SERPAPI_API_KEY = SETTINGS.SERPAPI_API_KEY
TELEGRAM_BOT_TOKEN = SETTINGS.TELEGRAM_BOT_TOKEN
TELEGRAM_CONNECT_TIMEOUT = SETTINGS.TELEGRAM_CONNECT_TIMEOUT
TELEGRAM_READ_TIMEOUT = SETTINGS.TELEGRAM_READ_TIMEOUT
TELEGRAM_WRITE_TIMEOUT = SETTINGS.TELEGRAM_WRITE_TIMEOUT
TELEGRAM_POOL_TIMEOUT = SETTINGS.TELEGRAM_POOL_TIMEOUT
TELEGRAM_GET_UPDATES_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_TIMEOUT
TELEGRAM_GET_UPDATES_CONNECT_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_CONNECT_TIMEOUT
TELEGRAM_GET_UPDATES_READ_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_READ_TIMEOUT
TELEGRAM_GET_UPDATES_WRITE_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_WRITE_TIMEOUT
TELEGRAM_GET_UPDATES_POOL_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_POOL_TIMEOUT
TELEGRAM_GET_UPDATES_CONNECTION_POOL_SIZE = (
    SETTINGS.TELEGRAM_GET_UPDATES_CONNECTION_POOL_SIZE
)
TELEGRAM_POLLING_RETRY_INITIAL_DELAY = SETTINGS.TELEGRAM_POLLING_RETRY_INITIAL_DELAY
TELEGRAM_POLLING_RETRY_MAX_DELAY = SETTINGS.TELEGRAM_POLLING_RETRY_MAX_DELAY
RUNTIME_MAX_CONCURRENCY = SETTINGS.RUNTIME_MAX_CONCURRENCY
RUNTIME_GLOBAL_CAPACITY = SETTINGS.RUNTIME_GLOBAL_CAPACITY
RUNTIME_PER_KEY_CAPACITY = SETTINGS.RUNTIME_PER_KEY_CAPACITY
RUNTIME_MAILBOX_IDLE_TTL_SECONDS = SETTINGS.RUNTIME_MAILBOX_IDLE_TTL_SECONDS
RUNTIME_SHUTDOWN_GRACE_SECONDS = SETTINGS.RUNTIME_SHUTDOWN_GRACE_SECONDS
SCHEDULING_POLL_INTERVAL = SETTINGS.SCHEDULING_POLL_INTERVAL
SCHEDULING_WORKER_COUNT = SETTINGS.SCHEDULING_WORKER_COUNT
SCHEDULING_LEASE_SECONDS = SETTINGS.SCHEDULING_LEASE_SECONDS
INBOX_WORKER_COUNT = SETTINGS.INBOX_WORKER_COUNT
INBOX_POLL_INTERVAL = SETTINGS.INBOX_POLL_INTERVAL
INBOX_LEASE_SECONDS = SETTINGS.INBOX_LEASE_SECONDS
INFERENCE_WORKER_COUNT = SETTINGS.INFERENCE_WORKER_COUNT
INFERENCE_POLL_INTERVAL = SETTINGS.INFERENCE_POLL_INTERVAL
INFERENCE_PROVIDER_TIMEOUT_SECONDS = SETTINGS.INFERENCE_PROVIDER_TIMEOUT_SECONDS
INFERENCE_LEASE_SECONDS = SETTINGS.INFERENCE_LEASE_SECONDS
INFERENCE_ATTEMPT_TIMEOUT_SECONDS = SETTINGS.INFERENCE_ATTEMPT_TIMEOUT_SECONDS
OUTBOX_WORKER_COUNT = SETTINGS.OUTBOX_WORKER_COUNT
OUTBOX_POLL_INTERVAL = SETTINGS.OUTBOX_POLL_INTERVAL
OUTBOX_LEASE_SECONDS = SETTINGS.OUTBOX_LEASE_SECONDS
OUTBOX_ATTEMPT_TIMEOUT_SECONDS = SETTINGS.OUTBOX_ATTEMPT_TIMEOUT_SECONDS
COMPACTION_WORKER_COUNT = SETTINGS.COMPACTION_WORKER_COUNT
COMPACTION_POLL_INTERVAL = SETTINGS.COMPACTION_POLL_INTERVAL
COMPACTION_PROVIDER_TIMEOUT_SECONDS = SETTINGS.COMPACTION_PROVIDER_TIMEOUT_SECONDS
COMPACTION_ATTEMPT_TIMEOUT_SECONDS = SETTINGS.COMPACTION_ATTEMPT_TIMEOUT_SECONDS
COMPACTION_LEASE_SECONDS = SETTINGS.COMPACTION_LEASE_SECONDS
RETRIEVAL_WORKER_COUNT = SETTINGS.RETRIEVAL_WORKER_COUNT
RETRIEVAL_BATCH_SIZE = SETTINGS.RETRIEVAL_BATCH_SIZE
RETRIEVAL_POLL_INTERVAL = SETTINGS.RETRIEVAL_POLL_INTERVAL
RETRIEVAL_LEASE_SECONDS = SETTINGS.RETRIEVAL_LEASE_SECONDS
RETRIEVAL_EMBEDDING_API_KEY = SETTINGS.RETRIEVAL_EMBEDDING_API_KEY
RETRIEVAL_EMBEDDING_API_BASE = SETTINGS.RETRIEVAL_EMBEDDING_API_BASE
RETRIEVAL_EMBEDDING_MODEL = SETTINGS.RETRIEVAL_EMBEDDING_MODEL
RETRIEVAL_EMBEDDING_SPACE_ID = SETTINGS.RETRIEVAL_EMBEDDING_SPACE_ID
RETRIEVAL_EMBEDDING_DIMENSIONS = SETTINGS.RETRIEVAL_EMBEDDING_DIMENSIONS
RETRIEVAL_EMBEDDING_TIMEOUT_SECONDS = SETTINGS.RETRIEVAL_EMBEDDING_TIMEOUT_SECONDS
RETRIEVAL_QUERY_INSTRUCTION = SETTINGS.RETRIEVAL_QUERY_INSTRUCTION
CONVERSATION_HISTORY_CACHE_CAPACITY = SETTINGS.CONVERSATION_HISTORY_CACHE_CAPACITY
CONVERSATION_HISTORY_CACHE_TTL_SECONDS = SETTINGS.CONVERSATION_HISTORY_CACHE_TTL_SECONDS
NETWORK_PROXY_URL = SETTINGS.NETWORK_PROXY_URL
OPENAI_API_KEY = SETTINGS.OPENAI_API_KEY
OPENAI_BASE_URL = SETTINGS.OPENAI_BASE_URL
OPENAI_CHAT_MODEL = SETTINGS.OPENAI_CHAT_MODEL
OPENAI_SUMMARY_MODEL = SETTINGS.OPENAI_SUMMARY_MODEL
OPENAI_TRANSLATE_MODEL = SETTINGS.OPENAI_TRANSLATE_MODEL
OPENROUTER_API_KEY = SETTINGS.OPENROUTER_API_KEY
OPENROUTER_API_BASE = SETTINGS.OPENROUTER_API_BASE
OPENROUTER_CHAT_MODEL = SETTINGS.OPENROUTER_CHAT_MODEL
OPENROUTER_SUMMARY_MODEL = SETTINGS.OPENROUTER_SUMMARY_MODEL
OPENROUTER_TRANSLATE_MODEL = SETTINGS.OPENROUTER_TRANSLATE_MODEL
AZURE_OPENAI_API_KEY = SETTINGS.AZURE_OPENAI_API_KEY
AZURE_OPENAI_API_ENDPOINT = SETTINGS.AZURE_OPENAI_API_ENDPOINT
AZURE_OPENAI_API_VERSION = SETTINGS.AZURE_OPENAI_API_VERSION
AZURE_OPENAI_DEPLOYMENT = SETTINGS.AZURE_OPENAI_DEPLOYMENT
AZURE_OPENAI_CHAT_MODEL = SETTINGS.AZURE_OPENAI_CHAT_MODEL
AZURE_OPENAI_SUMMARY_MODEL = SETTINGS.AZURE_OPENAI_SUMMARY_MODEL
AZURE_OPENAI_TRANSLATE_MODEL = SETTINGS.AZURE_OPENAI_TRANSLATE_MODEL

SILICONFLOW_API_KEY = SETTINGS.SILICONFLOW_API_KEY
SILICONFLOW_API_BASE = SETTINGS.SILICONFLOW_API_BASE
SILICONFLOW_CHAT_MODEL = SETTINGS.SILICONFLOW_CHAT_MODEL
SILICONFLOW_SUMMARY_MODEL = SETTINGS.SILICONFLOW_SUMMARY_MODEL
SILICONFLOW_TRANSLATE_MODEL = SETTINGS.SILICONFLOW_TRANSLATE_MODEL


def _build_azure_base_url() -> str:
    if not AZURE_OPENAI_API_ENDPOINT or not AZURE_OPENAI_DEPLOYMENT:
        return ""
    return (
        f"{AZURE_OPENAI_API_ENDPOINT.rstrip('/')}/openai/deployments/"
        f"{AZURE_OPENAI_DEPLOYMENT}"
    )


AZURE_OPENAI_BASE_URL = SETTINGS.AZURE_OPENAI_BASE_URL or _build_azure_base_url()

AI_SUMMARY_PROVIDER = SETTINGS.AI_SUMMARY_PROVIDER
AI_SUMMARY_FALLBACK_PROVIDER = SETTINGS.AI_SUMMARY_FALLBACK_PROVIDER
AI_TRANSLATE_PROVIDER = SETTINGS.AI_TRANSLATE_PROVIDER
AI_TRANSLATE_FALLBACK_PROVIDER = SETTINGS.AI_TRANSLATE_FALLBACK_PROVIDER

CHAT_TOKEN_WARN_LIMIT = SETTINGS.CHAT_TOKEN_WARN_LIMIT
CHAT_TOKEN_LIMIT = SETTINGS.CHAT_TOKEN_LIMIT
CHAT_RESERVED_TOKENS = SETTINGS.CHAT_RESERVED_TOKENS

JUDGE0_API_URL = SETTINGS.JUDGE0_API_URL
JUDGE0_API_KEY = SETTINGS.JUDGE0_API_KEY

IMAGE_GEN_API_URL = SETTINGS.IMAGE_GEN_API_URL
IMAGE_GEN_API_TOKEN = SETTINGS.IMAGE_GEN_API_TOKEN
IMAGE_GEN_TIMEOUT = SETTINGS.IMAGE_GEN_TIMEOUT
FISH_AUDIO_API_KEY = SETTINGS.FISH_AUDIO_API_KEY
FISH_AUDIO_MODEL = SETTINGS.FISH_AUDIO_MODEL
FISH_AUDIO_REFERENCE_ID = SETTINGS.FISH_AUDIO_REFERENCE_ID

ADMIN_USER_ID = SETTINGS.ADMIN_USER_ID
ADMIN_CONTACT_NAME = SETTINGS.ADMIN_CONTACT_NAME
NEW_USER_BONUS_COINS = SETTINGS.NEW_USER_BONUS_COINS

POSTGRES_CONFIG = {
    "host": SETTINGS.POSTGRES_HOST,
    "user": SETTINGS.POSTGRES_USER,
    "password": SETTINGS.POSTGRES_PASSWORD,
    "database": SETTINGS.POSTGRES_DATABASE,
}

DB_POOL_SIZE = SETTINGS.DB_POOL_SIZE
DB_MAX_OVERFLOW = SETTINGS.DB_MAX_OVERFLOW
DB_POOL_RECYCLE = SETTINGS.DB_POOL_RECYCLE
DB_CONNECT_TIMEOUT = SETTINGS.DB_CONNECT_TIMEOUT
DB_SEARCH_PATH = SETTINGS.DB_SEARCH_PATH


def _build_postgres_dsn() -> str:
    user = POSTGRES_CONFIG.get("user") or "postgres"
    password = POSTGRES_CONFIG.get("password") or ""
    host = POSTGRES_CONFIG.get("host") or "localhost"
    database = POSTGRES_CONFIG.get("database") or "fogmoe"
    port = SETTINGS.POSTGRES_PORT or 5432

    auth = user
    if password:
        auth = f"{user}:{quote_plus(password)}"

    location = f"{host}:{port}" if port else host
    return f"postgresql+asyncpg://{auth}@{location}/{database}"


SQLALCHEMY_DATABASE_URI = SETTINGS.DATABASE_URL or _build_postgres_dsn()

# 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
LOG_LEVEL = SETTINGS.LOG_LEVEL
LOG_DIR = BASE_DIR / "logs"
LOG_FILE_MAX_BYTES = SETTINGS.LOG_FILE_MAX_BYTES
LOG_FILE_BACKUP_COUNT = SETTINGS.LOG_FILE_BACKUP_COUNT
LOG_QUEUE_MAX_SIZE = SETTINGS.LOG_QUEUE_MAX_SIZE

OBSERVABILITY_ENABLED = SETTINGS.OBSERVABILITY_ENABLED
OBSERVABILITY_ENVIRONMENT = SETTINGS.OBSERVABILITY_ENVIRONMENT
OBSERVABILITY_QUEUE_CAPACITY = SETTINGS.OBSERVABILITY_QUEUE_CAPACITY
OBSERVABILITY_BATCH_SIZE = SETTINGS.OBSERVABILITY_BATCH_SIZE
OBSERVABILITY_FLUSH_INTERVAL_SECONDS = SETTINGS.OBSERVABILITY_FLUSH_INTERVAL_SECONDS
OBSERVABILITY_RETRY_MAX_DELAY_SECONDS = SETTINGS.OBSERVABILITY_RETRY_MAX_DELAY_SECONDS
OBSERVABILITY_SHUTDOWN_FLUSH_TIMEOUT_SECONDS = (
    SETTINGS.OBSERVABILITY_SHUTDOWN_FLUSH_TIMEOUT_SECONDS
)
OBSERVABILITY_DB_COMMAND_TIMEOUT_SECONDS = (
    SETTINGS.OBSERVABILITY_DB_COMMAND_TIMEOUT_SECONDS
)
OBSERVABILITY_METRIC_INTERVAL_SECONDS = SETTINGS.OBSERVABILITY_METRIC_INTERVAL_SECONDS
OBSERVABILITY_RETENTION_DAYS = SETTINGS.OBSERVABILITY_RETENTION_DAYS


def asyncpg_database_uri() -> str:
    """@brief 返回 asyncpg 原生数据库 URI / Return the native asyncpg database URI.

    @return 不含 SQLAlchemy driver 标记的 URI / URI without the SQLAlchemy driver marker.
    """

    return SQLALCHEMY_DATABASE_URI.replace(
        "postgresql+asyncpg://",
        "postgresql://",
        1,
    )


def _read_text_resource(relative_path: str) -> str:
    return (BASE_DIR / relative_path).read_text(encoding="utf-8")


# help 命令的帮助信息
HELP_TEXT = _read_text_resource("resources/telegram_help.md")

# AI 系统提示词：人设与运行契约都由受版本控制的资源文件提供。
SYSTEM_PROMPT = _read_text_resource("resources/prompts/system_prompt.md")


def _parse_csv_value(raw_value: str | None) -> list[str]:
    if not raw_value:
        return []
    values = [item.strip().lower() for item in raw_value.split(",") if item.strip()]
    return values


# AI 服务的排序，按照优先级从高到低排序
AI_SERVICE_ORDER = _parse_csv_value(SETTINGS.AI_CHAT_ORDER)
AI_CHAT_TEXT_ONLY_MODELS = _parse_csv_value(SETTINGS.AI_CHAT_TEXT_ONLY_MODELS)
