# Description: Configuration file for the bot
# replace with secure storage (e.g., environment variable / secrets manager)
from pathlib import Path
from urllib.parse import quote_plus

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parents[3]


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=BASE_DIR / ".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    GEMINI_API_KEY: str | None = None
    GEMINI_API_BASE: str | None = None
    GEMINI_OPENAI_COMPATIBLE: bool = False
    GEMINI_CHAT_MODEL: str | None = None
    GEMINI_CHAT_FALLBACK_MODEL: str | None = None
    GEMINI_SUMMARY_MODEL: str | None = None
    GEMINI_SUMMARY_FALLBACK_MODEL: str | None = None
    GEMINI_TRANSLATE_MODEL: str | None = None
    GEMINI_VISION_MODEL: str | None = None
    GEMINI_CLASSIFIER_MODEL: str | None = None

    ZAI_API_KEY: str | None = None
    ZAI_API_BASE: str | None = None
    ZHIPU_CHAT_MODEL: str | None = None
    ZHIPU_SUMMARY_MODEL: str | None = None
    ZHIPU_TRANSLATE_MODEL: str | None = None
    ZHIPU_VISION_MODEL: str | None = None
    ZHIPU_CLASSIFIER_MODEL: str | None = None

    SERPAPI_API_KEY: str | None = None
    TELEGRAM_BOT_TOKEN: str | None = None
    TELEGRAM_CONNECT_TIMEOUT: float = 10.0
    TELEGRAM_READ_TIMEOUT: float = 30.0
    TELEGRAM_WRITE_TIMEOUT: float = 30.0
    TELEGRAM_POOL_TIMEOUT: float = 10.0
    TELEGRAM_GET_UPDATES_TIMEOUT: int = 30
    TELEGRAM_GET_UPDATES_CONNECT_TIMEOUT: float = 10.0
    TELEGRAM_GET_UPDATES_READ_TIMEOUT: float = 35.0
    TELEGRAM_GET_UPDATES_WRITE_TIMEOUT: float = 30.0
    TELEGRAM_GET_UPDATES_POOL_TIMEOUT: float = 10.0
    NETWORK_PROXY_URL: str | None = None

    OPENAI_API_KEY: str | None = None
    OPENAI_BASE_URL: str | None = None
    OPENAI_CHAT_MODEL: str | None = None
    OPENAI_SUMMARY_MODEL: str | None = None
    OPENAI_TRANSLATE_MODEL: str | None = None
    OPENAI_VISION_MODEL: str | None = None
    OPENAI_CLASSIFIER_MODEL: str | None = None

    OPENROUTER_API_KEY: str | None = None
    OPENROUTER_API_BASE: str | None = None
    OPENROUTER_CHAT_MODEL: str | None = None
    OPENROUTER_SUMMARY_MODEL: str | None = None
    OPENROUTER_TRANSLATE_MODEL: str | None = None
    OPENROUTER_VISION_MODEL: str | None = None
    OPENROUTER_CLASSIFIER_MODEL: str | None = None

    AZURE_OPENAI_API_KEY: str | None = None
    AZURE_OPENAI_API_ENDPOINT: str | None = None
    AZURE_OPENAI_API_VERSION: str | None = None
    AZURE_OPENAI_DEPLOYMENT: str | None = None
    AZURE_OPENAI_BASE_URL: str | None = None
    AZURE_OPENAI_CHAT_MODEL: str | None = None
    AZURE_OPENAI_SUMMARY_MODEL: str | None = None
    AZURE_OPENAI_TRANSLATE_MODEL: str | None = None
    AZURE_OPENAI_VISION_MODEL: str | None = None
    AZURE_OPENAI_CLASSIFIER_MODEL: str | None = None

    SILICONFLOW_API_KEY: str | None = None
    SILICONFLOW_API_BASE: str = "https://api.siliconflow.cn/v1"
    SILICONFLOW_CHAT_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"
    SILICONFLOW_SUMMARY_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"
    SILICONFLOW_TRANSLATE_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"
    SILICONFLOW_VISION_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"
    SILICONFLOW_CLASSIFIER_MODEL: str = "deepseek-ai/DeepSeek-V4-Flash"

    AI_SUMMARY_PROVIDER: str | None = None
    AI_SUMMARY_FALLBACK_PROVIDER: str | None = None
    AI_TRANSLATE_PROVIDER: str | None = None
    AI_TRANSLATE_FALLBACK_PROVIDER: str | None = None
    AI_VISION_PROVIDER: str | None = None
    AI_VISION_FALLBACK_PROVIDER: str | None = None
    AI_CLASSIFIER_PROVIDER: str | None = None
    AI_CLASSIFIER_FALLBACK_PROVIDER: str | None = None
    AI_CHAT_ORDER: str = ""
    AI_CHAT_TEXT_ONLY_MODELS: str = "deepseek-ai/DeepSeek-V4-Flash"

    # Token estimates apply DEFAULT_GUARD_RATIO before comparing these limits.
    CHAT_TOKEN_WARN_LIMIT: int = 114000
    CHAT_TOKEN_LIMIT: int = 120000
    CHAT_BATCH_WINDOW_SECONDS: float = 1.0

    JUDGE0_API_URL: str = "https://ce.judge0.com"
    JUDGE0_API_KEY: str | None = None
    E2B_API_KEY: str | None = None

    IMAGE_GEN_API_URL: str = ""
    IMAGE_GEN_API_TOKEN: str = ""
    IMAGE_GEN_TIMEOUT: int = 30

    FISH_AUDIO_API_KEY: str | None = None
    FISH_AUDIO_MODEL: str = "s2.1-pro-free"
    FISH_AUDIO_REFERENCE_ID: str = "dc020cb237df4248907565718715b20b"

    ADMIN_USER_ID: int = 1002288404
    NEW_USER_BONUS_COINS: int = 10

    POSTGRES_HOST: str | None = None
    POSTGRES_USER: str | None = None
    POSTGRES_PASSWORD: str | None = None
    POSTGRES_DATABASE: str | None = None
    POSTGRES_PORT: int | None = None
    DB_POOL_SIZE: int = 5
    DB_MAX_OVERFLOW: int = 10
    DB_POOL_RECYCLE: int = 1800
    DB_CONNECT_TIMEOUT: int = 10
    DB_SEARCH_PATH: str = "identity,conversation,assistant,economy,moderation,crypto,game,public"
    DATABASE_URL: str | None = None

    LOG_LEVEL: str = "INFO"

    @field_validator("GEMINI_OPENAI_COMPATIBLE", mode="before")
    @classmethod
    def _parse_gemini_openai_compatible(cls, value: object) -> bool:
        if value is None:
            return False
        if isinstance(value, bool):
            return value
        return str(value).strip().lower() in {
            "1",
            "true",
            "yes",
            "on",
        }

    @field_validator("POSTGRES_PORT", mode="before")
    @classmethod
    def _parse_optional_port(cls, value: object) -> object:
        if value is None:
            return None
        if isinstance(value, str) and not value.strip():
            return None
        return value

SETTINGS = AppSettings()


GEMINI_API_KEY = SETTINGS.GEMINI_API_KEY
GEMINI_API_BASE = SETTINGS.GEMINI_API_BASE
GEMINI_OPENAI_COMPATIBLE = SETTINGS.GEMINI_OPENAI_COMPATIBLE
GEMINI_CHAT_MODEL = SETTINGS.GEMINI_CHAT_MODEL
GEMINI_CHAT_FALLBACK_MODEL = SETTINGS.GEMINI_CHAT_FALLBACK_MODEL
GEMINI_SUMMARY_MODEL = SETTINGS.GEMINI_SUMMARY_MODEL
GEMINI_SUMMARY_FALLBACK_MODEL = SETTINGS.GEMINI_SUMMARY_FALLBACK_MODEL
GEMINI_TRANSLATE_MODEL = SETTINGS.GEMINI_TRANSLATE_MODEL
GEMINI_VISION_MODEL = SETTINGS.GEMINI_VISION_MODEL
GEMINI_CLASSIFIER_MODEL = SETTINGS.GEMINI_CLASSIFIER_MODEL

ZAI_API_KEY = SETTINGS.ZAI_API_KEY
ZAI_API_BASE = SETTINGS.ZAI_API_BASE
ZHIPU_CHAT_MODEL = SETTINGS.ZHIPU_CHAT_MODEL
ZHIPU_SUMMARY_MODEL = SETTINGS.ZHIPU_SUMMARY_MODEL
ZHIPU_TRANSLATE_MODEL = SETTINGS.ZHIPU_TRANSLATE_MODEL
ZHIPU_VISION_MODEL = SETTINGS.ZHIPU_VISION_MODEL
ZHIPU_CLASSIFIER_MODEL = SETTINGS.ZHIPU_CLASSIFIER_MODEL
SERPAPI_API_KEY = SETTINGS.SERPAPI_API_KEY
TELEGRAM_BOT_TOKEN = SETTINGS.TELEGRAM_BOT_TOKEN
TELEGRAM_CONNECT_TIMEOUT = SETTINGS.TELEGRAM_CONNECT_TIMEOUT
TELEGRAM_READ_TIMEOUT = SETTINGS.TELEGRAM_READ_TIMEOUT
TELEGRAM_WRITE_TIMEOUT = SETTINGS.TELEGRAM_WRITE_TIMEOUT
TELEGRAM_POOL_TIMEOUT = SETTINGS.TELEGRAM_POOL_TIMEOUT
TELEGRAM_GET_UPDATES_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_TIMEOUT
TELEGRAM_GET_UPDATES_CONNECT_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_CONNECT_TIMEOUT
TELEGRAM_GET_UPDATES_READ_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_READ_TIMEOUT
TELEGRAM_GET_UPDATES_WRITE_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_WRITE_TIMEOUT
TELEGRAM_GET_UPDATES_POOL_TIMEOUT = SETTINGS.TELEGRAM_GET_UPDATES_POOL_TIMEOUT
NETWORK_PROXY_URL = SETTINGS.NETWORK_PROXY_URL
OPENAI_API_KEY = SETTINGS.OPENAI_API_KEY
OPENAI_BASE_URL = SETTINGS.OPENAI_BASE_URL
OPENAI_CHAT_MODEL = SETTINGS.OPENAI_CHAT_MODEL
OPENAI_SUMMARY_MODEL = SETTINGS.OPENAI_SUMMARY_MODEL
OPENAI_TRANSLATE_MODEL = SETTINGS.OPENAI_TRANSLATE_MODEL
OPENAI_VISION_MODEL = SETTINGS.OPENAI_VISION_MODEL
OPENAI_CLASSIFIER_MODEL = SETTINGS.OPENAI_CLASSIFIER_MODEL
OPENROUTER_API_KEY = SETTINGS.OPENROUTER_API_KEY
OPENROUTER_API_BASE = SETTINGS.OPENROUTER_API_BASE
OPENROUTER_CHAT_MODEL = SETTINGS.OPENROUTER_CHAT_MODEL
OPENROUTER_SUMMARY_MODEL = SETTINGS.OPENROUTER_SUMMARY_MODEL
OPENROUTER_TRANSLATE_MODEL = SETTINGS.OPENROUTER_TRANSLATE_MODEL
OPENROUTER_VISION_MODEL = SETTINGS.OPENROUTER_VISION_MODEL
OPENROUTER_CLASSIFIER_MODEL = SETTINGS.OPENROUTER_CLASSIFIER_MODEL
AZURE_OPENAI_API_KEY = SETTINGS.AZURE_OPENAI_API_KEY
AZURE_OPENAI_API_ENDPOINT = SETTINGS.AZURE_OPENAI_API_ENDPOINT
AZURE_OPENAI_API_VERSION = SETTINGS.AZURE_OPENAI_API_VERSION
AZURE_OPENAI_DEPLOYMENT = SETTINGS.AZURE_OPENAI_DEPLOYMENT
AZURE_OPENAI_CHAT_MODEL = SETTINGS.AZURE_OPENAI_CHAT_MODEL
AZURE_OPENAI_SUMMARY_MODEL = SETTINGS.AZURE_OPENAI_SUMMARY_MODEL
AZURE_OPENAI_TRANSLATE_MODEL = SETTINGS.AZURE_OPENAI_TRANSLATE_MODEL
AZURE_OPENAI_VISION_MODEL = SETTINGS.AZURE_OPENAI_VISION_MODEL
AZURE_OPENAI_CLASSIFIER_MODEL = SETTINGS.AZURE_OPENAI_CLASSIFIER_MODEL

SILICONFLOW_API_KEY = SETTINGS.SILICONFLOW_API_KEY
SILICONFLOW_API_BASE = SETTINGS.SILICONFLOW_API_BASE
SILICONFLOW_CHAT_MODEL = SETTINGS.SILICONFLOW_CHAT_MODEL
SILICONFLOW_SUMMARY_MODEL = SETTINGS.SILICONFLOW_SUMMARY_MODEL
SILICONFLOW_TRANSLATE_MODEL = SETTINGS.SILICONFLOW_TRANSLATE_MODEL
SILICONFLOW_VISION_MODEL = SETTINGS.SILICONFLOW_VISION_MODEL
SILICONFLOW_CLASSIFIER_MODEL = SETTINGS.SILICONFLOW_CLASSIFIER_MODEL

def _build_azure_base_url() -> str:
    if not AZURE_OPENAI_API_ENDPOINT or not AZURE_OPENAI_DEPLOYMENT:
        return ""
    return (
        f"{AZURE_OPENAI_API_ENDPOINT.rstrip('/')}/openai/deployments/"
        f"{AZURE_OPENAI_DEPLOYMENT}"
    )

AZURE_OPENAI_BASE_URL = SETTINGS.AZURE_OPENAI_BASE_URL or _build_azure_base_url()

AI_SUMMARY_PROVIDER = SETTINGS.AI_SUMMARY_PROVIDER
AI_SUMMARY_FALLBACK_PROVIDER = SETTINGS.AI_SUMMARY_FALLBACK_PROVIDER
AI_TRANSLATE_PROVIDER = SETTINGS.AI_TRANSLATE_PROVIDER
AI_TRANSLATE_FALLBACK_PROVIDER = SETTINGS.AI_TRANSLATE_FALLBACK_PROVIDER
AI_VISION_PROVIDER = SETTINGS.AI_VISION_PROVIDER
AI_VISION_FALLBACK_PROVIDER = SETTINGS.AI_VISION_FALLBACK_PROVIDER
AI_CLASSIFIER_PROVIDER = SETTINGS.AI_CLASSIFIER_PROVIDER
AI_CLASSIFIER_FALLBACK_PROVIDER = SETTINGS.AI_CLASSIFIER_FALLBACK_PROVIDER

CHAT_TOKEN_WARN_LIMIT = SETTINGS.CHAT_TOKEN_WARN_LIMIT
CHAT_TOKEN_LIMIT = SETTINGS.CHAT_TOKEN_LIMIT
CHAT_BATCH_WINDOW_SECONDS = SETTINGS.CHAT_BATCH_WINDOW_SECONDS

JUDGE0_API_URL = SETTINGS.JUDGE0_API_URL
JUDGE0_API_KEY = SETTINGS.JUDGE0_API_KEY
E2B_API_KEY = SETTINGS.E2B_API_KEY

IMAGE_GEN_API_URL = SETTINGS.IMAGE_GEN_API_URL
IMAGE_GEN_API_TOKEN = SETTINGS.IMAGE_GEN_API_TOKEN
IMAGE_GEN_TIMEOUT = SETTINGS.IMAGE_GEN_TIMEOUT
FISH_AUDIO_API_KEY = SETTINGS.FISH_AUDIO_API_KEY
FISH_AUDIO_MODEL = SETTINGS.FISH_AUDIO_MODEL
FISH_AUDIO_REFERENCE_ID = SETTINGS.FISH_AUDIO_REFERENCE_ID

ADMIN_USER_ID = SETTINGS.ADMIN_USER_ID
NEW_USER_BONUS_COINS = SETTINGS.NEW_USER_BONUS_COINS

POSTGRES_CONFIG = {
    "host": SETTINGS.POSTGRES_HOST,
    "user": SETTINGS.POSTGRES_USER,
    "password": SETTINGS.POSTGRES_PASSWORD,
    "database": SETTINGS.POSTGRES_DATABASE,
}

DB_POOL_SIZE = SETTINGS.DB_POOL_SIZE
DB_MAX_OVERFLOW = SETTINGS.DB_MAX_OVERFLOW
DB_POOL_RECYCLE = SETTINGS.DB_POOL_RECYCLE
DB_CONNECT_TIMEOUT = SETTINGS.DB_CONNECT_TIMEOUT
DB_SEARCH_PATH = SETTINGS.DB_SEARCH_PATH

def _build_postgres_dsn() -> str:
    user = POSTGRES_CONFIG.get("user") or "postgres"
    password = POSTGRES_CONFIG.get("password") or ""
    host = POSTGRES_CONFIG.get("host") or "localhost"
    database = POSTGRES_CONFIG.get("database") or "fogmoe"
    port = SETTINGS.POSTGRES_PORT or 5432

    auth = user
    if password:
        auth = f"{user}:{quote_plus(password)}"

    location = f"{host}:{port}" if port else host
    return f"postgresql+asyncpg://{auth}@{location}/{database}"

SQLALCHEMY_DATABASE_URI = SETTINGS.DATABASE_URL or _build_postgres_dsn()

# 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
LOG_LEVEL = SETTINGS.LOG_LEVEL
LOG_DIR = BASE_DIR / "logs"
LOG_FILE_PATH = LOG_DIR / "tgbot.log"


def _read_text_resource(relative_path: str) -> str:
    return (BASE_DIR / relative_path).read_text(encoding="utf-8")

# help 命令的帮助信息
HELP_TEXT = _read_text_resource("resources/telegram_help.md")

# AI 系统提示词
SYSTEM_PROMPT = _read_text_resource("resources/prompts/system_prompt.md")

def _parse_csv_value(raw_value: str | None) -> list[str]:
    if not raw_value:
        return []
    values = [item.strip().lower() for item in raw_value.split(",") if item.strip()]
    return values


# AI 服务的排序，按照优先级从高到低排序
AI_SERVICE_ORDER = _parse_csv_value(SETTINGS.AI_CHAT_ORDER)
AI_CHAT_TEXT_ONLY_MODELS = _parse_csv_value(SETTINGS.AI_CHAT_TEXT_ONLY_MODELS)
